module Privy
  module Models
    module Wallets
      type earn_fee_collect_action_response =
        {
          id: String,
          asset_address: String,
          :caip2 => String,
          created_at: Time,
          raw_amount: String?,
          status: Privy::Models::Wallets::wallet_action_status,
          type: Privy::Models::Wallets::EarnFeeCollectActionResponse::type_,
          vault_address: String,
          vault_id: String,
          wallet_id: String,
          amount: String?,
          asset: String,
          decimals: Integer,
          failure_reason: Privy::Wallets::FailureReason,
          steps: ::Array[Privy::Models::Wallets::wallet_action_step]
        }

      class EarnFeeCollectActionResponse < Privy::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor asset_address: String

        attr_accessor caip2: String

        attr_accessor created_at: Time

        attr_accessor raw_amount: String?

        attr_accessor status: Privy::Models::Wallets::wallet_action_status

        attr_accessor type: Privy::Models::Wallets::EarnFeeCollectActionResponse::type_

        attr_accessor vault_address: String

        attr_accessor vault_id: String

        attr_accessor wallet_id: String

        attr_accessor amount: String?

        attr_reader asset: String?

        def asset=: (String) -> String

        attr_reader decimals: Integer?

        def decimals=: (Integer) -> Integer

        attr_reader failure_reason: Privy::Wallets::FailureReason?

        def failure_reason=: (
          Privy::Wallets::FailureReason
        ) -> Privy::Wallets::FailureReason

        attr_reader steps: ::Array[Privy::Models::Wallets::wallet_action_step]?

        def steps=: (
          ::Array[Privy::Models::Wallets::wallet_action_step]
        ) -> ::Array[Privy::Models::Wallets::wallet_action_step]

        def initialize: (
          id: String,
          asset_address: String,
          caip2: String,
          created_at: Time,
          raw_amount: String?,
          status: Privy::Models::Wallets::wallet_action_status,
          type: Privy::Models::Wallets::EarnFeeCollectActionResponse::type_,
          vault_address: String,
          vault_id: String,
          wallet_id: String,
          ?amount: String?,
          ?asset: String,
          ?decimals: Integer,
          ?failure_reason: Privy::Wallets::FailureReason,
          ?steps: ::Array[Privy::Models::Wallets::wallet_action_step]
        ) -> void

        def to_hash: -> {
          id: String,
          asset_address: String,
          :caip2 => String,
          created_at: Time,
          raw_amount: String?,
          status: Privy::Models::Wallets::wallet_action_status,
          type: Privy::Models::Wallets::EarnFeeCollectActionResponse::type_,
          vault_address: String,
          vault_id: String,
          wallet_id: String,
          amount: String?,
          asset: String,
          decimals: Integer,
          failure_reason: Privy::Wallets::FailureReason,
          steps: ::Array[Privy::Models::Wallets::wallet_action_step]
        }

        type type_ = :earn_fee_collect

        module Type
          extend Privy::Internal::Type::Enum

          EARN_FEE_COLLECT: :earn_fee_collect

          def self?.values: -> ::Array[Privy::Models::Wallets::EarnFeeCollectActionResponse::type_]
        end
      end
    end
  end
end
