module Privy
  module Models
    module Wallets
      type earn_deposit_request_body =
        {
          vault_id: String,
          amount: String,
          nonce: String,
          raw_amount: String,
          reference_id: String
        }

      class EarnDepositRequestBody < Privy::Internal::Type::BaseModel
        attr_accessor vault_id: String

        attr_reader amount: String?

        def amount=: (String) -> String

        attr_reader nonce: String?

        def nonce=: (String) -> String

        attr_reader raw_amount: String?

        def raw_amount=: (String) -> String

        attr_reader reference_id: String?

        def reference_id=: (String) -> String

        def initialize: (
          vault_id: String,
          ?amount: String,
          ?nonce: String,
          ?raw_amount: String,
          ?reference_id: String
        ) -> void

        def to_hash: -> {
          vault_id: String,
          amount: String,
          nonce: String,
          raw_amount: String,
          reference_id: String
        }
      end
    end
  end
end
