module Privy
  module Models
    module Wallets
      type ethereum_earn_vault_details_response =
        Privy::Wallets::AaveVaultDetails | Privy::Wallets::MorphoVaultDetails

      module EthereumEarnVaultDetailsResponse
        extend Privy::Internal::Type::Union

        def self?.variants: -> ::Array[Privy::Models::Wallets::ethereum_earn_vault_details_response]
      end
    end
  end
end
