module Privy
  module Models
    module Wallets
      type ethereum_earn_provider = :morpho | :aave | :veda | :tempo

      module EthereumEarnProvider
        extend Privy::Internal::Type::Enum

        MORPHO: :morpho
        AAVE: :aave
        VEDA: :veda
        TEMPO: :tempo

        def self?.values: -> ::Array[Privy::Models::Wallets::ethereum_earn_provider]
      end
    end
  end
end
