module Privy
  module Models
    module Wallets
      type ethereum_earn_position_response =
        {
          asset: Privy::Wallets::EarnAsset,
          assets_in_vault: String,
          shares_in_vault: String,
          total_deposited: String,
          total_withdrawn: String,
          apy_allocation: ::Array[Privy::Wallets::EarnPositionApyAllocation],
          apy_bps: Integer
        }

      class EthereumEarnPositionResponse < Privy::Internal::Type::BaseModel
        attr_accessor asset: Privy::Wallets::EarnAsset

        attr_accessor assets_in_vault: String

        attr_accessor shares_in_vault: String

        attr_accessor total_deposited: String

        attr_accessor total_withdrawn: String

        attr_reader apy_allocation: ::Array[Privy::Wallets::EarnPositionApyAllocation]?

        def apy_allocation=: (
          ::Array[Privy::Wallets::EarnPositionApyAllocation]
        ) -> ::Array[Privy::Wallets::EarnPositionApyAllocation]

        attr_reader apy_bps: Integer?

        def apy_bps=: (Integer) -> Integer

        def initialize: (
          asset: Privy::Wallets::EarnAsset,
          assets_in_vault: String,
          shares_in_vault: String,
          total_deposited: String,
          total_withdrawn: String,
          ?apy_allocation: ::Array[Privy::Wallets::EarnPositionApyAllocation],
          ?apy_bps: Integer
        ) -> void

        def to_hash: -> {
          asset: Privy::Wallets::EarnAsset,
          assets_in_vault: String,
          shares_in_vault: String,
          total_deposited: String,
          total_withdrawn: String,
          apy_allocation: ::Array[Privy::Wallets::EarnPositionApyAllocation],
          apy_bps: Integer
        }
      end
    end
  end
end
