module Privy
  module Models
    module Wallets
      type failure_reason = { message: String, details: top }

      class FailureReason < Privy::Internal::Type::BaseModel
        attr_accessor message: String

        attr_reader details: top?

        def details=: (top) -> top

        def initialize: (message: String, ?details: top) -> void

        def to_hash: -> { message: String, details: top }
      end
    end
  end
end
