module Privy
  module Models
    module Wallets
      type svm_transaction_wallet_action_step =
        {
          :caip2 => String,
          status: Privy::Models::Wallets::svm_wallet_action_step_status,
          transaction_signature: String?,
          type: Privy::Models::Wallets::SvmTransactionWalletActionStep::type_,
          failure_reason: Privy::Wallets::FailureReason,
          finalized: bool,
          gas_credits_charged_usd: String
        }

      class SvmTransactionWalletActionStep < Privy::Internal::Type::BaseModel
        attr_accessor caip2: String

        attr_accessor status: Privy::Models::Wallets::svm_wallet_action_step_status

        attr_accessor transaction_signature: String?

        attr_accessor type: Privy::Models::Wallets::SvmTransactionWalletActionStep::type_

        attr_reader failure_reason: Privy::Wallets::FailureReason?

        def failure_reason=: (
          Privy::Wallets::FailureReason
        ) -> Privy::Wallets::FailureReason

        attr_reader finalized: bool?

        def finalized=: (bool) -> bool

        attr_reader gas_credits_charged_usd: String?

        def gas_credits_charged_usd=: (String) -> String

        def initialize: (
          caip2: String,
          status: Privy::Models::Wallets::svm_wallet_action_step_status,
          transaction_signature: String?,
          type: Privy::Models::Wallets::SvmTransactionWalletActionStep::type_,
          ?failure_reason: Privy::Wallets::FailureReason,
          ?finalized: bool,
          ?gas_credits_charged_usd: String
        ) -> void

        def to_hash: -> {
          :caip2 => String,
          status: Privy::Models::Wallets::svm_wallet_action_step_status,
          transaction_signature: String?,
          type: Privy::Models::Wallets::SvmTransactionWalletActionStep::type_,
          failure_reason: Privy::Wallets::FailureReason,
          finalized: bool,
          gas_credits_charged_usd: String
        }

        type type_ = :svm_transaction

        module Type
          extend Privy::Internal::Type::Enum

          SVM_TRANSACTION: :svm_transaction

          def self?.values: -> ::Array[Privy::Models::Wallets::SvmTransactionWalletActionStep::type_]
        end
      end
    end
  end
end
