module Privy
  module Models
    module Wallets
      type svm_wallet_action_step_status =
        :preparing
        | :queued
        | :pending
        | :confirmed
        | :rejected
        | :reverted
        | :failed

      module SvmWalletActionStepStatus
        extend Privy::Internal::Type::Enum

        PREPARING: :preparing
        QUEUED: :queued
        PENDING: :pending
        CONFIRMED: :confirmed
        REJECTED: :rejected
        REVERTED: :reverted
        FAILED: :failed

        def self?.values: -> ::Array[Privy::Models::Wallets::svm_wallet_action_step_status]
      end
    end
  end
end
