module Privy
  module Models
    module Wallets
      type transaction_get_params =
        {
          wallet_id: String,
          chain: Privy::Models::transaction_chain_name_input,
          token: Privy::Models::Wallets::TransactionGetParams::token,
          asset: Privy::Models::Wallets::TransactionGetParams::asset,
          cursor: String,
          include_archived: bool,
          limit: Float?,
          tx_hash: String
        }
        & Privy::Internal::Type::request_parameters

      class TransactionGetParams < Privy::Internal::Type::BaseModel
        extend Privy::Internal::Type::RequestParameters::Converter
        include Privy::Internal::Type::RequestParameters

        attr_accessor wallet_id: String

        attr_accessor chain: Privy::Models::transaction_chain_name_input

        attr_reader token: Privy::Models::Wallets::TransactionGetParams::token?

        def token=: (
          Privy::Models::Wallets::TransactionGetParams::token
        ) -> Privy::Models::Wallets::TransactionGetParams::token

        attr_reader asset: Privy::Models::Wallets::TransactionGetParams::asset?

        def asset=: (
          Privy::Models::Wallets::TransactionGetParams::asset
        ) -> Privy::Models::Wallets::TransactionGetParams::asset

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader include_archived: bool?

        def include_archived=: (bool) -> bool

        attr_accessor limit: Float?

        attr_reader tx_hash: String?

        def tx_hash=: (String) -> String

        def initialize: (
          wallet_id: String,
          chain: Privy::Models::transaction_chain_name_input,
          ?token: Privy::Models::Wallets::TransactionGetParams::token,
          ?asset: Privy::Models::Wallets::TransactionGetParams::asset,
          ?cursor: String,
          ?include_archived: bool,
          ?limit: Float?,
          ?tx_hash: String,
          ?request_options: Privy::request_opts
        ) -> void

        def to_hash: -> {
          wallet_id: String,
          chain: Privy::Models::transaction_chain_name_input,
          token: Privy::Models::Wallets::TransactionGetParams::token,
          asset: Privy::Models::Wallets::TransactionGetParams::asset,
          cursor: String,
          include_archived: bool,
          limit: Float?,
          tx_hash: String,
          request_options: Privy::RequestOptions
        }

        type token = String | ::Array[String]

        module Token
          extend Privy::Internal::Type::Union

          def self?.variants: -> ::Array[Privy::Models::Wallets::TransactionGetParams::token]

          TransactionTokenAddressInputArray: Privy::Internal::Type::Converter
        end

        type asset =
          :usdc
          | :"usdc.e"
          | :eth
          | :avax
          | :pol
          | :bnb
          | :usdt
          | :eurc
          | :usdb
          | :pathusd
          | :sol
          | :trx
          | ::Array[Privy::Models::wallet_asset]

        module Asset
          extend Privy::Internal::Type::Union

          def self?.variants: -> ::Array[Privy::Models::Wallets::TransactionGetParams::asset]

          USDC: :usdc
          USDC_E: :"usdc.e"
          ETH: :eth
          AVAX: :avax
          POL: :pol
          BNB: :bnb
          USDT: :usdt
          EURC: :eurc
          USDB: :usdb
          PATHUSD: :pathusd
          SOL: :sol
          TRX: :trx

          WalletAssetArray: Privy::Internal::Type::Converter
        end
      end
    end
  end
end
