module Privy
  module Models
    module WalletActionType = Wallets::WalletActionType

    module Wallets
      type wallet_action_type =
        :swap
        | :transfer
        | :earn_deposit
        | :earn_withdraw
        | :earn_incentive_claim
        | :earn_fee_collect

      module WalletActionType
        extend Privy::Internal::Type::Enum

        SWAP: :swap
        TRANSFER: :transfer
        EARN_DEPOSIT: :earn_deposit
        EARN_WITHDRAW: :earn_withdraw
        EARN_INCENTIVE_CLAIM: :earn_incentive_claim
        EARN_FEE_COLLECT: :earn_fee_collect

        def self?.values: -> ::Array[Privy::Models::Wallets::wallet_action_type]
      end
    end
  end
end
