module Privy
  module Models
    module WalletActionInclude = Wallets::WalletActionInclude

    module Wallets
      type wallet_action_include = :steps

      module WalletActionInclude
        extend Privy::Internal::Type::Enum

        STEPS: :steps

        def self?.values: -> ::Array[Privy::Models::Wallets::wallet_action_include]
      end
    end
  end
end
