module Privy
  module Models
    module Organizations
      type external_fiat_account_create_params =
        { organization_id: String } & Privy::Internal::Type::request_parameters

      class ExternalFiatAccountCreateParams < Privy::Models::CreateExternalFiatAccountRequestBody
        extend Privy::Internal::Type::RequestParameters::Converter
        include Privy::Internal::Type::RequestParameters

        def organization_id: -> String

        def organization_id=: (String _) -> String

        def initialize: (
          organization_id: String,
          ?request_options: Privy::request_opts
        ) -> void

        def to_hash: -> {
          organization_id: String,
          request_options: Privy::RequestOptions
        }
      end
    end
  end
end
