module Privy
  module Models
    module Organizations
      type kyb_list_params =
        { organization_id: String } & Privy::Internal::Type::request_parameters

      class KYBListParams < Privy::Internal::Type::BaseModel
        extend Privy::Internal::Type::RequestParameters::Converter
        include Privy::Internal::Type::RequestParameters

        attr_accessor organization_id: String

        def initialize: (
          organization_id: String,
          ?request_options: Privy::request_opts
        ) -> void

        def to_hash: -> {
          organization_id: String,
          request_options: Privy::RequestOptions
        }
      end
    end
  end
end
