module Privy
  module Resources
    class Organizations
      class ExternalFiatAccounts
        def create: (
          String organization_id,
          account: Privy::Models::external_fiat_account_data,
          account_owner_name: String,
          currency: String,
          provider: Privy::Models::CreateExternalFiatAccountRequestBody::provider,
          ?address: Privy::ExternalFiatAccountAddress,
          ?bank_name: String,
          ?environment: Privy::Models::environment,
          ?request_options: Privy::request_opts
        ) -> Privy::OrganizationExternalFiatAccountResponse

        def list: (
          String organization_id,
          provider: Privy::Models::orchestration_provider,
          ?environment: Privy::Models::environment,
          ?request_options: Privy::request_opts
        ) -> Privy::ListOrganizationExternalFiatAccountsResponse

        def delete: (
          String account_id,
          organization_id: String,
          ?request_options: Privy::request_opts
        ) -> Privy::SuccessResponse

        def get: (
          String account_id,
          organization_id: String,
          ?request_options: Privy::request_opts
        ) -> Privy::OrganizationExternalFiatAccountResponse

        def initialize: (client: Privy::Client) -> void
      end
    end
  end
end
