module Privy
  module Models
    module Wallets
      module Earn
        type ethereum_vault_details_params =
          { vault_id: String } & Privy::Internal::Type::request_parameters

        class EthereumVaultDetailsParams < Privy::Internal::Type::BaseModel
          extend Privy::Internal::Type::RequestParameters::Converter
          include Privy::Internal::Type::RequestParameters

          attr_accessor vault_id: String

          def initialize: (
            vault_id: String,
            ?request_options: Privy::request_opts
          ) -> void

          def to_hash: -> {
            vault_id: String,
            request_options: Privy::RequestOptions
          }
        end
      end
    end
  end
end
