module Privy
  module Resources
    class Wallets
      class DepositAccounts
        class Crypto
          attr_reader orders: Privy::Resources::Wallets::DepositAccounts::Crypto::Orders

          def create: (
            String wallet_id,
            create_crypto_deposit_account_request_body: Privy::Models::create_crypto_deposit_account_request_body,
            ?privy_authorization_signature: String,
            ?privy_idempotency_key: String,
            ?privy_request_expiry: String,
            ?request_options: Privy::request_opts
          ) -> Privy::CreateCryptoDepositAccountResponse

          def list: (
            String wallet_id,
            ?cursor: String,
            ?limit: Integer,
            ?request_options: Privy::request_opts
          ) -> Privy::Internal::Cursor[Privy::CryptoDepositAddressRoute]

          def get_config: (
            ?request_options: Privy::request_opts
          ) -> Privy::CryptoDepositAccountConfigResponse

          def get_next_order: (
            String wallet_id,
            after: Time,
            ?request_options: Privy::request_opts
          ) -> Privy::GetCryptoDepositAccountNextOrderResponse

          def quote: (
            destination: Privy::DepositAccountCryptoQuoteAsset,
            source: Privy::DepositAccountCryptoQuoteAsset,
            ?input_amount: String,
            ?slippage_bps: Integer,
            ?request_options: Privy::request_opts
          ) -> Privy::DepositAccountCryptoQuoteResponse

          def initialize: (client: Privy::Client) -> void
        end
      end
    end
  end
end
