module Privy
  module Models
    type account_wallet_configuration_item =
      { chain_type: Privy::Models::first_class_chain_type }

    class AccountWalletConfigurationItem < Privy::Internal::Type::BaseModel
      attr_accessor chain_type: Privy::Models::first_class_chain_type

      def initialize: (
        chain_type: Privy::Models::first_class_chain_type
      ) -> void

      def to_hash: -> { chain_type: Privy::Models::first_class_chain_type }
    end
  end
end
