module Privy
  module Models
    type accounts_list_response =
      { data: ::Array[Privy::AccountResponse], next_cursor: String? }

    class AccountsListResponse < Privy::Internal::Type::BaseModel
      attr_accessor data: ::Array[Privy::AccountResponse]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Privy::AccountResponse],
        next_cursor: String?
      ) -> void

      def to_hash: -> {
        data: ::Array[Privy::AccountResponse],
        next_cursor: String?
      }
    end
  end
end
