module Privy
  module Models
    type account_balance_params =
      { testnet_mode: Privy::Models::chain_testnet_mode }

    class AccountBalanceParams < Privy::Internal::Type::BaseModel
      attr_reader testnet_mode: Privy::Models::chain_testnet_mode?

      def testnet_mode=: (
        Privy::Models::chain_testnet_mode
      ) -> Privy::Models::chain_testnet_mode

      def initialize: (?testnet_mode: Privy::Models::chain_testnet_mode) -> void

      def to_hash: -> { testnet_mode: Privy::Models::chain_testnet_mode }
    end
  end
end
