module Privy
  module Models
    type alchemy_paymaster_context = { policy_id: String }

    class AlchemyPaymasterContext < Privy::Internal::Type::BaseModel
      attr_accessor policy_id: String

      def initialize: (policy_id: String) -> void

      def to_hash: -> { policy_id: String }
    end
  end
end
