module Privy
  module Models
    type amount_type = :exact_input | :exact_output

    module AmountType
      extend Privy::Internal::Type::Enum

      EXACT_INPUT: :exact_input
      EXACT_OUTPUT: :exact_output

      def self?.values: -> ::Array[Privy::Models::amount_type]
    end
  end
end
