module Privy
  module Models
    type authenticate_jwt_input =
      { token: String, mode: Privy::Models::authenticate_mode_option }

    class AuthenticateJwtInput < Privy::Internal::Type::BaseModel
      attr_reader token: String?

      def token=: (String) -> String

      attr_reader mode: Privy::Models::authenticate_mode_option?

      def mode=: (
        Privy::Models::authenticate_mode_option
      ) -> Privy::Models::authenticate_mode_option

      def initialize: (
        ?token: String,
        ?mode: Privy::Models::authenticate_mode_option
      ) -> void

      def to_hash: -> {
        token: String,
        mode: Privy::Models::authenticate_mode_option
      }
    end
  end
end
