module Privy
  module Models
    type authorization_key_dashboard_response =
      {
        id: String,
        created_at: Float,
        display_name: String?,
        public_key: String,
        role: Privy::Models::authorization_key_role?
      }

    class AuthorizationKeyDashboardResponse < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Float

      attr_accessor display_name: String?

      attr_accessor public_key: String

      attr_accessor role: Privy::Models::authorization_key_role?

      def initialize: (
        id: String,
        created_at: Float,
        display_name: String?,
        public_key: String,
        role: Privy::Models::authorization_key_role?
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Float,
        display_name: String?,
        public_key: String,
        role: Privy::Models::authorization_key_role?
      }
    end
  end
end
