module Privy
  module Models
    type automation_deposit_trigger_config =
      {
        assets: Privy::Models::automation_asset_filter,
        type: Privy::Models::AutomationDepositTriggerConfig::type_
      }

    class AutomationDepositTriggerConfig < Privy::Internal::Type::BaseModel
      attr_accessor assets: Privy::Models::automation_asset_filter

      attr_accessor type: Privy::Models::AutomationDepositTriggerConfig::type_

      def initialize: (
        assets: Privy::Models::automation_asset_filter,
        type: Privy::Models::AutomationDepositTriggerConfig::type_
      ) -> void

      def to_hash: -> {
        assets: Privy::Models::automation_asset_filter,
        type: Privy::Models::AutomationDepositTriggerConfig::type_
      }

      type type_ = :deposit

      module Type
        extend Privy::Internal::Type::Enum

        DEPOSIT: :deposit

        def self?.values: -> ::Array[Privy::Models::AutomationDepositTriggerConfig::type_]
      end
    end
  end
end
