module Privy
  module Models
    type automation_destination_asset_input = { asset: String, chain: String }

    class AutomationDestinationAssetInput < Privy::Models::AutomationDestinationAsset
      def asset: -> String?

      def asset=: (String _) -> String

      def chain: -> String?

      def chain=: (String _) -> String

      def initialize: (?asset: String, ?chain: String) -> void

      def to_hash: -> { asset: String, chain: String }
    end
  end
end
