module Privy
  module Models
    type automation_action_config_input =
      Privy::AutomationSwapActionConfigInput
      | Privy::AutomationEarnDepositActionConfigInput

    module AutomationActionConfigInput
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::automation_action_config_input]
    end
  end
end
