module Privy
  module Models
    type automation_config =
      {
        action: Privy::AutomationActionConfig,
        trigger: Privy::AutomationTriggerConfig
      }

    class AutomationConfig < Privy::Internal::Type::BaseModel
      attr_accessor action: Privy::AutomationActionConfig

      attr_accessor trigger: Privy::AutomationTriggerConfig

      def initialize: (
        action: Privy::AutomationActionConfig,
        trigger: Privy::AutomationTriggerConfig
      ) -> void

      def to_hash: -> {
        action: Privy::AutomationActionConfig,
        trigger: Privy::AutomationTriggerConfig
      }
    end
  end
end
