module Privy
  module Models
    type automation_deposit_trigger_config_input =
      {
        assets: Privy::Models::automation_asset_filter_input,
        type: Privy::Models::AutomationDepositTriggerConfigInput::type_
      }

    class AutomationDepositTriggerConfigInput < Privy::Internal::Type::BaseModel
      attr_accessor assets: Privy::Models::automation_asset_filter_input

      attr_accessor type: Privy::Models::AutomationDepositTriggerConfigInput::type_

      def initialize: (
        assets: Privy::Models::automation_asset_filter_input,
        type: Privy::Models::AutomationDepositTriggerConfigInput::type_
      ) -> void

      def to_hash: -> {
        assets: Privy::Models::automation_asset_filter_input,
        type: Privy::Models::AutomationDepositTriggerConfigInput::type_
      }

      type type_ = :deposit

      module Type
        extend Privy::Internal::Type::Enum

        DEPOSIT: :deposit

        def self?.values: -> ::Array[Privy::Models::AutomationDepositTriggerConfigInput::type_]
      end
    end
  end
end
