module Privy
  module Models
    type automation_action_config =
      Privy::AutomationSwapActionConfig
      | Privy::AutomationEarnDepositActionConfig

    module AutomationActionConfig
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::automation_action_config]
    end
  end
end
