module Privy
  module Models
    type automation_action_config =
      {
        destination_chain_asset: Privy::AutomationDestinationAsset,
        type: Privy::Models::AutomationActionConfig::type_
      }

    class AutomationActionConfig < Privy::Internal::Type::BaseModel
      attr_accessor destination_chain_asset: Privy::AutomationDestinationAsset

      attr_accessor type: Privy::Models::AutomationActionConfig::type_

      def initialize: (
        destination_chain_asset: Privy::AutomationDestinationAsset,
        type: Privy::Models::AutomationActionConfig::type_
      ) -> void

      def to_hash: -> {
        destination_chain_asset: Privy::AutomationDestinationAsset,
        type: Privy::Models::AutomationActionConfig::type_
      }

      type type_ = :swap

      module Type
        extend Privy::Internal::Type::Enum

        SWAP: :swap

        def self?.values: -> ::Array[Privy::Models::AutomationActionConfig::type_]
      end
    end
  end
end
