module Privy
  module Models
    type bridge_create_fiat_deposit_account_request_body =
      {
        destination: Privy::FiatDepositAccountDestination,
        provider: Privy::Models::BridgeCreateFiatDepositAccountRequestBody::provider,
        source: Privy::CreateFiatDepositAccountSource,
        environment: Privy::Models::environment
      }

    class BridgeCreateFiatDepositAccountRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor destination: Privy::FiatDepositAccountDestination

      attr_accessor provider: Privy::Models::BridgeCreateFiatDepositAccountRequestBody::provider

      attr_accessor source: Privy::CreateFiatDepositAccountSource

      attr_reader environment: Privy::Models::environment?

      def environment=: (
        Privy::Models::environment
      ) -> Privy::Models::environment

      def initialize: (
        destination: Privy::FiatDepositAccountDestination,
        provider: Privy::Models::BridgeCreateFiatDepositAccountRequestBody::provider,
        source: Privy::CreateFiatDepositAccountSource,
        ?environment: Privy::Models::environment
      ) -> void

      def to_hash: -> {
        destination: Privy::FiatDepositAccountDestination,
        provider: Privy::Models::BridgeCreateFiatDepositAccountRequestBody::provider,
        source: Privy::CreateFiatDepositAccountSource,
        environment: Privy::Models::environment
      }

      type provider = :bridge

      module Provider
        extend Privy::Internal::Type::Enum

        BRIDGE: :bridge

        def self?.values: -> ::Array[Privy::Models::BridgeCreateFiatDepositAccountRequestBody::provider]
      end
    end
  end
end
