module Privy
  module Models
    type bridge_fiat_virtual_account_deposit_instructions =
      Privy::BridgeUsdFiatVirtualAccountDepositInstructions
      | Privy::BridgeEurFiatVirtualAccountDepositInstructions
      | Privy::BridgeMxnFiatVirtualAccountDepositInstructions
      | Privy::BridgeBrlFiatVirtualAccountDepositInstructions
      | Privy::BridgeGbpFiatVirtualAccountDepositInstructions

    module BridgeFiatVirtualAccountDepositInstructions
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::bridge_fiat_virtual_account_deposit_instructions]
    end
  end
end
