module Privy
  module Models
    type bridge_sandbox_fiat_virtual_account_request =
      {
        destination: Privy::BridgeFiatVirtualAccountDestination,
        provider: Privy::Models::BridgeSandboxFiatVirtualAccountRequest::provider,
        source: Privy::BridgeFiatVirtualAccountSource
      }

    class BridgeSandboxFiatVirtualAccountRequest < Privy::Internal::Type::BaseModel
      attr_accessor destination: Privy::BridgeFiatVirtualAccountDestination

      attr_accessor provider: Privy::Models::BridgeSandboxFiatVirtualAccountRequest::provider

      attr_accessor source: Privy::BridgeFiatVirtualAccountSource

      def initialize: (
        destination: Privy::BridgeFiatVirtualAccountDestination,
        provider: Privy::Models::BridgeSandboxFiatVirtualAccountRequest::provider,
        source: Privy::BridgeFiatVirtualAccountSource
      ) -> void

      def to_hash: -> {
        destination: Privy::BridgeFiatVirtualAccountDestination,
        provider: Privy::Models::BridgeSandboxFiatVirtualAccountRequest::provider,
        source: Privy::BridgeFiatVirtualAccountSource
      }

      type provider = :"bridge-sandbox"

      module Provider
        extend Privy::Internal::Type::Enum

        BRIDGE_SANDBOX: :"bridge-sandbox"

        def self?.values: -> ::Array[Privy::Models::BridgeSandboxFiatVirtualAccountRequest::provider]
      end
    end
  end
end
