module Privy
  module Models
    type card_issuing_customer_rejected_response =
      {
        status: Privy::Models::CardIssuingCustomerRejectedResponse::status,
        rejection_reasons: ::Array[Privy::CardIssuingCustomerRejectionReason]
      }

    class CardIssuingCustomerRejectedResponse < Privy::Internal::Type::BaseModel
      attr_accessor status: Privy::Models::CardIssuingCustomerRejectedResponse::status

      attr_reader rejection_reasons: ::Array[Privy::CardIssuingCustomerRejectionReason]?

      def rejection_reasons=: (
        ::Array[Privy::CardIssuingCustomerRejectionReason]
      ) -> ::Array[Privy::CardIssuingCustomerRejectionReason]

      def initialize: (
        status: Privy::Models::CardIssuingCustomerRejectedResponse::status,
        ?rejection_reasons: ::Array[Privy::CardIssuingCustomerRejectionReason]
      ) -> void

      def to_hash: -> {
        status: Privy::Models::CardIssuingCustomerRejectedResponse::status,
        rejection_reasons: ::Array[Privy::CardIssuingCustomerRejectionReason]
      }

      type status = :rejected

      module Status
        extend Privy::Internal::Type::Enum

        REJECTED: :rejected

        def self?.values: -> ::Array[Privy::Models::CardIssuingCustomerRejectedResponse::status]
      end
    end
  end
end
