module Privy
  module Models
    type card_issuing_config =
      { card_logo_url: String?, publishable_key: String }

    class CardIssuingConfig < Privy::Internal::Type::BaseModel
      attr_accessor card_logo_url: String?

      attr_accessor publishable_key: String

      def initialize: (card_logo_url: String?, publishable_key: String) -> void

      def to_hash: -> { card_logo_url: String?, publishable_key: String }
    end
  end
end
