module Privy
  module Models
    type card_issuing_card_response =
      {
        id: String,
        asset: String,
        balance_formatted: String?,
        brand: String?,
        cardholder: Privy::CardIssuingCardholder,
        chain_id: String,
        created_at: Integer,
        exp_month: Integer?,
        exp_year: Integer?,
        :last4 => String?,
        provider_id: String,
        status: String,
        wallet_id: String
      }

    class CardIssuingCardResponse < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor asset: String

      attr_accessor balance_formatted: String?

      attr_accessor brand: String?

      attr_accessor cardholder: Privy::CardIssuingCardholder

      attr_accessor chain_id: String

      attr_accessor created_at: Integer

      attr_accessor exp_month: Integer?

      attr_accessor exp_year: Integer?

      attr_accessor last4: String?

      attr_accessor provider_id: String

      attr_accessor status: String

      attr_accessor wallet_id: String

      def initialize: (
        id: String,
        asset: String,
        balance_formatted: String?,
        brand: String?,
        cardholder: Privy::CardIssuingCardholder,
        chain_id: String,
        created_at: Integer,
        exp_month: Integer?,
        exp_year: Integer?,
        last4: String?,
        provider_id: String,
        status: String,
        wallet_id: String
      ) -> void

      def to_hash: -> {
        id: String,
        asset: String,
        balance_formatted: String?,
        brand: String?,
        cardholder: Privy::CardIssuingCardholder,
        chain_id: String,
        created_at: Integer,
        exp_month: Integer?,
        exp_year: Integer?,
        :last4 => String?,
        provider_id: String,
        status: String,
        wallet_id: String
      }
    end
  end
end
