module Privy
  module Models
    type card_issuing_customer_consents_request_body =
      {
        environment: Privy::Models::environment,
        accept_bank_terms: bool,
        accept_electronic_disclosure: bool
      }

    class CardIssuingCustomerConsentsRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor environment: Privy::Models::environment

      attr_reader accept_bank_terms: bool?

      def accept_bank_terms=: (bool) -> bool

      attr_reader accept_electronic_disclosure: bool?

      def accept_electronic_disclosure=: (bool) -> bool

      def initialize: (
        environment: Privy::Models::environment,
        ?accept_bank_terms: bool,
        ?accept_electronic_disclosure: bool
      ) -> void

      def to_hash: -> {
        environment: Privy::Models::environment,
        accept_bank_terms: bool,
        accept_electronic_disclosure: bool
      }
    end
  end
end
