module Privy
  module Models
    type card_issuing_transaction_status =
      :pending | :posted | :declined | :expired | :reversed

    module CardIssuingTransactionStatus
      extend Privy::Internal::Type::Enum

      PENDING: :pending
      POSTED: :posted
      DECLINED: :declined
      EXPIRED: :expired
      REVERSED: :reversed

      def self?.values: -> ::Array[Privy::Models::card_issuing_transaction_status]
    end
  end
end
