module Privy
  module Models
    type card_issuing_list_transactions_input =
      {
        environment: Privy::Models::environment,
        cursor: String,
        limit: Integer
      }

    class CardIssuingListTransactionsInput < Privy::Internal::Type::BaseModel
      attr_accessor environment: Privy::Models::environment

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        environment: Privy::Models::environment,
        ?cursor: String,
        ?limit: Integer
      ) -> void

      def to_hash: -> {
        environment: Privy::Models::environment,
        cursor: String,
        limit: Integer
      }
    end
  end
end
