module Privy
  module Models
    type card_issuing_transaction_status =
      :pending | :completed | :declined | :disputed | :refunded

    module CardIssuingTransactionStatus
      extend Privy::Internal::Type::Enum

      PENDING: :pending
      COMPLETED: :completed
      DECLINED: :declined
      DISPUTED: :disputed
      REFUNDED: :refunded

      def self?.values: -> ::Array[Privy::Models::card_issuing_transaction_status]
    end
  end
end
