module Privy
  module Models
    type card_issuing_customer_provider_terms_required_response =
      {
        status: Privy::Models::CardIssuingCustomerProviderTermsRequiredResponse::status,
        tos_url: String
      }

    class CardIssuingCustomerProviderTermsRequiredResponse < Privy::Internal::Type::BaseModel
      attr_accessor status: Privy::Models::CardIssuingCustomerProviderTermsRequiredResponse::status

      attr_accessor tos_url: String

      def initialize: (
        status: Privy::Models::CardIssuingCustomerProviderTermsRequiredResponse::status,
        tos_url: String
      ) -> void

      def to_hash: -> {
        status: Privy::Models::CardIssuingCustomerProviderTermsRequiredResponse::status,
        tos_url: String
      }

      type status = :provider_terms_required

      module Status
        extend Privy::Internal::Type::Enum

        PROVIDER_TERMS_REQUIRED: :provider_terms_required

        def self?.values: -> ::Array[Privy::Models::CardIssuingCustomerProviderTermsRequiredResponse::status]
      end
    end
  end
end
