module Privy
  module Models
    type condition_operator =
      :eq | :gt | :gte | :lt | :lte | :in | :in_condition_set

    module ConditionOperator
      extend Privy::Internal::Type::Enum

      EQ: :eq
      GT: :gt
      GTE: :gte
      LT: :lt
      LTE: :lte
      IN: :in
      IN_CONDITION_SET: :in_condition_set

      def self?.values: -> ::Array[Privy::Models::condition_operator]
    end
  end
end
