module Privy
  module Models
    type create_organization_secret_response = { organization_secret: String }

    class CreateOrganizationSecretResponse < Privy::Models::OrganizationSecretView
      def organization_secret: -> String

      def organization_secret=: (String _) -> String

      def initialize: (organization_secret: String) -> void

      def to_hash: -> { organization_secret: String }
    end
  end
end
