module Privy
  module Models
    type create_crypto_deposit_account_request_body =
      Privy::CreateCryptoDepositAccountWithConfigRequestBody
      | Privy::CreateCryptoDepositAccountWithRouteRequestBody

    module CreateCryptoDepositAccountRequestBody
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::create_crypto_deposit_account_request_body]
    end
  end
end
