module Privy
  module Models
    type create_crypto_deposit_account_response =
      { deposit_accounts: ::Array[Privy::CryptoDepositAddressRoute] }

    class CreateCryptoDepositAccountResponse < Privy::Internal::Type::BaseModel
      attr_accessor deposit_accounts: ::Array[Privy::CryptoDepositAddressRoute]

      def initialize: (
        deposit_accounts: ::Array[Privy::CryptoDepositAddressRoute]
      ) -> void

      def to_hash: -> {
        deposit_accounts: ::Array[Privy::CryptoDepositAddressRoute]
      }
    end
  end
end
