module Privy
  module Models
    type create_stripe_onramp_session_response =
      {
        id: String,
        session_id: String,
        transaction_details: Privy::OnrampSessionTransactionDetails?
      }

    class CreateStripeOnrampSessionResponse < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor session_id: String

      attr_accessor transaction_details: Privy::OnrampSessionTransactionDetails?

      def initialize: (
        id: String,
        session_id: String,
        ?transaction_details: Privy::OnrampSessionTransactionDetails?
      ) -> void

      def to_hash: -> {
        id: String,
        session_id: String,
        transaction_details: Privy::OnrampSessionTransactionDetails?
      }
    end
  end
end
