module Privy
  module Models
    type create_link_auth_intent_input = { email: String }

    class CreateLinkAuthIntentInput < Privy::Internal::Type::BaseModel
      attr_reader email: String?

      def email=: (String) -> String

      def initialize: (?email: String) -> void

      def to_hash: -> { email: String }
    end
  end
end
