module Privy
  module Models
    type create_crypto_deposit_account_with_config_request_body =
      { deposit_config_id: String }

    class CreateCryptoDepositAccountWithConfigRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor deposit_config_id: String

      def initialize: (deposit_config_id: String) -> void

      def to_hash: -> { deposit_config_id: String }
    end
  end
end
