module Privy
  module Models
    type create_crypto_deposit_account_with_route_request_body =
      {
        destination: Privy::CryptoDepositAsset,
        source: Privy::Models::crypto_deposit_asset_filter
      }

    class CreateCryptoDepositAccountWithRouteRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor destination: Privy::CryptoDepositAsset

      attr_accessor source: Privy::Models::crypto_deposit_asset_filter

      def initialize: (
        destination: Privy::CryptoDepositAsset,
        source: Privy::Models::crypto_deposit_asset_filter
      ) -> void

      def to_hash: -> {
        destination: Privy::CryptoDepositAsset,
        source: Privy::Models::crypto_deposit_asset_filter
      }
    end
  end
end
