module Privy
  module Models
    type cross_app_smart_wallet = { address: String }

    class CrossAppSmartWallet < Privy::Internal::Type::BaseModel
      attr_accessor address: String

      def initialize: (address: String) -> void

      def to_hash: -> { address: String }
    end
  end
end
