module Privy
  module Models
    type custom_token_transfer_source =
      { asset_address: String, chain: String, amount: String }

    class CustomTokenTransferSource < Privy::Internal::Type::BaseModel
      attr_accessor asset_address: String

      attr_accessor chain: String

      attr_reader amount: String?

      def amount=: (String) -> String

      def initialize: (
        asset_address: String,
        chain: String,
        ?amount: String
      ) -> void

      def to_hash: -> { asset_address: String, chain: String, amount: String }
    end
  end
end
