module Privy
  module Models
    type custodian_transaction_wallet_action_step =
      {
        custodian: String,
        status: Privy::Models::custodian_transaction_wallet_action_step_status,
        type: Privy::Models::CustodianTransactionWalletActionStep::type_,
        failure_reason: Privy::FailureReason
      }

    class CustodianTransactionWalletActionStep < Privy::Internal::Type::BaseModel
      attr_accessor custodian: String

      attr_accessor status: Privy::Models::custodian_transaction_wallet_action_step_status

      attr_accessor type: Privy::Models::CustodianTransactionWalletActionStep::type_

      attr_reader failure_reason: Privy::FailureReason?

      def failure_reason=: (Privy::FailureReason) -> Privy::FailureReason

      def initialize: (
        custodian: String,
        status: Privy::Models::custodian_transaction_wallet_action_step_status,
        type: Privy::Models::CustodianTransactionWalletActionStep::type_,
        ?failure_reason: Privy::FailureReason
      ) -> void

      def to_hash: -> {
        custodian: String,
        status: Privy::Models::custodian_transaction_wallet_action_step_status,
        type: Privy::Models::CustodianTransactionWalletActionStep::type_,
        failure_reason: Privy::FailureReason
      }

      type type_ = :custodian_transaction

      module Type
        extend Privy::Internal::Type::Enum

        CUSTODIAN_TRANSACTION: :custodian_transaction

        def self?.values: -> ::Array[Privy::Models::CustodianTransactionWalletActionStep::type_]
      end
    end
  end
end
