module Privy
  module Models
    type custodial_wallet_chain_type = :ethereum | :solana

    module CustodialWalletChainType
      extend Privy::Internal::Type::Enum

      ETHEREUM: :ethereum
      SOLANA: :solana

      def self?.values: -> ::Array[Privy::Models::custodial_wallet_chain_type]
    end
  end
end
