module Privy
  module Models
    type custodial_wallet_provider = :bridge

    module CustodialWalletProvider
      extend Privy::Internal::Type::Enum

      BRIDGE: :bridge

      def self?.values: -> ::Array[Privy::Models::custodial_wallet_provider]
    end
  end
end
