module Privy
  module Models
    type deposit_started_destination = { asset: String, chain: String }

    class DepositStartedDestination < Privy::Internal::Type::BaseModel
      attr_accessor asset: String

      attr_accessor chain: String

      def initialize: (asset: String, chain: String) -> void

      def to_hash: -> { asset: String, chain: String }
    end
  end
end
