module Privy
  module Models
    type earn_claimed_rewards_query = { chain: String }

    class EarnClaimedRewardsQuery < Privy::Internal::Type::BaseModel
      attr_accessor chain: String

      def initialize: (chain: String) -> void

      def to_hash: -> { chain: String }
    end
  end
end
