module Privy
  module Models
    type encrypted_wallet_authenticate_response =
      {
        encrypted_authorization_key: Privy::EncryptedAuthorizationKey,
        expires_at: Float,
        wallets: ::Array[Privy::Wallet]
      }

    class EncryptedWalletAuthenticateResponse < Privy::Internal::Type::BaseModel
      attr_accessor encrypted_authorization_key: Privy::EncryptedAuthorizationKey

      attr_accessor expires_at: Float

      attr_accessor wallets: ::Array[Privy::Wallet]

      def initialize: (
        encrypted_authorization_key: Privy::EncryptedAuthorizationKey,
        expires_at: Float,
        wallets: ::Array[Privy::Wallet]
      ) -> void

      def to_hash: -> {
        encrypted_authorization_key: Privy::EncryptedAuthorizationKey,
        expires_at: Float,
        wallets: ::Array[Privy::Wallet]
      }
    end
  end
end
