module Privy
  module Models
    type ethereum_sign_transaction_rpc_input =
      {
        method_: Privy::Models::EthereumSignTransactionRpcInput::method_,
        params: Privy::EthereumSignTransactionRpcInputParams,
        address: String,
        chain_type: Privy::Models::EthereumSignTransactionRpcInput::chain_type,
        wallet_id: String
      }

    class EthereumSignTransactionRpcInput < Privy::Internal::Type::BaseModel
      attr_accessor method_: Privy::Models::EthereumSignTransactionRpcInput::method_

      attr_accessor params: Privy::EthereumSignTransactionRpcInputParams

      attr_reader address: String?

      def address=: (String) -> String

      attr_reader chain_type: Privy::Models::EthereumSignTransactionRpcInput::chain_type?

      def chain_type=: (
        Privy::Models::EthereumSignTransactionRpcInput::chain_type
      ) -> Privy::Models::EthereumSignTransactionRpcInput::chain_type

      attr_reader wallet_id: String?

      def wallet_id=: (String) -> String

      def initialize: (
        method_: Privy::Models::EthereumSignTransactionRpcInput::method_,
        params: Privy::EthereumSignTransactionRpcInputParams,
        ?address: String,
        ?chain_type: Privy::Models::EthereumSignTransactionRpcInput::chain_type,
        ?wallet_id: String
      ) -> void

      def to_hash: -> {
        method_: Privy::Models::EthereumSignTransactionRpcInput::method_,
        params: Privy::EthereumSignTransactionRpcInputParams,
        address: String,
        chain_type: Privy::Models::EthereumSignTransactionRpcInput::chain_type,
        wallet_id: String
      }

      type method_ = :eth_signTransaction

      module Method
        extend Privy::Internal::Type::Enum

        ETH_SIGN_TRANSACTION: :eth_signTransaction

        def self?.values: -> ::Array[Privy::Models::EthereumSignTransactionRpcInput::method_]
      end

      type chain_type = :ethereum

      module ChainType
        extend Privy::Internal::Type::Enum

        ETHEREUM: :ethereum

        def self?.values: -> ::Array[Privy::Models::EthereumSignTransactionRpcInput::chain_type]
      end
    end
  end
end
