module Privy
  module Models
    type ethereum_typed_data_domain_condition =
      {
        field: Privy::Models::ethereum_typed_data_domain_condition_field,
        field_source: Privy::Models::EthereumTypedDataDomainCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      }

    class EthereumTypedDataDomainCondition < Privy::Internal::Type::BaseModel
      attr_accessor field: Privy::Models::ethereum_typed_data_domain_condition_field

      attr_accessor field_source: Privy::Models::EthereumTypedDataDomainCondition::field_source

      attr_accessor operator: Privy::Models::condition_operator

      attr_accessor value: Privy::Models::condition_value

      def initialize: (
        field: Privy::Models::ethereum_typed_data_domain_condition_field,
        field_source: Privy::Models::EthereumTypedDataDomainCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      ) -> void

      def to_hash: -> {
        field: Privy::Models::ethereum_typed_data_domain_condition_field,
        field_source: Privy::Models::EthereumTypedDataDomainCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      }

      type field_source = :ethereum_typed_data_domain

      module FieldSource
        extend Privy::Internal::Type::Enum

        ETHEREUM_TYPED_DATA_DOMAIN: :ethereum_typed_data_domain

        def self?.values: -> ::Array[Privy::Models::EthereumTypedDataDomainCondition::field_source]
      end
    end
  end
end
