module Privy
  module Models
    type ethereum_yield_position_response =
      {
        asset: Privy::VaultAsset,
        assets_in_vault: String,
        shares_in_vault: String,
        total_deposited: String,
        total_withdrawn: String
      }

    class EthereumYieldPositionResponse < Privy::Internal::Type::BaseModel
      attr_accessor asset: Privy::VaultAsset

      attr_accessor assets_in_vault: String

      attr_accessor shares_in_vault: String

      attr_accessor total_deposited: String

      attr_accessor total_withdrawn: String

      def initialize: (
        asset: Privy::VaultAsset,
        assets_in_vault: String,
        shares_in_vault: String,
        total_deposited: String,
        total_withdrawn: String
      ) -> void

      def to_hash: -> {
        asset: Privy::VaultAsset,
        assets_in_vault: String,
        shares_in_vault: String,
        total_deposited: String,
        total_withdrawn: String
      }
    end
  end
end
