module Privy
  module Models
    type ethereum_yield_positions_input = { vault_id: String }

    class EthereumYieldPositionsInput < Privy::Internal::Type::BaseModel
      attr_accessor vault_id: String

      def initialize: (vault_id: String) -> void

      def to_hash: -> { vault_id: String }
    end
  end
end
