module Privy
  module Models
    type ethereum_sign_user_operation_rpc_response_data =
      {
        encoding: Privy::Models::EthereumSignUserOperationRpcResponseData::encoding,
        signature: String
      }

    class EthereumSignUserOperationRpcResponseData < Privy::Internal::Type::BaseModel
      attr_accessor encoding: Privy::Models::EthereumSignUserOperationRpcResponseData::encoding

      attr_accessor signature: String

      def initialize: (
        encoding: Privy::Models::EthereumSignUserOperationRpcResponseData::encoding,
        signature: String
      ) -> void

      def to_hash: -> {
        encoding: Privy::Models::EthereumSignUserOperationRpcResponseData::encoding,
        signature: String
      }

      type encoding = :hex

      module Encoding
        extend Privy::Internal::Type::Enum

        HEX: :hex

        def self?.values: -> ::Array[Privy::Models::EthereumSignUserOperationRpcResponseData::encoding]
      end
    end
  end
end
