module Privy
  module Models
    type ethereum_sign_user_operation_rpc_response =
      {
        data: Privy::EthereumSignUserOperationRpcResponseData,
        method_: Privy::Models::EthereumSignUserOperationRpcResponse::method_
      }

    class EthereumSignUserOperationRpcResponse < Privy::Internal::Type::BaseModel
      attr_accessor data: Privy::EthereumSignUserOperationRpcResponseData

      attr_accessor method_: Privy::Models::EthereumSignUserOperationRpcResponse::method_

      def initialize: (
        data: Privy::EthereumSignUserOperationRpcResponseData,
        method_: Privy::Models::EthereumSignUserOperationRpcResponse::method_
      ) -> void

      def to_hash: -> {
        data: Privy::EthereumSignUserOperationRpcResponseData,
        method_: Privy::Models::EthereumSignUserOperationRpcResponse::method_
      }

      type method_ = :eth_signUserOperation

      module Method
        extend Privy::Internal::Type::Enum

        ETH_SIGN_USER_OPERATION: :eth_signUserOperation

        def self?.values: -> ::Array[Privy::Models::EthereumSignUserOperationRpcResponse::method_]
      end
    end
  end
end
