module Privy
  module Models
    type ethereum_yield_claim_reward =
      { amount: String, token_address: String, token_symbol: String }

    class EthereumYieldClaimReward < Privy::Internal::Type::BaseModel
      attr_accessor amount: String

      attr_accessor token_address: String

      attr_accessor token_symbol: String

      def initialize: (
        amount: String,
        token_address: String,
        token_symbol: String
      ) -> void

      def to_hash: -> {
        amount: String,
        token_address: String,
        token_symbol: String
      }
    end
  end
end
