module Privy
  module Models
    type ethereum_send_calls_rpc_input =
      {
        :caip2 => String,
        method_: Privy::Models::EthereumSendCallsRpcInput::method_,
        params: Privy::EthereumSendCallsRpcInputParams,
        address: String,
        chain_type: Privy::Models::EthereumSendCallsRpcInput::chain_type,
        experimental_data_suffix: String,
        sponsor: bool,
        wallet_id: String
      }

    class EthereumSendCallsRpcInput < Privy::Internal::Type::BaseModel
      attr_accessor caip2: String

      attr_accessor method_: Privy::Models::EthereumSendCallsRpcInput::method_

      attr_accessor params: Privy::EthereumSendCallsRpcInputParams

      attr_reader address: String?

      def address=: (String) -> String

      attr_reader chain_type: Privy::Models::EthereumSendCallsRpcInput::chain_type?

      def chain_type=: (
        Privy::Models::EthereumSendCallsRpcInput::chain_type
      ) -> Privy::Models::EthereumSendCallsRpcInput::chain_type

      attr_reader experimental_data_suffix: String?

      def experimental_data_suffix=: (String) -> String

      attr_reader sponsor: bool?

      def sponsor=: (bool) -> bool

      attr_reader wallet_id: String?

      def wallet_id=: (String) -> String

      def initialize: (
        caip2: String,
        method_: Privy::Models::EthereumSendCallsRpcInput::method_,
        params: Privy::EthereumSendCallsRpcInputParams,
        ?address: String,
        ?chain_type: Privy::Models::EthereumSendCallsRpcInput::chain_type,
        ?experimental_data_suffix: String,
        ?sponsor: bool,
        ?wallet_id: String
      ) -> void

      def to_hash: -> {
        :caip2 => String,
        method_: Privy::Models::EthereumSendCallsRpcInput::method_,
        params: Privy::EthereumSendCallsRpcInputParams,
        address: String,
        chain_type: Privy::Models::EthereumSendCallsRpcInput::chain_type,
        experimental_data_suffix: String,
        sponsor: bool,
        wallet_id: String
      }

      type method_ = :wallet_sendCalls

      module Method
        extend Privy::Internal::Type::Enum

        WALLET_SEND_CALLS: :wallet_sendCalls

        def self?.values: -> ::Array[Privy::Models::EthereumSendCallsRpcInput::method_]
      end

      type chain_type = :ethereum

      module ChainType
        extend Privy::Internal::Type::Enum

        ETHEREUM: :ethereum

        def self?.values: -> ::Array[Privy::Models::EthereumSendCallsRpcInput::chain_type]
      end
    end
  end
end
