module Privy
  module Models
    type ethereum_typed_data_message_condition =
      {
        field: String,
        field_source: Privy::Models::EthereumTypedDataMessageCondition::field_source,
        operator: Privy::Models::condition_operator,
        typed_data: Privy::EthereumTypedDataMessageCondition::TypedData,
        value: Privy::Models::condition_value
      }

    class EthereumTypedDataMessageCondition < Privy::Internal::Type::BaseModel
      attr_accessor field: String

      attr_accessor field_source: Privy::Models::EthereumTypedDataMessageCondition::field_source

      attr_accessor operator: Privy::Models::condition_operator

      attr_accessor typed_data: Privy::EthereumTypedDataMessageCondition::TypedData

      attr_accessor value: Privy::Models::condition_value

      def initialize: (
        field: String,
        field_source: Privy::Models::EthereumTypedDataMessageCondition::field_source,
        operator: Privy::Models::condition_operator,
        typed_data: Privy::EthereumTypedDataMessageCondition::TypedData,
        value: Privy::Models::condition_value
      ) -> void

      def to_hash: -> {
        field: String,
        field_source: Privy::Models::EthereumTypedDataMessageCondition::field_source,
        operator: Privy::Models::condition_operator,
        typed_data: Privy::EthereumTypedDataMessageCondition::TypedData,
        value: Privy::Models::condition_value
      }

      type field_source = :ethereum_typed_data_message

      module FieldSource
        extend Privy::Internal::Type::Enum

        ETHEREUM_TYPED_DATA_MESSAGE: :ethereum_typed_data_message

        def self?.values: -> ::Array[Privy::Models::EthereumTypedDataMessageCondition::field_source]
      end

      type typed_data =
        {
          primary_type: String,
          types: Privy::Models::typed_data_types_input_params
        }

      class TypedData < Privy::Internal::Type::BaseModel
        attr_accessor primary_type: String

        attr_accessor types: Privy::Models::typed_data_types_input_params

        def initialize: (
          primary_type: String,
          types: Privy::Models::typed_data_types_input_params
        ) -> void

        def to_hash: -> {
          primary_type: String,
          types: Privy::Models::typed_data_types_input_params
        }
      end
    end
  end
end
