module Privy
  module Models
    type evm_user_operation_wallet_action_step =
      {
        bundle_transaction_hash: String?,
        :caip2 => String,
        entrypoint_version: Privy::Models::EvmUserOperationWalletActionStep::entrypoint_version,
        status: Privy::Models::evm_wallet_action_step_status,
        type: Privy::Models::EvmUserOperationWalletActionStep::type_,
        user_operation_hash: String?,
        failure_reason: Privy::FailureReason,
        gas_credits_charged_usd: String
      }

    class EvmUserOperationWalletActionStep < Privy::Internal::Type::BaseModel
      attr_accessor bundle_transaction_hash: String?

      attr_accessor caip2: String

      attr_accessor entrypoint_version: Privy::Models::EvmUserOperationWalletActionStep::entrypoint_version

      attr_accessor status: Privy::Models::evm_wallet_action_step_status

      attr_accessor type: Privy::Models::EvmUserOperationWalletActionStep::type_

      attr_accessor user_operation_hash: String?

      attr_reader failure_reason: Privy::FailureReason?

      def failure_reason=: (Privy::FailureReason) -> Privy::FailureReason

      attr_reader gas_credits_charged_usd: String?

      def gas_credits_charged_usd=: (String) -> String

      def initialize: (
        bundle_transaction_hash: String?,
        caip2: String,
        entrypoint_version: Privy::Models::EvmUserOperationWalletActionStep::entrypoint_version,
        status: Privy::Models::evm_wallet_action_step_status,
        type: Privy::Models::EvmUserOperationWalletActionStep::type_,
        user_operation_hash: String?,
        ?failure_reason: Privy::FailureReason,
        ?gas_credits_charged_usd: String
      ) -> void

      def to_hash: -> {
        bundle_transaction_hash: String?,
        :caip2 => String,
        entrypoint_version: Privy::Models::EvmUserOperationWalletActionStep::entrypoint_version,
        status: Privy::Models::evm_wallet_action_step_status,
        type: Privy::Models::EvmUserOperationWalletActionStep::type_,
        user_operation_hash: String?,
        failure_reason: Privy::FailureReason,
        gas_credits_charged_usd: String
      }

      type entrypoint_version = :"0.6" | :"0.7" | :"0.8" | :"0.9"

      module EntrypointVersion
        extend Privy::Internal::Type::Enum

        ENTRYPOINT_VERSION_0_6: :"0.6"
        ENTRYPOINT_VERSION_0_7: :"0.7"
        ENTRYPOINT_VERSION_0_8: :"0.8"
        ENTRYPOINT_VERSION_0_9: :"0.9"

        def self?.values: -> ::Array[Privy::Models::EvmUserOperationWalletActionStep::entrypoint_version]
      end

      type type_ = :evm_user_operation

      module Type
        extend Privy::Internal::Type::Enum

        EVM_USER_OPERATION: :evm_user_operation

        def self?.values: -> ::Array[Privy::Models::EvmUserOperationWalletActionStep::type_]
      end
    end
  end
end
