module Privy
  module Models
    type evm_transaction_wallet_action_step =
      {
        :caip2 => String,
        status: Privy::Models::evm_wallet_action_step_status,
        transaction_hash: String?,
        type: Privy::Models::EvmTransactionWalletActionStep::type_,
        failure_reason: Privy::FailureReason
      }

    class EvmTransactionWalletActionStep < Privy::Internal::Type::BaseModel
      attr_accessor caip2: String

      attr_accessor status: Privy::Models::evm_wallet_action_step_status

      attr_accessor transaction_hash: String?

      attr_accessor type: Privy::Models::EvmTransactionWalletActionStep::type_

      attr_reader failure_reason: Privy::FailureReason?

      def failure_reason=: (Privy::FailureReason) -> Privy::FailureReason

      def initialize: (
        caip2: String,
        status: Privy::Models::evm_wallet_action_step_status,
        transaction_hash: String?,
        type: Privy::Models::EvmTransactionWalletActionStep::type_,
        ?failure_reason: Privy::FailureReason
      ) -> void

      def to_hash: -> {
        :caip2 => String,
        status: Privy::Models::evm_wallet_action_step_status,
        transaction_hash: String?,
        type: Privy::Models::EvmTransactionWalletActionStep::type_,
        failure_reason: Privy::FailureReason
      }

      type type_ = :evm_transaction

      module Type
        extend Privy::Internal::Type::Enum

        EVM_TRANSACTION: :evm_transaction

        def self?.values: -> ::Array[Privy::Models::EvmTransactionWalletActionStep::type_]
      end
    end
  end
end
