module Privy
  module Models
    type fiat_currency = :usd | :eur

    module FiatCurrency
      extend Privy::Internal::Type::Enum

      USD: :usd
      EUR: :eur

      def self?.values: -> ::Array[Privy::Models::fiat_currency]
    end
  end
end
