module Privy
  module Models
    type fiat_payment_rail = :sepa | :ach_push | :wire

    module FiatPaymentRail
      extend Privy::Internal::Type::Enum

      SEPA: :sepa
      ACH_PUSH: :ach_push
      WIRE: :wire

      def self?.values: -> ::Array[Privy::Models::fiat_payment_rail]
    end
  end
end
