module Privy
  module Models
    type gas_spend_currency = :usd

    module GasSpendCurrency
      extend Privy::Internal::Type::Enum

      USD: :usd

      def self?.values: -> ::Array[Privy::Models::gas_spend_currency]
    end
  end
end
