module Privy
  module Models
    type gas_sponsorship_configuration =
      {
        configured_networks: ::Array[String],
        require_app_secret: bool,
        sponsorship_enabled: bool
      }

    class GasSponsorshipConfiguration < Privy::Internal::Type::BaseModel
      attr_accessor configured_networks: ::Array[String]

      attr_accessor require_app_secret: bool

      attr_accessor sponsorship_enabled: bool

      def initialize: (
        configured_networks: ::Array[String],
        require_app_secret: bool,
        sponsorship_enabled: bool
      ) -> void

      def to_hash: -> {
        configured_networks: ::Array[String],
        require_app_secret: bool,
        sponsorship_enabled: bool
      }
    end
  end
end
