module Privy
  module Models
    type gas_sponsorship_configuration_input =
      {
        configured_networks: ::Array[String],
        require_app_secret: bool,
        sponsorship_enabled: bool
      }

    class GasSponsorshipConfigurationInput < Privy::Internal::Type::BaseModel
      attr_reader configured_networks: ::Array[String]?

      def configured_networks=: (::Array[String]) -> ::Array[String]

      attr_reader require_app_secret: bool?

      def require_app_secret=: (bool) -> bool

      attr_reader sponsorship_enabled: bool?

      def sponsorship_enabled=: (bool) -> bool

      def initialize: (
        ?configured_networks: ::Array[String],
        ?require_app_secret: bool,
        ?sponsorship_enabled: bool
      ) -> void

      def to_hash: -> {
        configured_networks: ::Array[String],
        require_app_secret: bool,
        sponsorship_enabled: bool
      }
    end
  end
end
