module Privy
  module Models
    type get_fiat_customer_request_input =
      { provider: Privy::Models::onramp_provider, kyc_redirect_url: String }

    class GetFiatCustomerRequestInput < Privy::Internal::Type::BaseModel
      attr_accessor provider: Privy::Models::onramp_provider

      attr_reader kyc_redirect_url: String?

      def kyc_redirect_url=: (String) -> String

      def initialize: (
        provider: Privy::Models::onramp_provider,
        ?kyc_redirect_url: String
      ) -> void

      def to_hash: -> {
        provider: Privy::Models::onramp_provider,
        kyc_redirect_url: String
      }
    end
  end
end
