module Privy
  module Models
    type get_fiat_onramp_url_response =
      Privy::FiatOnrampURLSessionResponse
      | Privy::FiatOnrampStripeSDKSessionResponse

    module GetFiatOnrampURLResponse
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::get_fiat_onramp_url_response]
    end
  end
end
