module Privy
  module Models
    type get_by_wallet_address_request_body = { address: String }

    class GetByWalletAddressRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor address: String

      def initialize: (address: String) -> void

      def to_hash: -> { address: String }
    end
  end
end
