module Privy
  module Models
    type get_fiat_onramp_url_response = { session_id: String, url: String }

    class GetFiatOnrampURLResponse < Privy::Internal::Type::BaseModel
      attr_accessor session_id: String

      attr_accessor url: String

      def initialize: (session_id: String, url: String) -> void

      def to_hash: -> { session_id: String, url: String }
    end
  end
end
