module Privy
  module Models
    type get_stripe_crypto_customer_input =
      { id: String, auth_intent_id: String }

    class GetStripeCryptoCustomerInput < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor auth_intent_id: String

      def initialize: (id: String, auth_intent_id: String) -> void

      def to_hash: -> { id: String, auth_intent_id: String }
    end
  end
end
