module Privy
  module Models
    type intent_update_wallet_params =
      { wallet_id: String, privy_request_expiry: String }
      & Privy::Internal::Type::request_parameters

    class IntentUpdateWalletParams < Privy::Models::WalletUpdateRequestBody
      extend Privy::Internal::Type::RequestParameters::Converter
      include Privy::Internal::Type::RequestParameters

      def wallet_id: -> String

      def wallet_id=: (String _) -> String

      def privy_request_expiry: -> String?

      def privy_request_expiry=: (String _) -> String

      def initialize: (
        wallet_id: String,
        ?privy_request_expiry: String,
        ?request_options: Privy::request_opts
      ) -> void

      def to_hash: -> {
        wallet_id: String,
        privy_request_expiry: String,
        request_options: Privy::RequestOptions
      }
    end
  end
end
