module Privy
  module Models
    type intent_authorization_key_quorum_member =
      Privy::IntentAuthorizationUserMember | Privy::IntentAuthorizationKeyMember

    module IntentAuthorizationKeyQuorumMember
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::intent_authorization_key_quorum_member]
    end
  end
end
