module Privy
  module Models
    type intent_authorization_member =
      Privy::IntentAuthorizationUserMember
      | Privy::IntentAuthorizationKeyMember
      | Privy::IntentAuthorizationKeyQuorum

    module IntentAuthorizationMember
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::intent_authorization_member]
    end
  end
end
