module Privy
  module Models
    type key_quorum_update_params =
      {
        key_quorum_id: String,
        privy_authorization_signature: String,
        privy_request_expiry: String
      }
      & Privy::Internal::Type::request_parameters

    class KeyQuorumUpdateParams < Privy::Models::KeyQuorumUpdateRequestBody
      extend Privy::Internal::Type::RequestParameters::Converter
      include Privy::Internal::Type::RequestParameters

      def key_quorum_id: -> String

      def key_quorum_id=: (String _) -> String

      def privy_authorization_signature: -> String?

      def privy_authorization_signature=: (String _) -> String

      def privy_request_expiry: -> String?

      def privy_request_expiry=: (String _) -> String

      def initialize: (
        key_quorum_id: String,
        ?privy_authorization_signature: String,
        ?privy_request_expiry: String,
        ?request_options: Privy::request_opts
      ) -> void

      def to_hash: -> {
        key_quorum_id: String,
        privy_authorization_signature: String,
        privy_request_expiry: String,
        request_options: Privy::RequestOptions
      }
    end
  end
end
