module Privy
  module Models
    type key_quorum_intent_response =
      {
        intent_type: Privy::Models::KeyQuorumIntentResponse::intent_type,
        request_details: Privy::KeyQuorumIntentResponse::RequestDetails,
        action_result: Privy::BaseActionResult,
        current_resource_data: Privy::KeyQuorum
      }

    class KeyQuorumIntentResponse < Privy::Models::BaseIntentResponse
      def intent_type: -> Privy::Models::KeyQuorumIntentResponse::intent_type

      def intent_type=: (
        Privy::Models::KeyQuorumIntentResponse::intent_type _
      ) -> Privy::Models::KeyQuorumIntentResponse::intent_type

      def request_details: -> Privy::KeyQuorumIntentResponse::RequestDetails

      def request_details=: (
        Privy::KeyQuorumIntentResponse::RequestDetails _
      ) -> Privy::KeyQuorumIntentResponse::RequestDetails

      def action_result: -> Privy::BaseActionResult?

      def action_result=: (Privy::BaseActionResult _) -> Privy::BaseActionResult

      def current_resource_data: -> Privy::KeyQuorum?

      def current_resource_data=: (Privy::KeyQuorum _) -> Privy::KeyQuorum

      def initialize: (
        intent_type: Privy::Models::KeyQuorumIntentResponse::intent_type,
        request_details: Privy::KeyQuorumIntentResponse::RequestDetails,
        ?action_result: Privy::BaseActionResult,
        ?current_resource_data: Privy::KeyQuorum
      ) -> void

      def to_hash: -> {
        intent_type: Privy::Models::KeyQuorumIntentResponse::intent_type,
        request_details: Privy::KeyQuorumIntentResponse::RequestDetails,
        action_result: Privy::BaseActionResult,
        current_resource_data: Privy::KeyQuorum
      }

      type intent_type = :KEY_QUORUM

      module IntentType
        extend Privy::Internal::Type::Enum

        KEY_QUORUM: :KEY_QUORUM

        def self?.values: -> ::Array[Privy::Models::KeyQuorumIntentResponse::intent_type]
      end

      type request_details =
        {
          body: Privy::KeyQuorumUpdateRequestBody,
          method_: Privy::Models::KeyQuorumIntentResponse::RequestDetails::method_,
          url: String
        }

      class RequestDetails < Privy::Internal::Type::BaseModel
        attr_accessor body: Privy::KeyQuorumUpdateRequestBody

        attr_accessor method_: Privy::Models::KeyQuorumIntentResponse::RequestDetails::method_

        attr_accessor url: String

        def initialize: (
          body: Privy::KeyQuorumUpdateRequestBody,
          method_: Privy::Models::KeyQuorumIntentResponse::RequestDetails::method_,
          url: String
        ) -> void

        def to_hash: -> {
          body: Privy::KeyQuorumUpdateRequestBody,
          method_: Privy::Models::KeyQuorumIntentResponse::RequestDetails::method_,
          url: String
        }

        type method_ = :PATCH

        module Method
          extend Privy::Internal::Type::Enum

          PATCH: :PATCH

          def self?.values: -> ::Array[Privy::Models::KeyQuorumIntentResponse::RequestDetails::method_]
        end
      end
    end
  end
end
