module Privy
  module Models
    type key_quorum =
      {
        id: String,
        authorization_keys: ::Array[Privy::AuthorizationKey],
        authorization_threshold: Float?,
        display_name: String?,
        user_ids: ::Array[String]?,
        key_quorum_ids: ::Array[String]
      }

    class KeyQuorum < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor authorization_keys: ::Array[Privy::AuthorizationKey]

      attr_accessor authorization_threshold: Float?

      attr_accessor display_name: String?

      attr_accessor user_ids: ::Array[String]?

      attr_reader key_quorum_ids: ::Array[String]?

      def key_quorum_ids=: (::Array[String]) -> ::Array[String]

      def initialize: (
        id: String,
        authorization_keys: ::Array[Privy::AuthorizationKey],
        authorization_threshold: Float?,
        display_name: String?,
        user_ids: ::Array[String]?,
        ?key_quorum_ids: ::Array[String]
      ) -> void

      def to_hash: -> {
        id: String,
        authorization_keys: ::Array[Privy::AuthorizationKey],
        authorization_threshold: Float?,
        display_name: String?,
        user_ids: ::Array[String]?,
        key_quorum_ids: ::Array[String]
      }
    end
  end
end
