module Privy
  module Models
    type key_quorum_create_params =
      {  } & Privy::Internal::Type::request_parameters

    class KeyQuorumCreateParams < Privy::Models::KeyQuorumCreateRequestBody
      extend Privy::Internal::Type::RequestParameters::Converter
      include Privy::Internal::Type::RequestParameters

      def initialize: (?request_options: Privy::request_opts) -> void

      def to_hash: -> { request_options: Privy::RequestOptions }
    end
  end
end
