module Privy
  module Models
    type kraken_embed_get_portfolio_summary_response =
      { data: Privy::KrakenEmbedGetPortfolioSummaryResponse::Data }

    class KrakenEmbedGetPortfolioSummaryResponse < Privy::Internal::Type::BaseModel
      attr_accessor data: Privy::KrakenEmbedGetPortfolioSummaryResponse::Data

      def initialize: (
        data: Privy::KrakenEmbedGetPortfolioSummaryResponse::Data
      ) -> void

      def to_hash: -> {
        data: Privy::KrakenEmbedGetPortfolioSummaryResponse::Data
      }

      type data =
        {
          result: Privy::KrakenEmbedGetPortfolioSummaryResponse::Data::Result?,
          error: ::Array[String],
          errors: ::Array[String]
        }

      class Data < Privy::Internal::Type::BaseModel
        attr_accessor result: Privy::KrakenEmbedGetPortfolioSummaryResponse::Data::Result?

        attr_reader error: ::Array[String]?

        def error=: (::Array[String]) -> ::Array[String]

        attr_reader errors: ::Array[String]?

        def errors=: (::Array[String]) -> ::Array[String]

        def initialize: (
          result: Privy::KrakenEmbedGetPortfolioSummaryResponse::Data::Result?,
          ?error: ::Array[String],
          ?errors: ::Array[String]
        ) -> void

        def to_hash: -> {
          result: Privy::KrakenEmbedGetPortfolioSummaryResponse::Data::Result?,
          error: ::Array[String],
          errors: ::Array[String]
        }

        type result =
          {
            available_balance: String,
            currency: String,
            open_orders: String,
            portfolio_value: String,
            timestamp: Time,
            withheld_value: String,
            cost_basis: String?,
            current_day_pnl: Privy::KrakenEmbedCurrentDayPnl?,
            lots_upnl: String?
          }

        class Result < Privy::Internal::Type::BaseModel
          attr_accessor available_balance: String

          attr_accessor currency: String

          attr_accessor open_orders: String

          attr_accessor portfolio_value: String

          attr_accessor timestamp: Time

          attr_accessor withheld_value: String

          attr_accessor cost_basis: String?

          attr_accessor current_day_pnl: Privy::KrakenEmbedCurrentDayPnl?

          attr_accessor lots_upnl: String?

          def initialize: (
            available_balance: String,
            currency: String,
            open_orders: String,
            portfolio_value: String,
            timestamp: Time,
            withheld_value: String,
            ?cost_basis: String?,
            ?current_day_pnl: Privy::KrakenEmbedCurrentDayPnl?,
            ?lots_upnl: String?
          ) -> void

          def to_hash: -> {
            available_balance: String,
            currency: String,
            open_orders: String,
            portfolio_value: String,
            timestamp: Time,
            withheld_value: String,
            cost_basis: String?,
            current_day_pnl: Privy::KrakenEmbedCurrentDayPnl?,
            lots_upnl: String?
          }
        end
      end
    end
  end
end
