module Privy
  module Models
    type kraken_embed_get_earn_summary_kraken_response =
      {
        result: Privy::KrakenEmbedGetEarnSummaryKrakenResponse::Result,
        error: ::Array[top],
        errors: ::Array[top]
      }

    class KrakenEmbedGetEarnSummaryKrakenResponse < Privy::Internal::Type::BaseModel
      attr_accessor result: Privy::KrakenEmbedGetEarnSummaryKrakenResponse::Result

      attr_reader error: ::Array[top]?

      def error=: (::Array[top]) -> ::Array[top]

      attr_reader errors: ::Array[top]?

      def errors=: (::Array[top]) -> ::Array[top]

      def initialize: (
        result: Privy::KrakenEmbedGetEarnSummaryKrakenResponse::Result,
        ?error: ::Array[top],
        ?errors: ::Array[top]
      ) -> void

      def to_hash: -> {
        result: Privy::KrakenEmbedGetEarnSummaryKrakenResponse::Result,
        error: ::Array[top],
        errors: ::Array[top]
      }

      type result = {  }

      class Result < Privy::Models::KrakenEmbedGetEarnSummaryResult
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
