module Privy
  module Models
    type kraken_embed_custom_order_action =
      {
        amount: Privy::KrakenEmbedCustomOrderAmount,
        fee_bps: String,
        quote: Privy::KrakenEmbedCustomOrderQuoteAsset,
        spread_bps: String,
        type: Privy::Models::kraken_embed_quote_type
      }

    class KrakenEmbedCustomOrderAction < Privy::Internal::Type::BaseModel
      attr_accessor amount: Privy::KrakenEmbedCustomOrderAmount

      attr_accessor fee_bps: String

      attr_accessor quote: Privy::KrakenEmbedCustomOrderQuoteAsset

      attr_accessor spread_bps: String

      attr_accessor type: Privy::Models::kraken_embed_quote_type

      def initialize: (
        amount: Privy::KrakenEmbedCustomOrderAmount,
        fee_bps: String,
        quote: Privy::KrakenEmbedCustomOrderQuoteAsset,
        spread_bps: String,
        type: Privy::Models::kraken_embed_quote_type
      ) -> void

      def to_hash: -> {
        amount: Privy::KrakenEmbedCustomOrderAmount,
        fee_bps: String,
        quote: Privy::KrakenEmbedCustomOrderQuoteAsset,
        spread_bps: String,
        type: Privy::Models::kraken_embed_quote_type
      }
    end
  end
end
