module Privy
  module Models
    type kraken_embed_start_identity_metadata =
      {
        document_number: String?,
        document_type: Privy::Models::kraken_embed_identity_document_type?,
        expiration_date: Date?,
        identity: Privy::KrakenEmbedStartIdentityInfo?,
        issuing_country: Privy::Models::kraken_embed_country_code?,
        nationality: Privy::Models::kraken_embed_country_code?
      }

    class KrakenEmbedStartIdentityMetadata < Privy::Internal::Type::BaseModel
      attr_accessor document_number: String?

      attr_accessor document_type: Privy::Models::kraken_embed_identity_document_type?

      attr_accessor expiration_date: Date?

      attr_accessor identity: Privy::KrakenEmbedStartIdentityInfo?

      attr_accessor issuing_country: Privy::Models::kraken_embed_country_code?

      attr_accessor nationality: Privy::Models::kraken_embed_country_code?

      def initialize: (
        ?document_number: String?,
        ?document_type: Privy::Models::kraken_embed_identity_document_type?,
        ?expiration_date: Date?,
        ?identity: Privy::KrakenEmbedStartIdentityInfo?,
        ?issuing_country: Privy::Models::kraken_embed_country_code?,
        ?nationality: Privy::Models::kraken_embed_country_code?
      ) -> void

      def to_hash: -> {
        document_number: String?,
        document_type: Privy::Models::kraken_embed_identity_document_type?,
        expiration_date: Date?,
        identity: Privy::KrakenEmbedStartIdentityInfo?,
        issuing_country: Privy::Models::kraken_embed_country_code?,
        nationality: Privy::Models::kraken_embed_country_code?
      }
    end
  end
end
