module Privy
  module Models
    type kraken_embed_start_identity_verification_url_input =
      {
        front_url: String,
        type: Privy::Models::KrakenEmbedStartIdentityVerificationURLInput::type_,
        back_url: String?,
        debug: Privy::KrakenEmbedStartVerificationDebug?,
        metadata: Privy::KrakenEmbedStartIdentityMetadata?
      }

    class KrakenEmbedStartIdentityVerificationURLInput < Privy::Internal::Type::BaseModel
      attr_accessor front_url: String

      attr_accessor type: Privy::Models::KrakenEmbedStartIdentityVerificationURLInput::type_

      attr_accessor back_url: String?

      attr_accessor debug: Privy::KrakenEmbedStartVerificationDebug?

      attr_accessor metadata: Privy::KrakenEmbedStartIdentityMetadata?

      def initialize: (
        front_url: String,
        type: Privy::Models::KrakenEmbedStartIdentityVerificationURLInput::type_,
        ?back_url: String?,
        ?debug: Privy::KrakenEmbedStartVerificationDebug?,
        ?metadata: Privy::KrakenEmbedStartIdentityMetadata?
      ) -> void

      def to_hash: -> {
        front_url: String,
        type: Privy::Models::KrakenEmbedStartIdentityVerificationURLInput::type_,
        back_url: String?,
        debug: Privy::KrakenEmbedStartVerificationDebug?,
        metadata: Privy::KrakenEmbedStartIdentityMetadata?
      }

      type type_ = :proof_of_identity

      module Type
        extend Privy::Internal::Type::Enum

        PROOF_OF_IDENTITY: :proof_of_identity

        def self?.values: -> ::Array[Privy::Models::KrakenEmbedStartIdentityVerificationURLInput::type_]
      end
    end
  end
end
