module Privy
  module Models
    type kraken_embed_get_portfolio_transactions_query_params_schema =
      {
        assets: ::Array[String],
        cursor: String,
        from_time: Time,
        ids: ::Array[String],
        page_size: Integer,
        quote: String,
        ref_ids: ::Array[Privy::KrakenEmbedPortfolioTransactionRefID],
        sorting: Privy::Models::kraken_embed_sorting_order,
        statuses: ::Array[Privy::Models::kraken_embed_transaction_status],
        types: ::Array[Privy::Models::kraken_embed_transaction_type],
        until_time: Time
      }

    class KrakenEmbedGetPortfolioTransactionsQueryParamsSchema < Privy::Internal::Type::BaseModel
      attr_reader assets: ::Array[String]?

      def assets=: (::Array[String]) -> ::Array[String]

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader from_time: Time?

      def from_time=: (Time) -> Time

      attr_reader ids: ::Array[String]?

      def ids=: (::Array[String]) -> ::Array[String]

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader quote: String?

      def quote=: (String) -> String

      attr_reader ref_ids: ::Array[Privy::KrakenEmbedPortfolioTransactionRefID]?

      def ref_ids=: (
        ::Array[Privy::KrakenEmbedPortfolioTransactionRefID]
      ) -> ::Array[Privy::KrakenEmbedPortfolioTransactionRefID]

      attr_reader sorting: Privy::Models::kraken_embed_sorting_order?

      def sorting=: (
        Privy::Models::kraken_embed_sorting_order
      ) -> Privy::Models::kraken_embed_sorting_order

      attr_reader statuses: ::Array[Privy::Models::kraken_embed_transaction_status]?

      def statuses=: (
        ::Array[Privy::Models::kraken_embed_transaction_status]
      ) -> ::Array[Privy::Models::kraken_embed_transaction_status]

      attr_reader types: ::Array[Privy::Models::kraken_embed_transaction_type]?

      def types=: (
        ::Array[Privy::Models::kraken_embed_transaction_type]
      ) -> ::Array[Privy::Models::kraken_embed_transaction_type]

      attr_reader until_time: Time?

      def until_time=: (Time) -> Time

      def initialize: (
        ?assets: ::Array[String],
        ?cursor: String,
        ?from_time: Time,
        ?ids: ::Array[String],
        ?page_size: Integer,
        ?quote: String,
        ?ref_ids: ::Array[Privy::KrakenEmbedPortfolioTransactionRefID],
        ?sorting: Privy::Models::kraken_embed_sorting_order,
        ?statuses: ::Array[Privy::Models::kraken_embed_transaction_status],
        ?types: ::Array[Privy::Models::kraken_embed_transaction_type],
        ?until_time: Time
      ) -> void

      def to_hash: -> {
        assets: ::Array[String],
        cursor: String,
        from_time: Time,
        ids: ::Array[String],
        page_size: Integer,
        quote: String,
        ref_ids: ::Array[Privy::KrakenEmbedPortfolioTransactionRefID],
        sorting: Privy::Models::kraken_embed_sorting_order,
        statuses: ::Array[Privy::Models::kraken_embed_transaction_status],
        types: ::Array[Privy::Models::kraken_embed_transaction_type],
        until_time: Time
      }
    end
  end
end
