module Privy
  module Models
    type kraken_embed_start_identity_info =
      { date_of_birth: Date?, full_name: Privy::KrakenEmbedFullName? }

    class KrakenEmbedStartIdentityInfo < Privy::Internal::Type::BaseModel
      attr_accessor date_of_birth: Date?

      attr_accessor full_name: Privy::KrakenEmbedFullName?

      def initialize: (
        ?date_of_birth: Date?,
        ?full_name: Privy::KrakenEmbedFullName?
      ) -> void

      def to_hash: -> {
        date_of_birth: Date?,
        full_name: Privy::KrakenEmbedFullName?
      }
    end
  end
end
