module Privy
  module Models
    type kraken_embed_start_verification_url_response =
      { result: Privy::KrakenEmbedStartVerificationURLResult? }

    class KrakenEmbedStartVerificationURLResponse < Privy::Internal::Type::BaseModel
      attr_accessor result: Privy::KrakenEmbedStartVerificationURLResult?

      def initialize: (
        result: Privy::KrakenEmbedStartVerificationURLResult?
      ) -> void

      def to_hash: -> { result: Privy::KrakenEmbedStartVerificationURLResult? }
    end
  end
end
