module Privy
  module Models
    type kraken_embed_custom_order_occurrence_trigger =
      { type: Privy::Models::kraken_embed_custom_order_occurrence_trigger_type }

    class KrakenEmbedCustomOrderOccurrenceTrigger < Privy::Internal::Type::BaseModel
      attr_accessor type: Privy::Models::kraken_embed_custom_order_occurrence_trigger_type

      def initialize: (
        type: Privy::Models::kraken_embed_custom_order_occurrence_trigger_type
      ) -> void

      def to_hash: -> {
        type: Privy::Models::kraken_embed_custom_order_occurrence_trigger_type
      }
    end
  end
end
