module Privy
  module Models
    type kraken_embed_start_address_metadata =
      {
        address: Privy::KrakenEmbedResidence?,
        document_number: String?,
        document_type: Privy::Models::kraken_embed_residence_document_type?,
        expiration_date: Date?
      }

    class KrakenEmbedStartAddressMetadata < Privy::Internal::Type::BaseModel
      attr_accessor address: Privy::KrakenEmbedResidence?

      attr_accessor document_number: String?

      attr_accessor document_type: Privy::Models::kraken_embed_residence_document_type?

      attr_accessor expiration_date: Date?

      def initialize: (
        ?address: Privy::KrakenEmbedResidence?,
        ?document_number: String?,
        ?document_type: Privy::Models::kraken_embed_residence_document_type?,
        ?expiration_date: Date?
      ) -> void

      def to_hash: -> {
        address: Privy::KrakenEmbedResidence?,
        document_number: String?,
        document_type: Privy::Models::kraken_embed_residence_document_type?,
        expiration_date: Date?
      }
    end
  end
end
