module Privy
  module Models
    type kraken_embed_get_portfolio_summary_response =
      { data: Privy::KrakenEmbedGetPortfolioSummaryResult }

    class KrakenEmbedGetPortfolioSummaryResponse < Privy::Internal::Type::BaseModel
      attr_accessor data: Privy::KrakenEmbedGetPortfolioSummaryResult

      def initialize: (
        data: Privy::KrakenEmbedGetPortfolioSummaryResult
      ) -> void

      def to_hash: -> { data: Privy::KrakenEmbedGetPortfolioSummaryResult }
    end
  end
end
