module Privy
  module Models
    type kraken_embed_get_portfolio_summary_query_params =
      {
        include_current_day_pnl: Privy::Models::kraken_embed_include_current_day_pnl_query_param,
        quote: String
      }

    class KrakenEmbedGetPortfolioSummaryQueryParams < Privy::Internal::Type::BaseModel
      attr_reader include_current_day_pnl: Privy::Models::kraken_embed_include_current_day_pnl_query_param?

      def include_current_day_pnl=: (
        Privy::Models::kraken_embed_include_current_day_pnl_query_param
      ) -> Privy::Models::kraken_embed_include_current_day_pnl_query_param

      attr_reader quote: String?

      def quote=: (String) -> String

      def initialize: (
        ?include_current_day_pnl: Privy::Models::kraken_embed_include_current_day_pnl_query_param,
        ?quote: String
      ) -> void

      def to_hash: -> {
        include_current_day_pnl: Privy::Models::kraken_embed_include_current_day_pnl_query_param,
        quote: String
      }
    end
  end
end
