module Privy
  module Models
    type kraken_embed_upcoming_reward =
      {
        accumulated_amount: Privy::KrakenEmbedEarnAmount,
        asset: String,
        date: Time,
        estimated_pending_amount: Privy::KrakenEmbedEarnAmount?
      }

    class KrakenEmbedUpcomingReward < Privy::Internal::Type::BaseModel
      attr_accessor accumulated_amount: Privy::KrakenEmbedEarnAmount

      attr_accessor asset: String

      attr_accessor date: Time

      attr_accessor estimated_pending_amount: Privy::KrakenEmbedEarnAmount?

      def initialize: (
        accumulated_amount: Privy::KrakenEmbedEarnAmount,
        asset: String,
        date: Time,
        estimated_pending_amount: Privy::KrakenEmbedEarnAmount?
      ) -> void

      def to_hash: -> {
        accumulated_amount: Privy::KrakenEmbedEarnAmount,
        asset: String,
        date: Time,
        estimated_pending_amount: Privy::KrakenEmbedEarnAmount?
      }
    end
  end
end
