module Privy
  module Models
    type kraken_embed_toggle_auto_earn_response =
      { data: Privy::KrakenEmbedToggleAutoEarnKrakenResponse }

    class KrakenEmbedToggleAutoEarnResponse < Privy::Internal::Type::BaseModel
      attr_accessor data: Privy::KrakenEmbedToggleAutoEarnKrakenResponse

      def initialize: (
        data: Privy::KrakenEmbedToggleAutoEarnKrakenResponse
      ) -> void

      def to_hash: -> { data: Privy::KrakenEmbedToggleAutoEarnKrakenResponse }
    end
  end
end
