module Privy
  module Models
    type kraken_embed_get_earn_summary_query_params = { currency: String }

    class KrakenEmbedGetEarnSummaryQueryParams < Privy::Internal::Type::BaseModel
      attr_accessor currency: String

      def initialize: (currency: String) -> void

      def to_hash: -> { currency: String }
    end
  end
end
