module Privy
  module Models
    type kraken_embed_list_custom_orders_query_params =
      {
        user_id: String,
        cursor: String,
        statuses: Privy::Models::KrakenEmbedListCustomOrdersQueryParams::statuses
      }

    class KrakenEmbedListCustomOrdersQueryParams < Privy::Internal::Type::BaseModel
      attr_accessor user_id: String

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader statuses: Privy::Models::KrakenEmbedListCustomOrdersQueryParams::statuses?

      def statuses=: (
        Privy::Models::KrakenEmbedListCustomOrdersQueryParams::statuses
      ) -> Privy::Models::KrakenEmbedListCustomOrdersQueryParams::statuses

      def initialize: (
        user_id: String,
        ?cursor: String,
        ?statuses: Privy::Models::KrakenEmbedListCustomOrdersQueryParams::statuses
      ) -> void

      def to_hash: -> {
        user_id: String,
        cursor: String,
        statuses: Privy::Models::KrakenEmbedListCustomOrdersQueryParams::statuses
      }

      type statuses =
        ::Array[Privy::Models::kraken_embed_custom_order_status_value] | String

      module Statuses
        extend Privy::Internal::Type::Union

        def self?.variants: -> ::Array[Privy::Models::KrakenEmbedListCustomOrdersQueryParams::statuses]

        KrakenEmbedCustomOrderStatusValueArray: Privy::Internal::Type::Converter
      end
    end
  end
end
