module Privy
  module Models
    type kraken_embed_get_custom_order_history_response =
      {
        result: Privy::KrakenEmbedGetCustomOrderHistoryResult?,
        error: ::Array[top],
        errors: ::Array[top]
      }

    class KrakenEmbedGetCustomOrderHistoryResponse < Privy::Internal::Type::BaseModel
      attr_accessor result: Privy::KrakenEmbedGetCustomOrderHistoryResult?

      attr_reader error: ::Array[top]?

      def error=: (::Array[top]) -> ::Array[top]

      attr_reader errors: ::Array[top]?

      def errors=: (::Array[top]) -> ::Array[top]

      def initialize: (
        result: Privy::KrakenEmbedGetCustomOrderHistoryResult?,
        ?error: ::Array[top],
        ?errors: ::Array[top]
      ) -> void

      def to_hash: -> {
        result: Privy::KrakenEmbedGetCustomOrderHistoryResult?,
        error: ::Array[top],
        errors: ::Array[top]
      }
    end
  end
end
