module Privy
  module Models
    type kraken_embed_custom_order_occurrence =
      {
        id: String,
        created_at: Time,
        status: Privy::Models::KrakenEmbedCustomOrderOccurrence::status,
        trigger: Privy::KrakenEmbedCustomOrderOccurrenceTrigger,
        updated_at: Time,
        executed_action: Privy::KrakenEmbedCustomOrderOccurrenceExecutedAction?,
        failure_reason: String,
        skip_reason: String
      }

    class KrakenEmbedCustomOrderOccurrence < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor status: Privy::Models::KrakenEmbedCustomOrderOccurrence::status

      attr_accessor trigger: Privy::KrakenEmbedCustomOrderOccurrenceTrigger

      attr_accessor updated_at: Time

      attr_accessor executed_action: Privy::KrakenEmbedCustomOrderOccurrenceExecutedAction?

      attr_reader failure_reason: String?

      def failure_reason=: (String) -> String

      attr_reader skip_reason: String?

      def skip_reason=: (String) -> String

      def initialize: (
        id: String,
        created_at: Time,
        status: Privy::Models::KrakenEmbedCustomOrderOccurrence::status,
        trigger: Privy::KrakenEmbedCustomOrderOccurrenceTrigger,
        updated_at: Time,
        ?executed_action: Privy::KrakenEmbedCustomOrderOccurrenceExecutedAction?,
        ?failure_reason: String,
        ?skip_reason: String
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        status: Privy::Models::KrakenEmbedCustomOrderOccurrence::status,
        trigger: Privy::KrakenEmbedCustomOrderOccurrenceTrigger,
        updated_at: Time,
        executed_action: Privy::KrakenEmbedCustomOrderOccurrenceExecutedAction?,
        failure_reason: String,
        skip_reason: String
      }

      type status = :success | :failure | :skipped

      module Status
        extend Privy::Internal::Type::Enum

        SUCCESS: :success
        FAILURE: :failure
        SKIPPED: :skipped

        def self?.values: -> ::Array[Privy::Models::KrakenEmbedCustomOrderOccurrence::status]
      end
    end
  end
end
