module Privy
  module Models
    type kraken_embed_get_portfolio_transactions_query_params_schema =
      {
        assets: ::Array[String],
        cursor: String,
        from_time: Time,
        ids: ::Array[String],
        page_size: Integer,
        quote: String,
        ref_ids: ::Array[Privy::KrakenEmbedPortfolioTransactionRefID],
        sorting: Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::sorting,
        statuses: ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::status],
        types: ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::type_],
        until_time: Time
      }

    class KrakenEmbedGetPortfolioTransactionsQueryParamsSchema < Privy::Internal::Type::BaseModel
      attr_reader assets: ::Array[String]?

      def assets=: (::Array[String]) -> ::Array[String]

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader from_time: Time?

      def from_time=: (Time) -> Time

      attr_reader ids: ::Array[String]?

      def ids=: (::Array[String]) -> ::Array[String]

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader quote: String?

      def quote=: (String) -> String

      attr_reader ref_ids: ::Array[Privy::KrakenEmbedPortfolioTransactionRefID]?

      def ref_ids=: (
        ::Array[Privy::KrakenEmbedPortfolioTransactionRefID]
      ) -> ::Array[Privy::KrakenEmbedPortfolioTransactionRefID]

      attr_reader sorting: Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::sorting?

      def sorting=: (
        Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::sorting
      ) -> Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::sorting

      attr_reader statuses: ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::status]?

      def statuses=: (
        ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::status]
      ) -> ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::status]

      attr_reader types: ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::type_]?

      def types=: (
        ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::type_]
      ) -> ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::type_]

      attr_reader until_time: Time?

      def until_time=: (Time) -> Time

      def initialize: (
        ?assets: ::Array[String],
        ?cursor: String,
        ?from_time: Time,
        ?ids: ::Array[String],
        ?page_size: Integer,
        ?quote: String,
        ?ref_ids: ::Array[Privy::KrakenEmbedPortfolioTransactionRefID],
        ?sorting: Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::sorting,
        ?statuses: ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::status],
        ?types: ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::type_],
        ?until_time: Time
      ) -> void

      def to_hash: -> {
        assets: ::Array[String],
        cursor: String,
        from_time: Time,
        ids: ::Array[String],
        page_size: Integer,
        quote: String,
        ref_ids: ::Array[Privy::KrakenEmbedPortfolioTransactionRefID],
        sorting: Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::sorting,
        statuses: ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::status],
        types: ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::type_],
        until_time: Time
      }

      type sorting = :descending | :ascending

      module Sorting
        extend Privy::Internal::Type::Enum

        DESCENDING: :descending
        ASCENDING: :ascending

        def self?.values: -> ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::sorting]
      end

      type status = :unspecified | :in_progress | :successful | :failed

      module Status
        extend Privy::Internal::Type::Enum

        UNSPECIFIED: :unspecified
        IN_PROGRESS: :in_progress
        SUCCESSFUL: :successful
        FAILED: :failed

        def self?.values: -> ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::status]
      end

      type type_ = :simple_order | :simple_order_failed | :earn_reward

      module Type
        extend Privy::Internal::Type::Enum

        SIMPLE_ORDER: :simple_order
        SIMPLE_ORDER_FAILED: :simple_order_failed
        EARN_REWARD: :earn_reward

        def self?.values: -> ::Array[Privy::Models::KrakenEmbedGetPortfolioTransactionsQueryParamsSchema::type_]
      end
    end
  end
end
