module Privy
  module Models
    type kraken_embed_start_address_verification_url_input =
      {
        document_url: String,
        type: Privy::Models::KrakenEmbedStartAddressVerificationURLInput::type_,
        debug: Privy::KrakenEmbedStartVerificationDebug?,
        metadata: Privy::KrakenEmbedStartAddressMetadata?
      }

    class KrakenEmbedStartAddressVerificationURLInput < Privy::Internal::Type::BaseModel
      attr_accessor document_url: String

      attr_accessor type: Privy::Models::KrakenEmbedStartAddressVerificationURLInput::type_

      attr_accessor debug: Privy::KrakenEmbedStartVerificationDebug?

      attr_accessor metadata: Privy::KrakenEmbedStartAddressMetadata?

      def initialize: (
        document_url: String,
        type: Privy::Models::KrakenEmbedStartAddressVerificationURLInput::type_,
        ?debug: Privy::KrakenEmbedStartVerificationDebug?,
        ?metadata: Privy::KrakenEmbedStartAddressMetadata?
      ) -> void

      def to_hash: -> {
        document_url: String,
        type: Privy::Models::KrakenEmbedStartAddressVerificationURLInput::type_,
        debug: Privy::KrakenEmbedStartVerificationDebug?,
        metadata: Privy::KrakenEmbedStartAddressMetadata?
      }

      type type_ = :proof_of_address

      module Type
        extend Privy::Internal::Type::Enum

        PROOF_OF_ADDRESS: :proof_of_address

        def self?.values: -> ::Array[Privy::Models::KrakenEmbedStartAddressVerificationURLInput::type_]
      end
    end
  end
end
