module Privy
  module Models
    type kraken_embed_earn_asset =
      {
        apr_estimate: Privy::KrakenEmbedEarnAprEstimate?,
        user_allocation: Privy::KrakenEmbedEarnUserAllocation?
      }

    class KrakenEmbedEarnAsset < Privy::Internal::Type::BaseModel
      attr_accessor apr_estimate: Privy::KrakenEmbedEarnAprEstimate?

      attr_accessor user_allocation: Privy::KrakenEmbedEarnUserAllocation?

      def initialize: (
        apr_estimate: Privy::KrakenEmbedEarnAprEstimate?,
        ?user_allocation: Privy::KrakenEmbedEarnUserAllocation?
      ) -> void

      def to_hash: -> {
        apr_estimate: Privy::KrakenEmbedEarnAprEstimate?,
        user_allocation: Privy::KrakenEmbedEarnUserAllocation?
      }
    end
  end
end
