module Privy
  module Models
    type kraken_embed_create_custom_order_response =
      {
        result: Privy::KrakenEmbedCreateCustomOrderResult?,
        error: ::Array[top],
        errors: ::Array[top]
      }

    class KrakenEmbedCreateCustomOrderResponse < Privy::Internal::Type::BaseModel
      attr_accessor result: Privy::KrakenEmbedCreateCustomOrderResult?

      attr_reader error: ::Array[top]?

      def error=: (::Array[top]) -> ::Array[top]

      attr_reader errors: ::Array[top]?

      def errors=: (::Array[top]) -> ::Array[top]

      def initialize: (
        result: Privy::KrakenEmbedCreateCustomOrderResult?,
        ?error: ::Array[top],
        ?errors: ::Array[top]
      ) -> void

      def to_hash: -> {
        result: Privy::KrakenEmbedCreateCustomOrderResult?,
        error: ::Array[top],
        errors: ::Array[top]
      }
    end
  end
end
