module Privy
  module Models
    type kraken_embed_get_asset_list_query_params_schema =
      {
        filter_assets: ::Array[String],
        filter_platform_statuses: ::Array[Privy::Models::KrakenEmbedGetAssetListQueryParamsSchema::filter_platform_status],
        filter_tradable_only: bool?,
        filter_user: String,
        lang: String,
        page_number: Integer,
        page_size: Integer,
        quote: String,
        sort: Privy::Models::kraken_embed_asset_sort_option
      }

    class KrakenEmbedGetAssetListQueryParamsSchema < Privy::Internal::Type::BaseModel
      attr_reader filter_assets: ::Array[String]?

      def filter_assets=: (::Array[String]) -> ::Array[String]

      attr_reader filter_platform_statuses: ::Array[Privy::Models::KrakenEmbedGetAssetListQueryParamsSchema::filter_platform_status]?

      def filter_platform_statuses=: (
        ::Array[Privy::Models::KrakenEmbedGetAssetListQueryParamsSchema::filter_platform_status]
      ) -> ::Array[Privy::Models::KrakenEmbedGetAssetListQueryParamsSchema::filter_platform_status]

      attr_accessor filter_tradable_only: bool?

      attr_reader filter_user: String?

      def filter_user=: (String) -> String

      attr_reader lang: String?

      def lang=: (String) -> String

      attr_reader page_number: Integer?

      def page_number=: (Integer) -> Integer

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader quote: String?

      def quote=: (String) -> String

      attr_reader sort: Privy::Models::kraken_embed_asset_sort_option?

      def sort=: (
        Privy::Models::kraken_embed_asset_sort_option
      ) -> Privy::Models::kraken_embed_asset_sort_option

      def initialize: (
        ?filter_assets: ::Array[String],
        ?filter_platform_statuses: ::Array[Privy::Models::KrakenEmbedGetAssetListQueryParamsSchema::filter_platform_status],
        ?filter_tradable_only: bool?,
        ?filter_user: String,
        ?lang: String,
        ?page_number: Integer,
        ?page_size: Integer,
        ?quote: String,
        ?sort: Privy::Models::kraken_embed_asset_sort_option
      ) -> void

      def to_hash: -> {
        filter_assets: ::Array[String],
        filter_platform_statuses: ::Array[Privy::Models::KrakenEmbedGetAssetListQueryParamsSchema::filter_platform_status],
        filter_tradable_only: bool?,
        filter_user: String,
        lang: String,
        page_number: Integer,
        page_size: Integer,
        quote: String,
        sort: Privy::Models::kraken_embed_asset_sort_option
      }

      type filter_platform_status =
        :enabled
        | :deposit_only
        | :withdrawal_only
        | :funding_temporarily_disabled
        | :disabled
        | String

      module FilterPlatformStatus
        extend Privy::Internal::Type::Union

        def self?.variants: -> ::Array[Privy::Models::KrakenEmbedGetAssetListQueryParamsSchema::filter_platform_status]

        ENABLED: :enabled
        DEPOSIT_ONLY: :deposit_only
        WITHDRAWAL_ONLY: :withdrawal_only
        FUNDING_TEMPORARILY_DISABLED: :funding_temporarily_disabled
        DISABLED: :disabled
      end
    end
  end
end
