module Privy
  module Models
    type kraken_embed_earn_user_allocation =
      {
        total_allocated: Privy::KrakenEmbedEarnAmount?,
        total_rewarded: Privy::KrakenEmbedEarnAmount?,
        upcoming_reward_date: Time?
      }

    class KrakenEmbedEarnUserAllocation < Privy::Internal::Type::BaseModel
      attr_accessor total_allocated: Privy::KrakenEmbedEarnAmount?

      attr_accessor total_rewarded: Privy::KrakenEmbedEarnAmount?

      attr_accessor upcoming_reward_date: Time?

      def initialize: (
        total_allocated: Privy::KrakenEmbedEarnAmount?,
        total_rewarded: Privy::KrakenEmbedEarnAmount?,
        ?upcoming_reward_date: Time?
      ) -> void

      def to_hash: -> {
        total_allocated: Privy::KrakenEmbedEarnAmount?,
        total_rewarded: Privy::KrakenEmbedEarnAmount?,
        upcoming_reward_date: Time?
      }
    end
  end
end
