module Privy
  module Models
    type kyb_associated_person =
      {
        date_of_birth: String,
        email: String,
        first_name: String,
        has_control: bool,
        has_ownership: bool,
        identifying_information: ::Array[Privy::VerificationDocument],
        is_signer: bool,
        last_name: String,
        residential_address: Privy::VerificationAddress,
        attested_ownership_structure_at: Privy::Models::KYBAssociatedPerson::attested_ownership_structure_at,
        documents: ::Array[Privy::KYBIndividualDocument],
        is_director: bool,
        kyc_screen: Privy::KyxScreen,
        middle_name: String,
        nationalities: ::Array[String],
        ofac_screen: Privy::KyxScreen,
        ownership_percentage: Integer,
        phone: String,
        place_of_birth: Privy::KYBPlaceOfBirth,
        relationship_established_at: String,
        title: String,
        transliterated_first_name: String,
        transliterated_last_name: String,
        transliterated_middle_name: String,
        transliterated_residential_address: Privy::VerificationAddress,
        verified_database_at: Privy::Models::KYBAssociatedPerson::verified_database_at,
        verified_govid_at: Privy::Models::KYBAssociatedPerson::verified_govid_at,
        verified_proof_of_address_at: Privy::Models::KYBAssociatedPerson::verified_proof_of_address_at
      }

    class KYBAssociatedPerson < Privy::Internal::Type::BaseModel
      attr_accessor date_of_birth: String

      attr_accessor email: String

      attr_accessor first_name: String

      attr_accessor has_control: bool

      attr_accessor has_ownership: bool

      attr_accessor identifying_information: ::Array[Privy::VerificationDocument]

      attr_accessor is_signer: bool

      attr_accessor last_name: String

      attr_accessor residential_address: Privy::VerificationAddress

      attr_reader attested_ownership_structure_at: Privy::Models::KYBAssociatedPerson::attested_ownership_structure_at?

      def attested_ownership_structure_at=: (
        Privy::Models::KYBAssociatedPerson::attested_ownership_structure_at
      ) -> Privy::Models::KYBAssociatedPerson::attested_ownership_structure_at

      attr_reader documents: ::Array[Privy::KYBIndividualDocument]?

      def documents=: (
        ::Array[Privy::KYBIndividualDocument]
      ) -> ::Array[Privy::KYBIndividualDocument]

      attr_reader is_director: bool?

      def is_director=: (bool) -> bool

      attr_reader kyc_screen: Privy::KyxScreen?

      def kyc_screen=: (Privy::KyxScreen) -> Privy::KyxScreen

      attr_reader middle_name: String?

      def middle_name=: (String) -> String

      attr_reader nationalities: ::Array[String]?

      def nationalities=: (::Array[String]) -> ::Array[String]

      attr_reader ofac_screen: Privy::KyxScreen?

      def ofac_screen=: (Privy::KyxScreen) -> Privy::KyxScreen

      attr_reader ownership_percentage: Integer?

      def ownership_percentage=: (Integer) -> Integer

      attr_reader phone: String?

      def phone=: (String) -> String

      attr_reader place_of_birth: Privy::KYBPlaceOfBirth?

      def place_of_birth=: (Privy::KYBPlaceOfBirth) -> Privy::KYBPlaceOfBirth

      attr_reader relationship_established_at: String?

      def relationship_established_at=: (String) -> String

      attr_reader title: String?

      def title=: (String) -> String

      attr_reader transliterated_first_name: String?

      def transliterated_first_name=: (String) -> String

      attr_reader transliterated_last_name: String?

      def transliterated_last_name=: (String) -> String

      attr_reader transliterated_middle_name: String?

      def transliterated_middle_name=: (String) -> String

      attr_reader transliterated_residential_address: Privy::VerificationAddress?

      def transliterated_residential_address=: (
        Privy::VerificationAddress
      ) -> Privy::VerificationAddress

      attr_reader verified_database_at: Privy::Models::KYBAssociatedPerson::verified_database_at?

      def verified_database_at=: (
        Privy::Models::KYBAssociatedPerson::verified_database_at
      ) -> Privy::Models::KYBAssociatedPerson::verified_database_at

      attr_reader verified_govid_at: Privy::Models::KYBAssociatedPerson::verified_govid_at?

      def verified_govid_at=: (
        Privy::Models::KYBAssociatedPerson::verified_govid_at
      ) -> Privy::Models::KYBAssociatedPerson::verified_govid_at

      attr_reader verified_proof_of_address_at: Privy::Models::KYBAssociatedPerson::verified_proof_of_address_at?

      def verified_proof_of_address_at=: (
        Privy::Models::KYBAssociatedPerson::verified_proof_of_address_at
      ) -> Privy::Models::KYBAssociatedPerson::verified_proof_of_address_at

      def initialize: (
        date_of_birth: String,
        email: String,
        first_name: String,
        has_control: bool,
        has_ownership: bool,
        identifying_information: ::Array[Privy::VerificationDocument],
        is_signer: bool,
        last_name: String,
        residential_address: Privy::VerificationAddress,
        ?attested_ownership_structure_at: Privy::Models::KYBAssociatedPerson::attested_ownership_structure_at,
        ?documents: ::Array[Privy::KYBIndividualDocument],
        ?is_director: bool,
        ?kyc_screen: Privy::KyxScreen,
        ?middle_name: String,
        ?nationalities: ::Array[String],
        ?ofac_screen: Privy::KyxScreen,
        ?ownership_percentage: Integer,
        ?phone: String,
        ?place_of_birth: Privy::KYBPlaceOfBirth,
        ?relationship_established_at: String,
        ?title: String,
        ?transliterated_first_name: String,
        ?transliterated_last_name: String,
        ?transliterated_middle_name: String,
        ?transliterated_residential_address: Privy::VerificationAddress,
        ?verified_database_at: Privy::Models::KYBAssociatedPerson::verified_database_at,
        ?verified_govid_at: Privy::Models::KYBAssociatedPerson::verified_govid_at,
        ?verified_proof_of_address_at: Privy::Models::KYBAssociatedPerson::verified_proof_of_address_at
      ) -> void

      def to_hash: -> {
        date_of_birth: String,
        email: String,
        first_name: String,
        has_control: bool,
        has_ownership: bool,
        identifying_information: ::Array[Privy::VerificationDocument],
        is_signer: bool,
        last_name: String,
        residential_address: Privy::VerificationAddress,
        attested_ownership_structure_at: Privy::Models::KYBAssociatedPerson::attested_ownership_structure_at,
        documents: ::Array[Privy::KYBIndividualDocument],
        is_director: bool,
        kyc_screen: Privy::KyxScreen,
        middle_name: String,
        nationalities: ::Array[String],
        ofac_screen: Privy::KyxScreen,
        ownership_percentage: Integer,
        phone: String,
        place_of_birth: Privy::KYBPlaceOfBirth,
        relationship_established_at: String,
        title: String,
        transliterated_first_name: String,
        transliterated_last_name: String,
        transliterated_middle_name: String,
        transliterated_residential_address: Privy::VerificationAddress,
        verified_database_at: Privy::Models::KYBAssociatedPerson::verified_database_at,
        verified_govid_at: Privy::Models::KYBAssociatedPerson::verified_govid_at,
        verified_proof_of_address_at: Privy::Models::KYBAssociatedPerson::verified_proof_of_address_at
      }

      type attested_ownership_structure_at = Time | Date

      module AttestedOwnershipStructureAt
        extend Privy::Internal::Type::Union

        def self?.variants: -> ::Array[Privy::Models::KYBAssociatedPerson::attested_ownership_structure_at]
      end

      type verified_database_at = Time | Date

      module VerifiedDatabaseAt
        extend Privy::Internal::Type::Union

        def self?.variants: -> ::Array[Privy::Models::KYBAssociatedPerson::verified_database_at]
      end

      type verified_govid_at = Time | Date

      module VerifiedGovidAt
        extend Privy::Internal::Type::Union

        def self?.variants: -> ::Array[Privy::Models::KYBAssociatedPerson::verified_govid_at]
      end

      type verified_proof_of_address_at = Time | Date

      module VerifiedProofOfAddressAt
        extend Privy::Internal::Type::Union

        def self?.variants: -> ::Array[Privy::Models::KYBAssociatedPerson::verified_proof_of_address_at]
      end
    end
  end
end
