module Privy
  module Models
    type kyx_endorsement =
      {
        issues: ::Array[String]?,
        missing: ::Array[String]?,
        name: String,
        status: String
      }

    class KyxEndorsement < Privy::Internal::Type::BaseModel
      attr_accessor issues: ::Array[String]?

      attr_accessor missing: ::Array[String]?

      attr_accessor name: String

      attr_accessor status: String

      def initialize: (
        issues: ::Array[String]?,
        missing: ::Array[String]?,
        name: String,
        status: String
      ) -> void

      def to_hash: -> {
        issues: ::Array[String]?,
        missing: ::Array[String]?,
        name: String,
        status: String
      }
    end
  end
end
