module Privy
  module Models
    type kyx_endorsement =
      { missing: ::Array[String]?, name: String, status: String }

    class KyxEndorsement < Privy::Internal::Type::BaseModel
      attr_accessor missing: ::Array[String]?

      attr_accessor name: String

      attr_accessor status: String

      def initialize: (
        missing: ::Array[String]?,
        name: String,
        status: String
      ) -> void

      def to_hash: -> {
        missing: ::Array[String]?,
        name: String,
        status: String
      }
    end
  end
end
