module Privy
  module Models
    type linked_account_wallet_input =
      {
        address: String,
        chain_type: Privy::Models::first_class_chain_type,
        type: :wallet
      }

    class LinkedAccountWalletInput < Privy::Internal::Type::BaseModel
      attr_accessor address: String

      attr_accessor chain_type: Privy::Models::first_class_chain_type

      attr_accessor type: :wallet

      def initialize: (
        address: String,
        chain_type: Privy::Models::first_class_chain_type,
        ?type: :wallet
      ) -> void

      def to_hash: -> {
        address: String,
        chain_type: Privy::Models::first_class_chain_type,
        type: :wallet
      }
    end
  end
end
