module Privy
  module Models
    type linked_account_base_wallet =
      {
        address: String,
        chain_type: Privy::Models::first_class_chain_type,
        type: Privy::Models::linked_account_base_wallet_type
      }

    class LinkedAccountBaseWallet < Privy::Internal::Type::BaseModel
      attr_accessor address: String

      attr_accessor chain_type: Privy::Models::first_class_chain_type

      attr_accessor type: Privy::Models::linked_account_base_wallet_type

      def initialize: (
        address: String,
        chain_type: Privy::Models::first_class_chain_type,
        type: Privy::Models::linked_account_base_wallet_type
      ) -> void

      def to_hash: -> {
        address: String,
        chain_type: Privy::Models::first_class_chain_type,
        type: Privy::Models::linked_account_base_wallet_type
      }
    end
  end
end
