module Privy
  module Models
    type linked_account_passkey_input =
      {
        credential_device_type: Privy::Models::linked_account_passkey_credential_device_type,
        credential_id: String,
        credential_public_key: String,
        credential_username: String,
        type: :passkey
      }

    class LinkedAccountPasskeyInput < Privy::Internal::Type::BaseModel
      attr_accessor credential_device_type: Privy::Models::linked_account_passkey_credential_device_type

      attr_accessor credential_id: String

      attr_accessor credential_public_key: String

      attr_accessor credential_username: String

      attr_accessor type: :passkey

      def initialize: (
        credential_device_type: Privy::Models::linked_account_passkey_credential_device_type,
        credential_id: String,
        credential_public_key: String,
        credential_username: String,
        ?type: :passkey
      ) -> void

      def to_hash: -> {
        credential_device_type: Privy::Models::linked_account_passkey_credential_device_type,
        credential_id: String,
        credential_public_key: String,
        credential_username: String,
        type: :passkey
      }
    end
  end
end
