module Privy
  module Models
    type linked_account_google_oauth =
      {
        email: String,
        first_verified_at: Float?,
        latest_verified_at: Float?,
        name: String?,
        subject: String,
        type: Privy::Models::LinkedAccountGoogleOAuth::type_,
        verified_at: Float
      }

    class LinkedAccountGoogleOAuth < Privy::Internal::Type::BaseModel
      attr_accessor email: String

      attr_accessor first_verified_at: Float?

      attr_accessor latest_verified_at: Float?

      attr_accessor name: String?

      attr_accessor subject: String

      attr_accessor type: Privy::Models::LinkedAccountGoogleOAuth::type_

      attr_accessor verified_at: Float

      def initialize: (
        email: String,
        first_verified_at: Float?,
        latest_verified_at: Float?,
        name: String?,
        subject: String,
        type: Privy::Models::LinkedAccountGoogleOAuth::type_,
        verified_at: Float
      ) -> void

      def to_hash: -> {
        email: String,
        first_verified_at: Float?,
        latest_verified_at: Float?,
        name: String?,
        subject: String,
        type: Privy::Models::LinkedAccountGoogleOAuth::type_,
        verified_at: Float
      }

      type type_ = :google_oauth

      module Type
        extend Privy::Internal::Type::Enum

        GOOGLE_OAUTH: :google_oauth

        def self?.values: -> ::Array[Privy::Models::LinkedAccountGoogleOAuth::type_]
      end
    end
  end
end
