module Privy
  module Models
    type linked_mfa_method =
      Privy::SMSMfaMethod | Privy::TotpMfaMethod | Privy::PasskeyMfaMethod

    module LinkedMfaMethod
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::linked_mfa_method]
    end
  end
end
