module Privy
  module Models
    type linked_account_spotify_input =
      { subject: String, type: :spotify_oauth, email: String, name: String }

    class LinkedAccountSpotifyInput < Privy::Internal::Type::BaseModel
      attr_accessor subject: String

      attr_accessor type: :spotify_oauth

      attr_reader email: String?

      def email=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        subject: String,
        ?email: String,
        ?name: String,
        ?type: :spotify_oauth
      ) -> void

      def to_hash: -> {
        subject: String,
        type: :spotify_oauth,
        email: String,
        name: String
      }
    end
  end
end
