module Privy
  module Models
    type linked_account_twitter_oauth =
      {
        first_verified_at: Float?,
        latest_verified_at: Float?,
        name: String?,
        profile_picture_url: String?,
        subject: String,
        type: Privy::Models::LinkedAccountTwitterOAuth::type_,
        username: String?,
        verified_at: Float
      }

    class LinkedAccountTwitterOAuth < Privy::Internal::Type::BaseModel
      attr_accessor first_verified_at: Float?

      attr_accessor latest_verified_at: Float?

      attr_accessor name: String?

      attr_accessor profile_picture_url: String?

      attr_accessor subject: String

      attr_accessor type: Privy::Models::LinkedAccountTwitterOAuth::type_

      attr_accessor username: String?

      attr_accessor verified_at: Float

      def initialize: (
        first_verified_at: Float?,
        latest_verified_at: Float?,
        name: String?,
        profile_picture_url: String?,
        subject: String,
        type: Privy::Models::LinkedAccountTwitterOAuth::type_,
        username: String?,
        verified_at: Float
      ) -> void

      def to_hash: -> {
        first_verified_at: Float?,
        latest_verified_at: Float?,
        name: String?,
        profile_picture_url: String?,
        subject: String,
        type: Privy::Models::LinkedAccountTwitterOAuth::type_,
        username: String?,
        verified_at: Float
      }

      type type_ = :twitter_oauth

      module Type
        extend Privy::Internal::Type::Enum

        TWITTER_OAUTH: :twitter_oauth

        def self?.values: -> ::Array[Privy::Models::LinkedAccountTwitterOAuth::type_]
      end
    end
  end
end
