module Privy
  module Models
    type linked_account_line_oauth =
      {
        email: String?,
        first_verified_at: Float?,
        latest_verified_at: Float?,
        name: String?,
        profile_picture_url: String?,
        subject: String,
        type: Privy::Models::LinkedAccountLineOAuth::type_,
        verified_at: Float
      }

    class LinkedAccountLineOAuth < Privy::Internal::Type::BaseModel
      attr_accessor email: String?

      attr_accessor first_verified_at: Float?

      attr_accessor latest_verified_at: Float?

      attr_accessor name: String?

      attr_accessor profile_picture_url: String?

      attr_accessor subject: String

      attr_accessor type: Privy::Models::LinkedAccountLineOAuth::type_

      attr_accessor verified_at: Float

      def initialize: (
        email: String?,
        first_verified_at: Float?,
        latest_verified_at: Float?,
        name: String?,
        profile_picture_url: String?,
        subject: String,
        type: Privy::Models::LinkedAccountLineOAuth::type_,
        verified_at: Float
      ) -> void

      def to_hash: -> {
        email: String?,
        first_verified_at: Float?,
        latest_verified_at: Float?,
        name: String?,
        profile_picture_url: String?,
        subject: String,
        type: Privy::Models::LinkedAccountLineOAuth::type_,
        verified_at: Float
      }

      type type_ = :line_oauth

      module Type
        extend Privy::Internal::Type::Enum

        LINE_OAUTH: :line_oauth

        def self?.values: -> ::Array[Privy::Models::LinkedAccountLineOAuth::type_]
      end
    end
  end
end
