module Privy
  module Models
    type linked_account_passkey_credential_device_type =
      :singleDevice | :multiDevice

    module LinkedAccountPasskeyCredentialDeviceType
      extend Privy::Internal::Type::Enum

      SINGLE_DEVICE: :singleDevice
      MULTI_DEVICE: :multiDevice

      def self?.values: -> ::Array[Privy::Models::linked_account_passkey_credential_device_type]
    end
  end
end
