module Privy
  module Models
    type linked_account_apple_oauth =
      {
        email: String?,
        first_verified_at: Float?,
        latest_verified_at: Float?,
        subject: String,
        type: Privy::Models::LinkedAccountAppleOAuth::type_,
        verified_at: Float
      }

    class LinkedAccountAppleOAuth < Privy::Internal::Type::BaseModel
      attr_accessor email: String?

      attr_accessor first_verified_at: Float?

      attr_accessor latest_verified_at: Float?

      attr_accessor subject: String

      attr_accessor type: Privy::Models::LinkedAccountAppleOAuth::type_

      attr_accessor verified_at: Float

      def initialize: (
        email: String?,
        first_verified_at: Float?,
        latest_verified_at: Float?,
        subject: String,
        type: Privy::Models::LinkedAccountAppleOAuth::type_,
        verified_at: Float
      ) -> void

      def to_hash: -> {
        email: String?,
        first_verified_at: Float?,
        latest_verified_at: Float?,
        subject: String,
        type: Privy::Models::LinkedAccountAppleOAuth::type_,
        verified_at: Float
      }

      type type_ = :apple_oauth

      module Type
        extend Privy::Internal::Type::Enum

        APPLE_OAUTH: :apple_oauth

        def self?.values: -> ::Array[Privy::Models::LinkedAccountAppleOAuth::type_]
      end
    end
  end
end
