module Privy
  module Models
    type list_external_fiat_accounts_response =
      {
        external_fiat_accounts: ::Array[Privy::ExternalFiatAccount],
        next_cursor: String?
      }

    class ListExternalFiatAccountsResponse < Privy::Internal::Type::BaseModel
      attr_accessor external_fiat_accounts: ::Array[Privy::ExternalFiatAccount]

      attr_accessor next_cursor: String?

      def initialize: (
        external_fiat_accounts: ::Array[Privy::ExternalFiatAccount],
        next_cursor: String?
      ) -> void

      def to_hash: -> {
        external_fiat_accounts: ::Array[Privy::ExternalFiatAccount],
        next_cursor: String?
      }
    end
  end
end
