module Privy
  module Models
    type mfa_enabled_webhook_payload =
      {
        method_: Privy::Models::MfaEnabledWebhookPayload::method_,
        type: Privy::Models::MfaEnabledWebhookPayload::type_,
        user_id: String
      }

    class MfaEnabledWebhookPayload < Privy::Internal::Type::BaseModel
      attr_accessor method_: Privy::Models::MfaEnabledWebhookPayload::method_

      attr_accessor type: Privy::Models::MfaEnabledWebhookPayload::type_

      attr_accessor user_id: String

      def initialize: (
        method_: Privy::Models::MfaEnabledWebhookPayload::method_,
        type: Privy::Models::MfaEnabledWebhookPayload::type_,
        user_id: String
      ) -> void

      def to_hash: -> {
        method_: Privy::Models::MfaEnabledWebhookPayload::method_,
        type: Privy::Models::MfaEnabledWebhookPayload::type_,
        user_id: String
      }

      type method_ = :sms | :totp | :passkey

      module Method
        extend Privy::Internal::Type::Enum

        SMS: :sms
        TOTP: :totp
        PASSKEY: :passkey

        def self?.values: -> ::Array[Privy::Models::MfaEnabledWebhookPayload::method_]
      end

      type type_ = :"mfa.enabled"

      module Type
        extend Privy::Internal::Type::Enum

        MFA_ENABLED: :"mfa.enabled"

        def self?.values: -> ::Array[Privy::Models::MfaEnabledWebhookPayload::type_]
      end
    end
  end
end
