module Privy
  module Models
    type mfa_enabled_webhook_payload =
      {
        method_: Privy::Models::mfa_method,
        type: Privy::Models::MfaEnabledWebhookPayload::type_,
        user_id: String
      }

    class MfaEnabledWebhookPayload < Privy::Internal::Type::BaseModel
      attr_accessor method_: Privy::Models::mfa_method

      attr_accessor type: Privy::Models::MfaEnabledWebhookPayload::type_

      attr_accessor user_id: String

      def initialize: (
        method_: Privy::Models::mfa_method,
        type: Privy::Models::MfaEnabledWebhookPayload::type_,
        user_id: String
      ) -> void

      def to_hash: -> {
        method_: Privy::Models::mfa_method,
        type: Privy::Models::MfaEnabledWebhookPayload::type_,
        user_id: String
      }

      type type_ = :"mfa.enabled"

      module Type
        extend Privy::Internal::Type::Enum

        MFA_ENABLED: :"mfa.enabled"

        def self?.values: -> ::Array[Privy::Models::MfaEnabledWebhookPayload::type_]
      end
    end
  end
end
