module Privy
  module Models
    type mfa_disabled_webhook_payload =
      {
        method_: Privy::Models::mfa_method,
        type: Privy::Models::MfaDisabledWebhookPayload::type_,
        user_id: String
      }

    class MfaDisabledWebhookPayload < Privy::Internal::Type::BaseModel
      attr_accessor method_: Privy::Models::mfa_method

      attr_accessor type: Privy::Models::MfaDisabledWebhookPayload::type_

      attr_accessor user_id: String

      def initialize: (
        method_: Privy::Models::mfa_method,
        type: Privy::Models::MfaDisabledWebhookPayload::type_,
        user_id: String
      ) -> void

      def to_hash: -> {
        method_: Privy::Models::mfa_method,
        type: Privy::Models::MfaDisabledWebhookPayload::type_,
        user_id: String
      }

      type type_ = :"mfa.disabled"

      module Type
        extend Privy::Internal::Type::Enum

        MFA_DISABLED: :"mfa.disabled"

        def self?.values: -> ::Array[Privy::Models::MfaDisabledWebhookPayload::type_]
      end
    end
  end
end
