module Privy
  module Models
    type mfa_passkey_init_request_body = { relying_party: String }

    class MfaPasskeyInitRequestBody < Privy::Internal::Type::BaseModel
      attr_reader relying_party: String?

      def relying_party=: (String) -> String

      def initialize: (?relying_party: String) -> void

      def to_hash: -> { relying_party: String }
    end
  end
end
