module Privy
  module Models
    type mfa_passkey_verify_request_body =
      {
        authenticator_response: Privy::PasskeyAuthenticatorVerifyResponse,
        relying_party: String
      }

    class MfaPasskeyVerifyRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor authenticator_response: Privy::PasskeyAuthenticatorVerifyResponse

      attr_reader relying_party: String?

      def relying_party=: (String) -> String

      def initialize: (
        authenticator_response: Privy::PasskeyAuthenticatorVerifyResponse,
        ?relying_party: String
      ) -> void

      def to_hash: -> {
        authenticator_response: Privy::PasskeyAuthenticatorVerifyResponse,
        relying_party: String
      }
    end
  end
end
