module Privy
  module Models
    type moonpay_payment_method =
      :ach_bank_transfer
      | :credit_debit_card
      | :gbp_bank_transfer
      | :gbp_open_banking_payment
      | :mobile_wallet
      | :sepa_bank_transfer
      | :sepa_open_banking_payment
      | :pix_instant_payment
      | :yellow_card_bank_transfer

    module MoonpayPaymentMethod
      extend Privy::Internal::Type::Enum

      ACH_BANK_TRANSFER: :ach_bank_transfer
      CREDIT_DEBIT_CARD: :credit_debit_card
      GBP_BANK_TRANSFER: :gbp_bank_transfer
      GBP_OPEN_BANKING_PAYMENT: :gbp_open_banking_payment
      MOBILE_WALLET: :mobile_wallet
      SEPA_BANK_TRANSFER: :sepa_bank_transfer
      SEPA_OPEN_BANKING_PAYMENT: :sepa_open_banking_payment
      PIX_INSTANT_PAYMENT: :pix_instant_payment
      YELLOW_CARD_BANK_TRANSFER: :yellow_card_bank_transfer

      def self?.values: -> ::Array[Privy::Models::moonpay_payment_method]
    end
  end
end
