module Privy
  module Models
    type named_token_transfer_source =
      { asset: String, chain: String, amount: String }

    class NamedTokenTransferSource < Privy::Internal::Type::BaseModel
      attr_accessor asset: String

      attr_accessor chain: String

      attr_reader amount: String?

      def amount=: (String) -> String

      def initialize: (asset: String, chain: String, ?amount: String) -> void

      def to_hash: -> { asset: String, chain: String, amount: String }
    end
  end
end
