module Privy
  module Models
    type named_token_transfer_source =
      { amount: String, asset: String, chain: String }

    class NamedTokenTransferSource < Privy::Internal::Type::BaseModel
      attr_accessor amount: String

      attr_accessor asset: String

      attr_accessor chain: String

      def initialize: (amount: String, asset: String, chain: String) -> void

      def to_hash: -> { amount: String, asset: String, chain: String }
    end
  end
end
