module Privy
  module Models
    type oauth_token_device_code_pending_error =
      {
        error: Privy::Models::OAuthTokenDeviceCodePendingError::error,
        error_description: String,
        interval: Float
      }

    class OAuthTokenDeviceCodePendingError < Privy::Internal::Type::BaseModel
      attr_accessor error: Privy::Models::OAuthTokenDeviceCodePendingError::error

      attr_reader error_description: String?

      def error_description=: (String) -> String

      attr_reader interval: Float?

      def interval=: (Float) -> Float

      def initialize: (
        error: Privy::Models::OAuthTokenDeviceCodePendingError::error,
        ?error_description: String,
        ?interval: Float
      ) -> void

      def to_hash: -> {
        error: Privy::Models::OAuthTokenDeviceCodePendingError::error,
        error_description: String,
        interval: Float
      }

      type error =
        :authorization_pending | :slow_down | :access_denied | :expired_token

      module Error
        extend Privy::Internal::Type::Enum

        AUTHORIZATION_PENDING: :authorization_pending
        SLOW_DOWN: :slow_down
        ACCESS_DENIED: :access_denied
        EXPIRED_TOKEN: :expired_token

        def self?.values: -> ::Array[Privy::Models::OAuthTokenDeviceCodePendingError::error]
      end
    end
  end
end
