module Privy
  module Models
    type oauth_token_device_code_pending_error_code =
      :authorization_pending | :slow_down | :access_denied | :expired_token

    module OAuthTokenDeviceCodePendingErrorCode
      extend Privy::Internal::Type::Enum

      AUTHORIZATION_PENDING: :authorization_pending
      SLOW_DOWN: :slow_down
      ACCESS_DENIED: :access_denied
      EXPIRED_TOKEN: :expired_token

      def self?.values: -> ::Array[Privy::Models::oauth_token_device_code_pending_error_code]
    end
  end
end
