module Privy
  module Models
    type offramp_response =
      {
        id: String,
        deposit_instructions: Privy::OfframpDepositInstructions,
        status: Privy::Models::onramp_transfer_status
      }

    class OfframpResponse < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor deposit_instructions: Privy::OfframpDepositInstructions

      attr_accessor status: Privy::Models::onramp_transfer_status

      def initialize: (
        id: String,
        deposit_instructions: Privy::OfframpDepositInstructions,
        status: Privy::Models::onramp_transfer_status
      ) -> void

      def to_hash: -> {
        id: String,
        deposit_instructions: Privy::OfframpDepositInstructions,
        status: Privy::Models::onramp_transfer_status
      }
    end
  end
end
