module Privy
  module Models
    type offramp_deposit_instructions =
      {
        amount: String,
        chain: Privy::Models::onramp_chain,
        currency: Privy::Models::onramp_asset,
        from_address: String,
        to_address: String
      }

    class OfframpDepositInstructions < Privy::Internal::Type::BaseModel
      attr_accessor amount: String

      attr_accessor chain: Privy::Models::onramp_chain

      attr_accessor currency: Privy::Models::onramp_asset

      attr_accessor from_address: String

      attr_accessor to_address: String

      def initialize: (
        amount: String,
        chain: Privy::Models::onramp_chain,
        currency: Privy::Models::onramp_asset,
        from_address: String,
        to_address: String
      ) -> void

      def to_hash: -> {
        amount: String,
        chain: Privy::Models::onramp_chain,
        currency: Privy::Models::onramp_asset,
        from_address: String,
        to_address: String
      }
    end
  end
end
