module Privy
  module Models
    type onramp_kyc_status =
      :not_found
      | :active
      | :awaiting_questionnaire
      | :awaiting_ubo
      | :incomplete
      | :not_started
      | :offboarded
      | :paused
      | :rejected
      | :under_review

    module OnrampKYCStatus
      extend Privy::Internal::Type::Enum

      NOT_FOUND: :not_found
      ACTIVE: :active
      AWAITING_QUESTIONNAIRE: :awaiting_questionnaire
      AWAITING_UBO: :awaiting_ubo
      INCOMPLETE: :incomplete
      NOT_STARTED: :not_started
      OFFBOARDED: :offboarded
      PAUSED: :paused
      REJECTED: :rejected
      UNDER_REVIEW: :under_review

      def self?.values: -> ::Array[Privy::Models::onramp_kyc_status]
    end
  end
end
