module Privy
  module Models
    type onramp_asset = :usdc

    module OnrampAsset
      extend Privy::Internal::Type::Enum

      USDC: :usdc

      def self?.values: -> ::Array[Privy::Models::onramp_asset]
    end
  end
end
