module Privy
  module Models
    type onramp_session_transaction_details =
      {
        destination_amount: String?,
        destination_currency: String?,
        destination_network: String?,
        fee: String?,
        source_currency: String?,
        source_total_amount: String?,
        quote_expiration: Float?
      }

    class OnrampSessionTransactionDetails < Privy::Internal::Type::BaseModel
      attr_accessor destination_amount: String?

      attr_accessor destination_currency: String?

      attr_accessor destination_network: String?

      attr_accessor fee: String?

      attr_accessor source_currency: String?

      attr_accessor source_total_amount: String?

      attr_accessor quote_expiration: Float?

      def initialize: (
        destination_amount: String?,
        destination_currency: String?,
        destination_network: String?,
        fee: String?,
        source_currency: String?,
        source_total_amount: String?,
        ?quote_expiration: Float?
      ) -> void

      def to_hash: -> {
        destination_amount: String?,
        destination_currency: String?,
        destination_network: String?,
        fee: String?,
        source_currency: String?,
        source_total_amount: String?,
        quote_expiration: Float?
      }
    end
  end
end
