module Privy
  module Models
    type onramp_chain = :ethereum | :base | :arbitrum | :polygon | :optimism

    module OnrampChain
      extend Privy::Internal::Type::Enum

      ETHEREUM: :ethereum
      BASE: :base
      ARBITRUM: :arbitrum
      POLYGON: :polygon
      OPTIMISM: :optimism

      def self?.values: -> ::Array[Privy::Models::onramp_chain]
    end
  end
end
