module Privy
  module Models
    type onramp_kyc_response =
      {
        status: Privy::Models::onramp_kyc_status,
        user_id: String,
        provider_user_id: String
      }

    class OnrampKYCResponse < Privy::Internal::Type::BaseModel
      attr_accessor status: Privy::Models::onramp_kyc_status

      attr_accessor user_id: String

      attr_reader provider_user_id: String?

      def provider_user_id=: (String) -> String

      def initialize: (
        status: Privy::Models::onramp_kyc_status,
        user_id: String,
        ?provider_user_id: String
      ) -> void

      def to_hash: -> {
        status: Privy::Models::onramp_kyc_status,
        user_id: String,
        provider_user_id: String
      }
    end
  end
end
