module Privy
  module Models
    type onramp_session_transaction_details =
      {
        destination_amount: String?,
        destination_currency: String?,
        destination_network: String?,
        fees: Privy::OnrampSessionFees?,
        source_currency: String?,
        source_total_amount: String?
      }

    class OnrampSessionTransactionDetails < Privy::Internal::Type::BaseModel
      attr_accessor destination_amount: String?

      attr_accessor destination_currency: String?

      attr_accessor destination_network: String?

      attr_accessor fees: Privy::OnrampSessionFees?

      attr_accessor source_currency: String?

      attr_accessor source_total_amount: String?

      def initialize: (
        destination_amount: String?,
        destination_currency: String?,
        destination_network: String?,
        fees: Privy::OnrampSessionFees?,
        source_currency: String?,
        source_total_amount: String?
      ) -> void

      def to_hash: -> {
        destination_amount: String?,
        destination_currency: String?,
        destination_network: String?,
        fees: Privy::OnrampSessionFees?,
        source_currency: String?,
        source_total_amount: String?
      }
    end
  end
end
