module Privy
  module Models
    type onramp_transfer_status =
      :awaiting_funds
      | :in_review
      | :funds_received
      | :payment_submitted
      | :payment_processed
      | :canceled
      | :error
      | :undeliverable
      | :returned
      | :refunded

    module OnrampTransferStatus
      extend Privy::Internal::Type::Enum

      AWAITING_FUNDS: :awaiting_funds
      IN_REVIEW: :in_review
      FUNDS_RECEIVED: :funds_received
      PAYMENT_SUBMITTED: :payment_submitted
      PAYMENT_PROCESSED: :payment_processed
      CANCELED: :canceled
      ERROR: :error
      UNDELIVERABLE: :undeliverable
      RETURNED: :returned
      REFUNDED: :refunded

      def self?.values: -> ::Array[Privy::Models::onramp_transfer_status]
    end
  end
end
