module Privy
  module Models
    type organization_secrets_list_response =
      { data: ::Array[Privy::OrganizationSecretView] }

    class OrganizationSecretsListResponse < Privy::Internal::Type::BaseModel
      attr_accessor data: ::Array[Privy::OrganizationSecretView]

      def initialize: (data: ::Array[Privy::OrganizationSecretView]) -> void

      def to_hash: -> { data: ::Array[Privy::OrganizationSecretView] }
    end
  end
end
