module Privy
  module Models
    type organization_secret_id_input = { secret_id: String }

    class OrganizationSecretIDInput < Privy::Internal::Type::BaseModel
      attr_accessor secret_id: String

      def initialize: (secret_id: String) -> void

      def to_hash: -> { secret_id: String }
    end
  end
end
