module Privy
  module Models
    type organization_secret_view =
      {
        id: String,
        created_at: String,
        last_four: String,
        revoked_at: String?,
        signing_public_key: String?
      }

    class OrganizationSecretView < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: String

      attr_accessor last_four: String

      attr_accessor revoked_at: String?

      attr_accessor signing_public_key: String?

      def initialize: (
        id: String,
        created_at: String,
        last_four: String,
        revoked_at: String?,
        signing_public_key: String?
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: String,
        last_four: String,
        revoked_at: String?,
        signing_public_key: String?
      }
    end
  end
end
