module Privy
  module Models
    type passwordless_sms_authenticate_request_body =
      {
        code: String,
        phone_number: String,
        mode: Privy::Models::authenticate_mode_option
      }

    class PasswordlessSMSAuthenticateRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor code: String

      attr_accessor phone_number: String

      attr_reader mode: Privy::Models::authenticate_mode_option?

      def mode=: (
        Privy::Models::authenticate_mode_option
      ) -> Privy::Models::authenticate_mode_option

      def initialize: (
        code: String,
        phone_number: String,
        ?mode: Privy::Models::authenticate_mode_option
      ) -> void

      def to_hash: -> {
        code: String,
        phone_number: String,
        mode: Privy::Models::authenticate_mode_option
      }
    end
  end
end
