module Privy
  module Models
    type passwordless_link_request_body = { code: String, email: String }

    class PasswordlessLinkRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor code: String

      attr_accessor email: String

      def initialize: (code: String, email: String) -> void

      def to_hash: -> { code: String, email: String }
    end
  end
end
