module Privy
  module Models
    type passwordless_unlink_request_body = { address: String }

    class PasswordlessUnlinkRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor address: String

      def initialize: (address: String) -> void

      def to_hash: -> { address: String }
    end
  end
end
