module Privy
  module Models
    type passwordless_sms_transfer_request_body =
      { nonce: String, phone_number: String }

    class PasswordlessSMSTransferRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor nonce: String

      attr_accessor phone_number: String

      def initialize: (nonce: String, phone_number: String) -> void

      def to_hash: -> { nonce: String, phone_number: String }
    end
  end
end
