module Privy
  module Models
    type passkey_credential_descriptor =
      { id: String, type: String, transports: ::Array[String] }

    class PasskeyCredentialDescriptor < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor type: String

      attr_reader transports: ::Array[String]?

      def transports=: (::Array[String]) -> ::Array[String]

      def initialize: (
        id: String,
        type: String,
        ?transports: ::Array[String]
      ) -> void

      def to_hash: -> { id: String, type: String, transports: ::Array[String] }
    end
  end
end
