module Privy
  module Models
    type passwordless_sms_unlink_request_body = { phone_number: String }

    class PasswordlessSMSUnlinkRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor phone_number: String

      def initialize: (phone_number: String) -> void

      def to_hash: -> { phone_number: String }
    end
  end
end
