module Privy
  module Models
    type passwordless_update_request_body =
      { code: String, new_address: String, old_address: String }

    class PasswordlessUpdateRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor code: String

      attr_accessor new_address: String

      attr_accessor old_address: String

      def initialize: (
        code: String,
        new_address: String,
        old_address: String
      ) -> void

      def to_hash: -> { code: String, new_address: String, old_address: String }
    end
  end
end
