module Privy
  module Models
    type passwordless_transfer_request_body = { email: String, nonce: String }

    class PasswordlessTransferRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor email: String

      attr_accessor nonce: String

      def initialize: (email: String, nonce: String) -> void

      def to_hash: -> { email: String, nonce: String }
    end
  end
end
