module Privy
  module Models
    type passwordless_authenticate_request_body =
      {
        code: String,
        email: String,
        mode: Privy::Models::authenticate_mode_option
      }

    class PasswordlessAuthenticateRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor code: String

      attr_accessor email: String

      attr_reader mode: Privy::Models::authenticate_mode_option?

      def mode=: (
        Privy::Models::authenticate_mode_option
      ) -> Privy::Models::authenticate_mode_option

      def initialize: (
        code: String,
        email: String,
        ?mode: Privy::Models::authenticate_mode_option
      ) -> void

      def to_hash: -> {
        code: String,
        email: String,
        mode: Privy::Models::authenticate_mode_option
      }
    end
  end
end
