module Privy
  module Models
    type passwordless_init_request_body = { email: String, token: String }

    class PasswordlessInitRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor email: String

      attr_reader token: String?

      def token=: (String) -> String

      def initialize: (email: String, ?token: String) -> void

      def to_hash: -> { email: String, token: String }
    end
  end
end
