module Privy
  module Models
    type passwordless_sms_update_request_body =
      { code: String, new_phone_number: String, old_phone_number: String }

    class PasswordlessSMSUpdateRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor code: String

      attr_accessor new_phone_number: String

      attr_accessor old_phone_number: String

      def initialize: (
        code: String,
        new_phone_number: String,
        old_phone_number: String
      ) -> void

      def to_hash: -> {
        code: String,
        new_phone_number: String,
        old_phone_number: String
      }
    end
  end
end
