module Privy
  module Models
    type passwordless_sms_link_request_body =
      { code: String, phone_number: String }

    class PasswordlessSMSLinkRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor code: String

      attr_accessor phone_number: String

      def initialize: (code: String, phone_number: String) -> void

      def to_hash: -> { code: String, phone_number: String }
    end
  end
end
