module Privy
  module Models
    type passwordless_sms_init_request_body =
      { phone_number: String, token: String }

    class PasswordlessSMSInitRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor phone_number: String

      attr_reader token: String?

      def token=: (String) -> String

      def initialize: (phone_number: String, ?token: String) -> void

      def to_hash: -> { phone_number: String, token: String }
    end
  end
end
