module Privy
  module Models
    type policy_rule_request_params = { policy_id: String, rule_id: String }

    class PolicyRuleRequestParams < Privy::Internal::Type::BaseModel
      attr_accessor policy_id: String

      attr_accessor rule_id: String

      def initialize: (policy_id: String, rule_id: String) -> void

      def to_hash: -> { policy_id: String, rule_id: String }
    end
  end
end
