module Privy
  module Models
    type policy_method =
      :eth_sendTransaction
      | :eth_signTransaction
      | :eth_signUserOperation
      | :eth_signTypedData_v4
      | :personal_sign
      | :eth_sign7702Authorization
      | :wallet_sendCalls
      | :signTransaction
      | :signAndSendTransaction
      | :exportPrivateKey
      | :exportSeedPhrase
      | :signTransactionBytes
      | :raw_sign
      | :earn_deposit
      | :earn_withdraw
      | :transfer
      | :*

    module PolicyMethod
      extend Privy::Internal::Type::Enum

      ETH_SEND_TRANSACTION: :eth_sendTransaction
      ETH_SIGN_TRANSACTION: :eth_signTransaction
      ETH_SIGN_USER_OPERATION: :eth_signUserOperation
      ETH_SIGN_TYPED_DATA_V4: :eth_signTypedData_v4
      PERSONAL_SIGN: :personal_sign
      ETH_SIGN7702_AUTHORIZATION: :eth_sign7702Authorization
      WALLET_SEND_CALLS: :wallet_sendCalls
      SIGN_TRANSACTION: :signTransaction
      SIGN_AND_SEND_TRANSACTION: :signAndSendTransaction
      EXPORT_PRIVATE_KEY: :exportPrivateKey
      EXPORT_SEED_PHRASE: :exportSeedPhrase
      SIGN_TRANSACTION_BYTES: :signTransactionBytes
      RAW_SIGN: :raw_sign
      EARN_DEPOSIT: :earn_deposit
      EARN_WITHDRAW: :earn_withdraw
      TRANSFER: :transfer
      STAR: :*

      def self?.values: -> ::Array[Privy::Models::policy_method]
    end
  end
end
