module Privy
  module Models
    type policy =
      {
        id: String,
        chain_type: Privy::Models::wallet_chain_type,
        created_at: Float,
        name: String,
        owner_id: String?,
        rules: ::Array[Privy::PolicyRuleResponse],
        version: Privy::Models::Policy::version
      }

    class Policy < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor chain_type: Privy::Models::wallet_chain_type

      attr_accessor created_at: Float

      attr_accessor name: String

      attr_accessor owner_id: String?

      attr_accessor rules: ::Array[Privy::PolicyRuleResponse]

      attr_accessor version: Privy::Models::Policy::version

      def initialize: (
        id: String,
        chain_type: Privy::Models::wallet_chain_type,
        created_at: Float,
        name: String,
        owner_id: String?,
        rules: ::Array[Privy::PolicyRuleResponse],
        version: Privy::Models::Policy::version
      ) -> void

      def to_hash: -> {
        id: String,
        chain_type: Privy::Models::wallet_chain_type,
        created_at: Float,
        name: String,
        owner_id: String?,
        rules: ::Array[Privy::PolicyRuleResponse],
        version: Privy::Models::Policy::version
      }

      type version = :"1.0"

      module Version
        extend Privy::Internal::Type::Enum

        VERSION_1_0: :"1.0"

        def self?.values: -> ::Array[Privy::Models::Policy::version]
      end
    end
  end
end
