module Privy
  module Models
    type raw_sign_hash_params = { hash_: String }

    class RawSignHashParams < Privy::Internal::Type::BaseModel
      attr_accessor hash_: String

      def initialize: (hash_: String) -> void

      def to_hash: -> { hash_: String }
    end
  end
end
