module Privy
  module Models
    type refund_details =
      {
        original_transaction_hash: String,
        provider: Privy::Models::RefundDetails::provider,
        wallet_action_id: String
      }

    class RefundDetails < Privy::Internal::Type::BaseModel
      attr_accessor original_transaction_hash: String

      attr_accessor provider: Privy::Models::RefundDetails::provider

      attr_accessor wallet_action_id: String

      def initialize: (
        original_transaction_hash: String,
        provider: Privy::Models::RefundDetails::provider,
        wallet_action_id: String
      ) -> void

      def to_hash: -> {
        original_transaction_hash: String,
        provider: Privy::Models::RefundDetails::provider,
        wallet_action_id: String
      }

      type provider = :relay

      module Provider
        extend Privy::Internal::Type::Enum

        RELAY: :relay

        def self?.values: -> ::Array[Privy::Models::RefundDetails::provider]
      end
    end
  end
end
