module Privy
  module Models
    type rpc_sponsor_options = { asset: String }

    class RpcSponsorOptions < Privy::Internal::Type::BaseModel
      attr_accessor asset: String

      def initialize: (asset: String) -> void

      def to_hash: -> { asset: String }
    end
  end
end
