module Privy
  module Models
    type rule_mutate_intent_response =
      {
        intent_type: Privy::Models::RuleMutateIntentResponse::intent_type,
        request_details: Privy::Models::rule_intent_request_details,
        action_result: Privy::BaseActionResult,
        current_resource_data: Privy::PolicyRuleResponse,
        policy: Privy::Policy
      }

    class RuleMutateIntentResponse < Privy::Models::BaseIntentResponse
      def intent_type: -> Privy::Models::RuleMutateIntentResponse::intent_type

      def intent_type=: (
        Privy::Models::RuleMutateIntentResponse::intent_type _
      ) -> Privy::Models::RuleMutateIntentResponse::intent_type

      def request_details: -> Privy::Models::rule_intent_request_details

      def request_details=: (
        Privy::Models::rule_intent_request_details _
      ) -> Privy::Models::rule_intent_request_details

      def action_result: -> Privy::BaseActionResult?

      def action_result=: (Privy::BaseActionResult _) -> Privy::BaseActionResult

      def current_resource_data: -> Privy::PolicyRuleResponse?

      def current_resource_data=: (
        Privy::PolicyRuleResponse _
      ) -> Privy::PolicyRuleResponse

      def policy: -> Privy::Policy?

      def policy=: (Privy::Policy _) -> Privy::Policy

      def initialize: (
        intent_type: Privy::Models::RuleMutateIntentResponse::intent_type,
        request_details: Privy::Models::rule_intent_request_details,
        ?action_result: Privy::BaseActionResult,
        ?current_resource_data: Privy::PolicyRuleResponse,
        ?policy: Privy::Policy
      ) -> void

      def to_hash: -> {
        intent_type: Privy::Models::RuleMutateIntentResponse::intent_type,
        request_details: Privy::Models::rule_intent_request_details,
        action_result: Privy::BaseActionResult,
        current_resource_data: Privy::PolicyRuleResponse,
        policy: Privy::Policy
      }

      type intent_type = :RULE

      module IntentType
        extend Privy::Internal::Type::Enum

        RULE: :RULE

        def self?.values: -> ::Array[Privy::Models::RuleMutateIntentResponse::intent_type]
      end
    end
  end
end
