module Privy
  module Models
    type rule_intent_delete_request_details =
      {
        method_: Privy::Models::RuleIntentDeleteRequestDetails::method_,
        url: String,
        body: Privy::RuleIntentDeleteRequestBody
      }

    class RuleIntentDeleteRequestDetails < Privy::Internal::Type::BaseModel
      attr_accessor method_: Privy::Models::RuleIntentDeleteRequestDetails::method_

      attr_accessor url: String

      attr_reader body: Privy::RuleIntentDeleteRequestBody?

      def body=: (
        Privy::RuleIntentDeleteRequestBody
      ) -> Privy::RuleIntentDeleteRequestBody

      def initialize: (
        method_: Privy::Models::RuleIntentDeleteRequestDetails::method_,
        url: String,
        ?body: Privy::RuleIntentDeleteRequestBody
      ) -> void

      def to_hash: -> {
        method_: Privy::Models::RuleIntentDeleteRequestDetails::method_,
        url: String,
        body: Privy::RuleIntentDeleteRequestBody
      }

      type method_ = :DELETE

      module Method
        extend Privy::Internal::Type::Enum

        DELETE: :DELETE

        def self?.values: -> ::Array[Privy::Models::RuleIntentDeleteRequestDetails::method_]
      end
    end
  end
end
