module Privy
  module Models
    type siws_input =
      {
        message: String,
        signature: String,
        connector_type: String?,
        message_type: Privy::Models::siws_message_type,
        wallet_client_type: String?
      }

    class SiwsInput < Privy::Internal::Type::BaseModel
      attr_accessor message: String

      attr_accessor signature: String

      attr_accessor connector_type: String?

      attr_reader message_type: Privy::Models::siws_message_type?

      def message_type=: (
        Privy::Models::siws_message_type
      ) -> Privy::Models::siws_message_type

      attr_accessor wallet_client_type: String?

      def initialize: (
        message: String,
        signature: String,
        ?connector_type: String?,
        ?message_type: Privy::Models::siws_message_type,
        ?wallet_client_type: String?
      ) -> void

      def to_hash: -> {
        message: String,
        signature: String,
        connector_type: String?,
        message_type: Privy::Models::siws_message_type,
        wallet_client_type: String?
      }
    end
  end
end
