module Privy
  module Models
    type siws_address_input = { address: String }

    class SiwsAddressInput < Privy::Internal::Type::BaseModel
      attr_accessor address: String

      def initialize: (address: String) -> void

      def to_hash: -> { address: String }
    end
  end
end
