module Privy
  module Models
    type smart_wallet_configuration_input =
      Privy::SmartWalletConfigurationDisabled
      | Privy::SmartWalletConfigurationInputEnabled

    module SmartWalletConfigurationInput
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::smart_wallet_configuration_input]
    end
  end
end
