module Privy
  module Models
    type sms_mfa_method =
      { type: Privy::Models::SMSMfaMethod::type_, verified_at: Float }

    class SMSMfaMethod < Privy::Internal::Type::BaseModel
      attr_accessor type: Privy::Models::SMSMfaMethod::type_

      attr_accessor verified_at: Float

      def initialize: (
        type: Privy::Models::SMSMfaMethod::type_,
        verified_at: Float
      ) -> void

      def to_hash: -> {
        type: Privy::Models::SMSMfaMethod::type_,
        verified_at: Float
      }

      type type_ = :sms

      module Type
        extend Privy::Internal::Type::Enum

        SMS: :sms

        def self?.values: -> ::Array[Privy::Models::SMSMfaMethod::type_]
      end
    end
  end
end
