module Privy
  module Models
    type solana_token_program_instruction_condition =
      {
        field: Privy::Models::solana_token_program_instruction_condition_field,
        field_source: Privy::Models::SolanaTokenProgramInstructionCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      }

    class SolanaTokenProgramInstructionCondition < Privy::Internal::Type::BaseModel
      attr_accessor field: Privy::Models::solana_token_program_instruction_condition_field

      attr_accessor field_source: Privy::Models::SolanaTokenProgramInstructionCondition::field_source

      attr_accessor operator: Privy::Models::condition_operator

      attr_accessor value: Privy::Models::condition_value

      def initialize: (
        field: Privy::Models::solana_token_program_instruction_condition_field,
        field_source: Privy::Models::SolanaTokenProgramInstructionCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      ) -> void

      def to_hash: -> {
        field: Privy::Models::solana_token_program_instruction_condition_field,
        field_source: Privy::Models::SolanaTokenProgramInstructionCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      }

      type field_source = :solana_token_program_instruction

      module FieldSource
        extend Privy::Internal::Type::Enum

        SOLANA_TOKEN_PROGRAM_INSTRUCTION: :solana_token_program_instruction

        def self?.values: -> ::Array[Privy::Models::SolanaTokenProgramInstructionCondition::field_source]
      end
    end
  end
end
