module Privy
  module Models
    type solana_system_program_instruction_condition_field =
      :instructionName
      | :"Transfer.from"
      | :"Transfer.to"
      | :"Transfer.lamports"

    module SolanaSystemProgramInstructionConditionField
      extend Privy::Internal::Type::Enum

      INSTRUCTION_NAME: :instructionName
      TRANSFER_FROM: :"Transfer.from"
      TRANSFER_TO: :"Transfer.to"
      TRANSFER_LAMPORTS: :"Transfer.lamports"

      def self?.values: -> ::Array[Privy::Models::solana_system_program_instruction_condition_field]
    end
  end
end
