module Privy
  module Models
    type solana_system_program_instruction_condition =
      {
        field: Privy::Models::SolanaSystemProgramInstructionCondition::field,
        field_source: Privy::Models::SolanaSystemProgramInstructionCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      }

    class SolanaSystemProgramInstructionCondition < Privy::Internal::Type::BaseModel
      attr_accessor field: Privy::Models::SolanaSystemProgramInstructionCondition::field

      attr_accessor field_source: Privy::Models::SolanaSystemProgramInstructionCondition::field_source

      attr_accessor operator: Privy::Models::condition_operator

      attr_accessor value: Privy::Models::condition_value

      def initialize: (
        field: Privy::Models::SolanaSystemProgramInstructionCondition::field,
        field_source: Privy::Models::SolanaSystemProgramInstructionCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      ) -> void

      def to_hash: -> {
        field: Privy::Models::SolanaSystemProgramInstructionCondition::field,
        field_source: Privy::Models::SolanaSystemProgramInstructionCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      }

      type field =
        :instructionName
        | :"Transfer.from"
        | :"Transfer.to"
        | :"Transfer.lamports"

      module Field
        extend Privy::Internal::Type::Enum

        INSTRUCTION_NAME: :instructionName
        TRANSFER_FROM: :"Transfer.from"
        TRANSFER_TO: :"Transfer.to"
        TRANSFER_LAMPORTS: :"Transfer.lamports"

        def self?.values: -> ::Array[Privy::Models::SolanaSystemProgramInstructionCondition::field]
      end

      type field_source = :solana_system_program_instruction

      module FieldSource
        extend Privy::Internal::Type::Enum

        SOLANA_SYSTEM_PROGRAM_INSTRUCTION: :solana_system_program_instruction

        def self?.values: -> ::Array[Privy::Models::SolanaSystemProgramInstructionCondition::field_source]
      end
    end
  end
end
