module Privy
  module Models
    type solana_sign_and_send_transaction_rpc_input_params =
      {
        encoding: Privy::Models::SolanaSignAndSendTransactionRpcInputParams::encoding,
        transaction: String
      }

    class SolanaSignAndSendTransactionRpcInputParams < Privy::Internal::Type::BaseModel
      attr_accessor encoding: Privy::Models::SolanaSignAndSendTransactionRpcInputParams::encoding

      attr_accessor transaction: String

      def initialize: (
        encoding: Privy::Models::SolanaSignAndSendTransactionRpcInputParams::encoding,
        transaction: String
      ) -> void

      def to_hash: -> {
        encoding: Privy::Models::SolanaSignAndSendTransactionRpcInputParams::encoding,
        transaction: String
      }

      type encoding = :base64

      module Encoding
        extend Privy::Internal::Type::Enum

        BASE64: :base64

        def self?.values: -> ::Array[Privy::Models::SolanaSignAndSendTransactionRpcInputParams::encoding]
      end
    end
  end
end
