module Privy
  module Models
    type spark_transfer_tokens_rpc_response_data = { id: String }

    class SparkTransferTokensRpcResponseData < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      def initialize: (id: String) -> void

      def to_hash: -> { id: String }
    end
  end
end
