module Privy
  module Models
    type spark_withdraw_rpc_input =
      {
        method_: Privy::Models::SparkWithdrawRpcInput::method_,
        params: Privy::SparkWithdrawRpcInputParams,
        network: Privy::Models::spark_network
      }

    class SparkWithdrawRpcInput < Privy::Internal::Type::BaseModel
      attr_accessor method_: Privy::Models::SparkWithdrawRpcInput::method_

      attr_accessor params: Privy::SparkWithdrawRpcInputParams

      attr_reader network: Privy::Models::spark_network?

      def network=: (
        Privy::Models::spark_network
      ) -> Privy::Models::spark_network

      def initialize: (
        method_: Privy::Models::SparkWithdrawRpcInput::method_,
        params: Privy::SparkWithdrawRpcInputParams,
        ?network: Privy::Models::spark_network
      ) -> void

      def to_hash: -> {
        method_: Privy::Models::SparkWithdrawRpcInput::method_,
        params: Privy::SparkWithdrawRpcInputParams,
        network: Privy::Models::spark_network
      }

      type method_ = :withdraw

      module Method
        extend Privy::Internal::Type::Enum

        WITHDRAW: :withdraw

        def self?.values: -> ::Array[Privy::Models::SparkWithdrawRpcInput::method_]
      end
    end
  end
end
