module Privy
  module Models
    type spark_get_withdrawal_fee_quote_rpc_response =
      {
        method_: Privy::Models::SparkGetWithdrawalFeeQuoteRpcResponse::method_,
        data: Privy::SparkCoopExitFeeQuote
      }

    class SparkGetWithdrawalFeeQuoteRpcResponse < Privy::Internal::Type::BaseModel
      attr_accessor method_: Privy::Models::SparkGetWithdrawalFeeQuoteRpcResponse::method_

      attr_reader data: Privy::SparkCoopExitFeeQuote?

      def data=: (Privy::SparkCoopExitFeeQuote) -> Privy::SparkCoopExitFeeQuote

      def initialize: (
        method_: Privy::Models::SparkGetWithdrawalFeeQuoteRpcResponse::method_,
        ?data: Privy::SparkCoopExitFeeQuote
      ) -> void

      def to_hash: -> {
        method_: Privy::Models::SparkGetWithdrawalFeeQuoteRpcResponse::method_,
        data: Privy::SparkCoopExitFeeQuote
      }

      type method_ = :getWithdrawalFeeQuote

      module Method
        extend Privy::Internal::Type::Enum

        GET_WITHDRAWAL_FEE_QUOTE: :getWithdrawalFeeQuote

        def self?.values: -> ::Array[Privy::Models::SparkGetWithdrawalFeeQuoteRpcResponse::method_]
      end
    end
  end
end
