module Privy
  module Models
    type spark_pay_lightning_invoice_rpc_input =
      {
        method_: Privy::Models::SparkPayLightningInvoiceRpcInput::method_,
        params: Privy::SparkPayLightningInvoiceRpcInputParams,
        network: Privy::Models::spark_network
      }

    class SparkPayLightningInvoiceRpcInput < Privy::Internal::Type::BaseModel
      attr_accessor method_: Privy::Models::SparkPayLightningInvoiceRpcInput::method_

      attr_accessor params: Privy::SparkPayLightningInvoiceRpcInputParams

      attr_reader network: Privy::Models::spark_network?

      def network=: (
        Privy::Models::spark_network
      ) -> Privy::Models::spark_network

      def initialize: (
        method_: Privy::Models::SparkPayLightningInvoiceRpcInput::method_,
        params: Privy::SparkPayLightningInvoiceRpcInputParams,
        ?network: Privy::Models::spark_network
      ) -> void

      def to_hash: -> {
        method_: Privy::Models::SparkPayLightningInvoiceRpcInput::method_,
        params: Privy::SparkPayLightningInvoiceRpcInputParams,
        network: Privy::Models::spark_network
      }

      type method_ = :payLightningInvoice

      module Method
        extend Privy::Internal::Type::Enum

        PAY_LIGHTNING_INVOICE: :payLightningInvoice

        def self?.values: -> ::Array[Privy::Models::SparkPayLightningInvoiceRpcInput::method_]
      end
    end
  end
end
