module Privy
  module Models
    type spark_get_claim_static_deposit_quote_rpc_input =
      {
        method_: Privy::Models::SparkGetClaimStaticDepositQuoteRpcInput::method_,
        params: Privy::SparkGetClaimStaticDepositQuoteRpcInputParams,
        network: Privy::Models::spark_network
      }

    class SparkGetClaimStaticDepositQuoteRpcInput < Privy::Internal::Type::BaseModel
      attr_accessor method_: Privy::Models::SparkGetClaimStaticDepositQuoteRpcInput::method_

      attr_accessor params: Privy::SparkGetClaimStaticDepositQuoteRpcInputParams

      attr_reader network: Privy::Models::spark_network?

      def network=: (
        Privy::Models::spark_network
      ) -> Privy::Models::spark_network

      def initialize: (
        method_: Privy::Models::SparkGetClaimStaticDepositQuoteRpcInput::method_,
        params: Privy::SparkGetClaimStaticDepositQuoteRpcInputParams,
        ?network: Privy::Models::spark_network
      ) -> void

      def to_hash: -> {
        method_: Privy::Models::SparkGetClaimStaticDepositQuoteRpcInput::method_,
        params: Privy::SparkGetClaimStaticDepositQuoteRpcInputParams,
        network: Privy::Models::spark_network
      }

      type method_ = :getClaimStaticDepositQuote

      module Method
        extend Privy::Internal::Type::Enum

        GET_CLAIM_STATIC_DEPOSIT_QUOTE: :getClaimStaticDepositQuote

        def self?.values: -> ::Array[Privy::Models::SparkGetClaimStaticDepositQuoteRpcInput::method_]
      end
    end
  end
end
