module Privy
  module Models
    type spark_get_claim_static_deposit_quote_rpc_input_params =
      { transaction_id: String, output_index: Float }

    class SparkGetClaimStaticDepositQuoteRpcInputParams < Privy::Internal::Type::BaseModel
      attr_accessor transaction_id: String

      attr_reader output_index: Float?

      def output_index=: (Float) -> Float

      def initialize: (transaction_id: String, ?output_index: Float) -> void

      def to_hash: -> { transaction_id: String, output_index: Float }
    end
  end
end
