module Privy
  module Models
    type stripe_onramp_checkout_input = { auth_intent_id: String }

    class StripeOnrampCheckoutInput < Privy::Internal::Type::BaseModel
      attr_accessor auth_intent_id: String

      def initialize: (auth_intent_id: String) -> void

      def to_hash: -> { auth_intent_id: String }
    end
  end
end
