module Privy
  module Models
    type stripe_crypto_customer_expired =
      {
        crypto_customer_id: String,
        status: Privy::Models::StripeCryptoCustomerExpired::status
      }

    class StripeCryptoCustomerExpired < Privy::Internal::Type::BaseModel
      attr_accessor crypto_customer_id: String

      attr_accessor status: Privy::Models::StripeCryptoCustomerExpired::status

      def initialize: (
        crypto_customer_id: String,
        status: Privy::Models::StripeCryptoCustomerExpired::status
      ) -> void

      def to_hash: -> {
        crypto_customer_id: String,
        status: Privy::Models::StripeCryptoCustomerExpired::status
      }

      type status = :expired

      module Status
        extend Privy::Internal::Type::Enum

        EXPIRED: :expired

        def self?.values: -> ::Array[Privy::Models::StripeCryptoCustomerExpired::status]
      end
    end
  end
end
