module Privy
  module Models
    type stripe_verification = { name: String, status: String }

    class StripeVerification < Privy::Internal::Type::BaseModel
      attr_accessor name: String

      attr_accessor status: String

      def initialize: (name: String, status: String) -> void

      def to_hash: -> { name: String, status: String }
    end
  end
end
