module Privy
  module Models
    type stripe_quote = { expires_at: Float }

    class StripeQuote < Privy::Internal::Type::BaseModel
      attr_accessor expires_at: Float

      def initialize: (expires_at: Float) -> void

      def to_hash: -> { expires_at: Float }
    end
  end
end
