module Privy
  module Models
    type success_response = { success: bool }

    class SuccessResponse < Privy::Internal::Type::BaseModel
      attr_accessor success: bool

      def initialize: (success: bool) -> void

      def to_hash: -> { success: bool }
    end
  end
end
