module Privy
  module Models
    type swap_request_body =
      {
        base_amount: String,
        destination: Privy::SwapDestination,
        source: Privy::SwapSource,
        amount_type: Privy::Models::amount_type,
        fee_configuration: Privy::FeeConfiguration,
        slippage_bps: Float
      }

    class SwapRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor base_amount: String

      attr_accessor destination: Privy::SwapDestination

      attr_accessor source: Privy::SwapSource

      attr_reader amount_type: Privy::Models::amount_type?

      def amount_type=: (
        Privy::Models::amount_type
      ) -> Privy::Models::amount_type

      attr_reader fee_configuration: Privy::FeeConfiguration?

      def fee_configuration=: (
        Privy::FeeConfiguration
      ) -> Privy::FeeConfiguration

      attr_reader slippage_bps: Float?

      def slippage_bps=: (Float) -> Float

      def initialize: (
        base_amount: String,
        destination: Privy::SwapDestination,
        source: Privy::SwapSource,
        ?amount_type: Privy::Models::amount_type,
        ?fee_configuration: Privy::FeeConfiguration,
        ?slippage_bps: Float
      ) -> void

      def to_hash: -> {
        base_amount: String,
        destination: Privy::SwapDestination,
        source: Privy::SwapSource,
        amount_type: Privy::Models::amount_type,
        fee_configuration: Privy::FeeConfiguration,
        slippage_bps: Float
      }
    end
  end
end
