module Privy
  module Models
    type swap_destination =
      { asset_address: String, :caip2 => String, destination_address: String }

    class SwapDestination < Privy::Internal::Type::BaseModel
      attr_accessor asset_address: String

      attr_reader caip2: String?

      def caip2=: (String) -> String

      attr_reader destination_address: String?

      def destination_address=: (String) -> String

      def initialize: (
        asset_address: String,
        ?caip2: String,
        ?destination_address: String
      ) -> void

      def to_hash: -> {
        asset_address: String,
        :caip2 => String,
        destination_address: String
      }
    end
  end
end
