module Privy
  module Models
    type swap_action_response =
      {
        id: String,
        :caip2 => String,
        created_at: Time,
        input_amount: String?,
        input_token: String,
        output_amount: String?,
        output_token: String,
        status: Privy::Models::wallet_action_status,
        type: Privy::Models::SwapActionResponse::type_,
        wallet_id: String,
        :destination_caip2 => String,
        estimated_fees: ::Array[Privy::Models::fee_line_item]?,
        estimated_gas: Privy::SwapActionResponse::EstimatedGas,
        failure_reason: Privy::FailureReason,
        fees: ::Array[Privy::Models::fee_line_item]?,
        gas: Privy::SwapActionResponse::Gas,
        steps: ::Array[Privy::Models::wallet_action_step]
      }

    class SwapActionResponse < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor caip2: String

      attr_accessor created_at: Time

      attr_accessor input_amount: String?

      attr_accessor input_token: String

      attr_accessor output_amount: String?

      attr_accessor output_token: String

      attr_accessor status: Privy::Models::wallet_action_status

      attr_accessor type: Privy::Models::SwapActionResponse::type_

      attr_accessor wallet_id: String

      attr_reader destination_caip2: String?

      def destination_caip2=: (String) -> String

      attr_accessor estimated_fees: ::Array[Privy::Models::fee_line_item]?

      attr_reader estimated_gas: Privy::SwapActionResponse::EstimatedGas?

      def estimated_gas=: (
        Privy::SwapActionResponse::EstimatedGas
      ) -> Privy::SwapActionResponse::EstimatedGas

      attr_reader failure_reason: Privy::FailureReason?

      def failure_reason=: (Privy::FailureReason) -> Privy::FailureReason

      attr_accessor fees: ::Array[Privy::Models::fee_line_item]?

      attr_reader gas: Privy::SwapActionResponse::Gas?

      def gas=: (
        Privy::SwapActionResponse::Gas
      ) -> Privy::SwapActionResponse::Gas

      attr_reader steps: ::Array[Privy::Models::wallet_action_step]?

      def steps=: (
        ::Array[Privy::Models::wallet_action_step]
      ) -> ::Array[Privy::Models::wallet_action_step]

      def initialize: (
        id: String,
        caip2: String,
        created_at: Time,
        input_amount: String?,
        input_token: String,
        output_amount: String?,
        output_token: String,
        status: Privy::Models::wallet_action_status,
        type: Privy::Models::SwapActionResponse::type_,
        wallet_id: String,
        ?destination_caip2: String,
        ?estimated_fees: ::Array[Privy::Models::fee_line_item]?,
        ?estimated_gas: Privy::SwapActionResponse::EstimatedGas,
        ?failure_reason: Privy::FailureReason,
        ?fees: ::Array[Privy::Models::fee_line_item]?,
        ?gas: Privy::SwapActionResponse::Gas,
        ?steps: ::Array[Privy::Models::wallet_action_step]
      ) -> void

      def to_hash: -> {
        id: String,
        :caip2 => String,
        created_at: Time,
        input_amount: String?,
        input_token: String,
        output_amount: String?,
        output_token: String,
        status: Privy::Models::wallet_action_status,
        type: Privy::Models::SwapActionResponse::type_,
        wallet_id: String,
        :destination_caip2 => String,
        estimated_fees: ::Array[Privy::Models::fee_line_item]?,
        estimated_gas: Privy::SwapActionResponse::EstimatedGas,
        failure_reason: Privy::FailureReason,
        fees: ::Array[Privy::Models::fee_line_item]?,
        gas: Privy::SwapActionResponse::Gas,
        steps: ::Array[Privy::Models::wallet_action_step]
      }

      type type_ = :swap

      module Type
        extend Privy::Internal::Type::Enum

        SWAP: :swap

        def self?.values: -> ::Array[Privy::Models::SwapActionResponse::type_]
      end

      type estimated_gas = {  }

      class EstimatedGas < Privy::Models::Gas
        def initialize: -> void

        def to_hash: -> {  }
      end

      type gas = {  }

      class Gas < Privy::Models::Gas
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
