module Privy
  module Models
    type telegram_unlink_request_body = { telegram_user_id: String }

    class TelegramUnlinkRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor telegram_user_id: String

      def initialize: (telegram_user_id: String) -> void

      def to_hash: -> { telegram_user_id: String }
    end
  end
end
