module Privy
  module Models
    type transaction_execution_reverted_webhook_payload =
      {
        :caip2 => String,
        transaction_hash: String,
        transaction_id: String,
        type: Privy::Models::TransactionExecutionRevertedWebhookPayload::type_,
        wallet_id: String,
        reference_id: String?
      }

    class TransactionExecutionRevertedWebhookPayload < Privy::Internal::Type::BaseModel
      attr_accessor caip2: String

      attr_accessor transaction_hash: String

      attr_accessor transaction_id: String

      attr_accessor type: Privy::Models::TransactionExecutionRevertedWebhookPayload::type_

      attr_accessor wallet_id: String

      attr_accessor reference_id: String?

      def initialize: (
        caip2: String,
        transaction_hash: String,
        transaction_id: String,
        type: Privy::Models::TransactionExecutionRevertedWebhookPayload::type_,
        wallet_id: String,
        ?reference_id: String?
      ) -> void

      def to_hash: -> {
        :caip2 => String,
        transaction_hash: String,
        transaction_id: String,
        type: Privy::Models::TransactionExecutionRevertedWebhookPayload::type_,
        wallet_id: String,
        reference_id: String?
      }

      type type_ = :"transaction.execution_reverted"

      module Type
        extend Privy::Internal::Type::Enum

        TRANSACTION_EXECUTION_REVERTED: :"transaction.execution_reverted"

        def self?.values: -> ::Array[Privy::Models::TransactionExecutionRevertedWebhookPayload::type_]
      end
    end
  end
end
