module Privy
  module Models
    type transaction_still_pending_webhook_payload =
      {
        :caip2 => String,
        transaction_hash: String,
        transaction_id: String,
        transaction_request: Privy::UnsignedStandardEthereumTransaction,
        type: Privy::Models::TransactionStillPendingWebhookPayload::type_,
        wallet_id: String,
        reference_id: String?
      }

    class TransactionStillPendingWebhookPayload < Privy::Internal::Type::BaseModel
      attr_accessor caip2: String

      attr_accessor transaction_hash: String

      attr_accessor transaction_id: String

      attr_accessor transaction_request: Privy::UnsignedStandardEthereumTransaction

      attr_accessor type: Privy::Models::TransactionStillPendingWebhookPayload::type_

      attr_accessor wallet_id: String

      attr_accessor reference_id: String?

      def initialize: (
        caip2: String,
        transaction_hash: String,
        transaction_id: String,
        transaction_request: Privy::UnsignedStandardEthereumTransaction,
        type: Privy::Models::TransactionStillPendingWebhookPayload::type_,
        wallet_id: String,
        ?reference_id: String?
      ) -> void

      def to_hash: -> {
        :caip2 => String,
        transaction_hash: String,
        transaction_id: String,
        transaction_request: Privy::UnsignedStandardEthereumTransaction,
        type: Privy::Models::TransactionStillPendingWebhookPayload::type_,
        wallet_id: String,
        reference_id: String?
      }

      type type_ = :"transaction.still_pending"

      module Type
        extend Privy::Internal::Type::Enum

        TRANSACTION_STILL_PENDING: :"transaction.still_pending"

        def self?.values: -> ::Array[Privy::Models::TransactionStillPendingWebhookPayload::type_]
      end
    end
  end
end
