module Privy
  module Models
    type transaction =
      {
        id: String,
        :caip2 => String,
        created_at: Float,
        status: Privy::Models::blockchain_transaction_status,
        transaction_hash: String?,
        wallet_id: String,
        reference_id: String?,
        sponsored: bool,
        user_operation_hash: String
      }

    class Transaction < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor caip2: String

      attr_accessor created_at: Float

      attr_accessor status: Privy::Models::blockchain_transaction_status

      attr_accessor transaction_hash: String?

      attr_accessor wallet_id: String

      attr_accessor reference_id: String?

      attr_reader sponsored: bool?

      def sponsored=: (bool) -> bool

      attr_reader user_operation_hash: String?

      def user_operation_hash=: (String) -> String

      def initialize: (
        id: String,
        caip2: String,
        created_at: Float,
        status: Privy::Models::blockchain_transaction_status,
        transaction_hash: String?,
        wallet_id: String,
        ?reference_id: String?,
        ?sponsored: bool,
        ?user_operation_hash: String
      ) -> void

      def to_hash: -> {
        id: String,
        :caip2 => String,
        created_at: Float,
        status: Privy::Models::blockchain_transaction_status,
        transaction_hash: String?,
        wallet_id: String,
        reference_id: String?,
        sponsored: bool,
        user_operation_hash: String
      }
    end
  end
end
