module Privy
  module Models
    type transfer_farcaster_input =
      {
        farcaster_embedded_address: String,
        farcaster_id: String,
        nonce: String
      }

    class TransferFarcasterInput < Privy::Internal::Type::BaseModel
      attr_accessor farcaster_embedded_address: String

      attr_accessor farcaster_id: String

      attr_accessor nonce: String

      def initialize: (
        farcaster_embedded_address: String,
        farcaster_id: String,
        nonce: String
      ) -> void

      def to_hash: -> {
        farcaster_embedded_address: String,
        farcaster_id: String,
        nonce: String
      }
    end
  end
end
