module Privy
  module Models
    type transfer_sent_transaction_detail =
      {
        asset: Privy::Models::TransferSentTransactionDetail::asset,
        chain: Privy::Models::wallet_asset_chain_name_input,
        display_values: ::Hash[Symbol, String],
        raw_value: String,
        raw_value_decimals: Float,
        recipient: String,
        recipient_privy_user_id: String?,
        sender: String,
        sender_privy_user_id: String?,
        type: Privy::Models::TransferSentTransactionDetail::type_
      }

    class TransferSentTransactionDetail < Privy::Internal::Type::BaseModel
      attr_accessor asset: Privy::Models::TransferSentTransactionDetail::asset

      attr_accessor chain: Privy::Models::wallet_asset_chain_name_input

      attr_accessor display_values: ::Hash[Symbol, String]

      attr_accessor raw_value: String

      attr_accessor raw_value_decimals: Float

      attr_accessor recipient: String

      attr_accessor recipient_privy_user_id: String?

      attr_accessor sender: String

      attr_accessor sender_privy_user_id: String?

      attr_accessor type: Privy::Models::TransferSentTransactionDetail::type_

      def initialize: (
        asset: Privy::Models::TransferSentTransactionDetail::asset,
        chain: Privy::Models::wallet_asset_chain_name_input,
        display_values: ::Hash[Symbol, String],
        raw_value: String,
        raw_value_decimals: Float,
        recipient: String,
        recipient_privy_user_id: String?,
        sender: String,
        sender_privy_user_id: String?,
        type: Privy::Models::TransferSentTransactionDetail::type_
      ) -> void

      def to_hash: -> {
        asset: Privy::Models::TransferSentTransactionDetail::asset,
        chain: Privy::Models::wallet_asset_chain_name_input,
        display_values: ::Hash[Symbol, String],
        raw_value: String,
        raw_value_decimals: Float,
        recipient: String,
        recipient_privy_user_id: String?,
        sender: String,
        sender_privy_user_id: String?,
        type: Privy::Models::TransferSentTransactionDetail::type_
      }

      type asset =
        :usdc
        | :"usdc.e"
        | :eth
        | :avax
        | :pol
        | :bnb
        | :usdt
        | :eurc
        | :usdb
        | :pathusd
        | :sol
        | :trx
        | String

      module Asset
        extend Privy::Internal::Type::Union

        def self?.variants: -> ::Array[Privy::Models::TransferSentTransactionDetail::asset]

        USDC: :usdc
        USDC_E: :"usdc.e"
        ETH: :eth
        AVAX: :avax
        POL: :pol
        BNB: :bnb
        USDT: :usdt
        EURC: :eurc
        USDB: :usdb
        PATHUSD: :pathusd
        SOL: :sol
        TRX: :trx
      end

      type type_ = :transfer_sent

      module Type
        extend Privy::Internal::Type::Enum

        TRANSFER_SENT: :transfer_sent

        def self?.values: -> ::Array[Privy::Models::TransferSentTransactionDetail::type_]
      end
    end
  end
end
