module Privy
  module Models
    type tron_transaction_condition_field =
      :"TransferContract.to_address"
      | :"TransferContract.amount"
      | :"TriggerSmartContract.contract_address"
      | :"TriggerSmartContract.call_value"
      | :"TriggerSmartContract.token_id"
      | :"TriggerSmartContract.call_token_value"

    module TronTransactionConditionField
      extend Privy::Internal::Type::Enum

      TRANSFER_CONTRACT_TO_ADDRESS: :"TransferContract.to_address"
      TRANSFER_CONTRACT_AMOUNT: :"TransferContract.amount"
      TRIGGER_SMART_CONTRACT_CONTRACT_ADDRESS: :"TriggerSmartContract.contract_address"
      TRIGGER_SMART_CONTRACT_CALL_VALUE: :"TriggerSmartContract.call_value"
      TRIGGER_SMART_CONTRACT_TOKEN_ID: :"TriggerSmartContract.token_id"
      TRIGGER_SMART_CONTRACT_CALL_TOKEN_VALUE: :"TriggerSmartContract.call_token_value"

      def self?.values: -> ::Array[Privy::Models::tron_transaction_condition_field]
    end
  end
end
