module Privy
  module Models
    type tron_transaction_condition =
      {
        field: Privy::Models::tron_transaction_condition_field,
        field_source: Privy::Models::TronTransactionCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      }

    class TronTransactionCondition < Privy::Internal::Type::BaseModel
      attr_accessor field: Privy::Models::tron_transaction_condition_field

      attr_accessor field_source: Privy::Models::TronTransactionCondition::field_source

      attr_accessor operator: Privy::Models::condition_operator

      attr_accessor value: Privy::Models::condition_value

      def initialize: (
        field: Privy::Models::tron_transaction_condition_field,
        field_source: Privy::Models::TronTransactionCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      ) -> void

      def to_hash: -> {
        field: Privy::Models::tron_transaction_condition_field,
        field_source: Privy::Models::TronTransactionCondition::field_source,
        operator: Privy::Models::condition_operator,
        value: Privy::Models::condition_value
      }

      type field_source = :tron_transaction

      module FieldSource
        extend Privy::Internal::Type::Enum

        TRON_TRANSACTION: :tron_transaction

        def self?.values: -> ::Array[Privy::Models::TronTransactionCondition::field_source]
      end
    end
  end
end
