module Privy
  module Models
    type tron_rpc_response =
      Privy::TronSignTransactionRpcResponse
      | Privy::TronSendTransactionRpcResponse

    module TronRpcResponse
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::tron_rpc_response]
    end
  end
end
