module Privy
  module Models
    type tron_sign_transaction_rpc_input_params =
      { raw_data: Privy::TronRawDataForSign }

    class TronSignTransactionRpcInputParams < Privy::Internal::Type::BaseModel
      attr_accessor raw_data: Privy::TronRawDataForSign

      def initialize: (raw_data: Privy::TronRawDataForSign) -> void

      def to_hash: -> { raw_data: Privy::TronRawDataForSign }
    end
  end
end
