module Privy
  module Models
    type tron_contract =
      Privy::TronTransferContract | Privy::TronTriggerSmartContract

    module TronContract
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::tron_contract]
    end
  end
end
