module Privy
  module Models
    type tvm_transaction_wallet_action_step =
      {
        :caip2 => String,
        status: Privy::Models::tvm_wallet_action_step_status,
        transaction_id: String?,
        type: Privy::Models::TvmTransactionWalletActionStep::type_,
        failure_reason: Privy::FailureReason
      }

    class TvmTransactionWalletActionStep < Privy::Internal::Type::BaseModel
      attr_accessor caip2: String

      attr_accessor status: Privy::Models::tvm_wallet_action_step_status

      attr_accessor transaction_id: String?

      attr_accessor type: Privy::Models::TvmTransactionWalletActionStep::type_

      attr_reader failure_reason: Privy::FailureReason?

      def failure_reason=: (Privy::FailureReason) -> Privy::FailureReason

      def initialize: (
        caip2: String,
        status: Privy::Models::tvm_wallet_action_step_status,
        transaction_id: String?,
        type: Privy::Models::TvmTransactionWalletActionStep::type_,
        ?failure_reason: Privy::FailureReason
      ) -> void

      def to_hash: -> {
        :caip2 => String,
        status: Privy::Models::tvm_wallet_action_step_status,
        transaction_id: String?,
        type: Privy::Models::TvmTransactionWalletActionStep::type_,
        failure_reason: Privy::FailureReason
      }

      type type_ = :tvm_transaction

      module Type
        extend Privy::Internal::Type::Enum

        TVM_TRANSACTION: :tvm_transaction

        def self?.values: -> ::Array[Privy::Models::TvmTransactionWalletActionStep::type_]
      end
    end
  end
end
