module Privy
  module Models
    type typed_data_types_input_params =
      ::Hash[Symbol, ::Array[Privy::TypedDataTypeFieldInput]]

    TypedDataTypesInputParams: Privy::Internal::Type::Converter
  end
end
