module Privy
  module Models
    type update_organization_secret_signing_key_input =
      { signing_public_key: String? }

    class UpdateOrganizationSecretSigningKeyInput < Privy::Models::OrganizationSecretIDInput
      def signing_public_key: -> String?

      def signing_public_key=: (String? _) -> String?

      def initialize: (signing_public_key: String?) -> void

      def to_hash: -> { signing_public_key: String? }
    end
  end
end
