module Privy
  module Models
    type usage_cross_chain_fee_recorded_webhook_payload =
      {
        amount_usd: String,
        recorded_at: Integer,
        source_id: String,
        source_type: Privy::Models::usage_source_type,
        type: Privy::Models::UsageCrossChainFeeRecordedWebhookPayload::type_
      }

    class UsageCrossChainFeeRecordedWebhookPayload < Privy::Internal::Type::BaseModel
      attr_accessor amount_usd: String

      attr_accessor recorded_at: Integer

      attr_accessor source_id: String

      attr_accessor source_type: Privy::Models::usage_source_type

      attr_accessor type: Privy::Models::UsageCrossChainFeeRecordedWebhookPayload::type_

      def initialize: (
        amount_usd: String,
        recorded_at: Integer,
        source_id: String,
        source_type: Privy::Models::usage_source_type,
        type: Privy::Models::UsageCrossChainFeeRecordedWebhookPayload::type_
      ) -> void

      def to_hash: -> {
        amount_usd: String,
        recorded_at: Integer,
        source_id: String,
        source_type: Privy::Models::usage_source_type,
        type: Privy::Models::UsageCrossChainFeeRecordedWebhookPayload::type_
      }

      type type_ = :"usage.cross_chain_fee.recorded"

      module Type
        extend Privy::Internal::Type::Enum

        USAGE_CROSS_CHAIN_FEE_RECORDED: :"usage.cross_chain_fee.recorded"

        def self?.values: -> ::Array[Privy::Models::UsageCrossChainFeeRecordedWebhookPayload::type_]
      end
    end
  end
end
