module Privy
  module Models
    type user_pregenerate_wallets_params =
      { user_id: String, wallets: ::Array[Privy::WalletCreationInput] }
      & Privy::Internal::Type::request_parameters

    class UserPregenerateWalletsParams < Privy::Internal::Type::BaseModel
      extend Privy::Internal::Type::RequestParameters::Converter
      include Privy::Internal::Type::RequestParameters

      attr_accessor user_id: String

      attr_accessor wallets: ::Array[Privy::WalletCreationInput]

      def initialize: (
        user_id: String,
        wallets: ::Array[Privy::WalletCreationInput],
        ?request_options: Privy::request_opts
      ) -> void

      def to_hash: -> {
        user_id: String,
        wallets: ::Array[Privy::WalletCreationInput],
        request_options: Privy::RequestOptions
      }
    end
  end
end
