module Privy
  module Models
    type user_kyc_updated_data =
      {
        capabilities: Privy::KyxCapabilities,
        endorsements: ::Array[Privy::KyxEndorsement],
        kyc: Privy::UserKYCUpdatedKYCData,
        status: String,
        tos: Privy::UserKYCUpdatedTosData,
        stripe_cardholder_id: String
      }

    class UserKYCUpdatedData < Privy::Internal::Type::BaseModel
      attr_accessor capabilities: Privy::KyxCapabilities

      attr_accessor endorsements: ::Array[Privy::KyxEndorsement]

      attr_accessor kyc: Privy::UserKYCUpdatedKYCData

      attr_accessor status: String

      attr_accessor tos: Privy::UserKYCUpdatedTosData

      attr_reader stripe_cardholder_id: String?

      def stripe_cardholder_id=: (String) -> String

      def initialize: (
        capabilities: Privy::KyxCapabilities,
        endorsements: ::Array[Privy::KyxEndorsement],
        kyc: Privy::UserKYCUpdatedKYCData,
        status: String,
        tos: Privy::UserKYCUpdatedTosData,
        ?stripe_cardholder_id: String
      ) -> void

      def to_hash: -> {
        capabilities: Privy::KyxCapabilities,
        endorsements: ::Array[Privy::KyxEndorsement],
        kyc: Privy::UserKYCUpdatedKYCData,
        status: String,
        tos: Privy::UserKYCUpdatedTosData,
        stripe_cardholder_id: String
      }
    end
  end
end
