module Privy
  module Models
    type user_updated_account_webhook_payload =
      {
        account: Privy::Models::linked_account,
        type: Privy::Models::UserUpdatedAccountWebhookPayload::type_,
        user: Privy::User
      }

    class UserUpdatedAccountWebhookPayload < Privy::Internal::Type::BaseModel
      attr_accessor account: Privy::Models::linked_account

      attr_accessor type: Privy::Models::UserUpdatedAccountWebhookPayload::type_

      attr_accessor user: Privy::User

      def initialize: (
        account: Privy::Models::linked_account,
        type: Privy::Models::UserUpdatedAccountWebhookPayload::type_,
        user: Privy::User
      ) -> void

      def to_hash: -> {
        account: Privy::Models::linked_account,
        type: Privy::Models::UserUpdatedAccountWebhookPayload::type_,
        user: Privy::User
      }

      type type_ = :"user.updated_account"

      module Type
        extend Privy::Internal::Type::Enum

        USER_UPDATED_ACCOUNT: :"user.updated_account"

        def self?.values: -> ::Array[Privy::Models::UserUpdatedAccountWebhookPayload::type_]
      end
    end
  end
end
