module Privy
  module Models
    type user_kyc_updated_data =
      {
        capabilities: Privy::KyxCapabilities,
        endorsements: ::Array[Privy::KyxEndorsement],
        kyc: Privy::UserKYCUpdatedKYCData,
        status: String,
        tos: Privy::UserKYCUpdatedTosData
      }

    class UserKYCUpdatedData < Privy::Internal::Type::BaseModel
      attr_accessor capabilities: Privy::KyxCapabilities

      attr_accessor endorsements: ::Array[Privy::KyxEndorsement]

      attr_accessor kyc: Privy::UserKYCUpdatedKYCData

      attr_accessor status: String

      attr_accessor tos: Privy::UserKYCUpdatedTosData

      def initialize: (
        capabilities: Privy::KyxCapabilities,
        endorsements: ::Array[Privy::KyxEndorsement],
        kyc: Privy::UserKYCUpdatedKYCData,
        status: String,
        tos: Privy::UserKYCUpdatedTosData
      ) -> void

      def to_hash: -> {
        capabilities: Privy::KyxCapabilities,
        endorsements: ::Array[Privy::KyxEndorsement],
        kyc: Privy::UserKYCUpdatedKYCData,
        status: String,
        tos: Privy::UserKYCUpdatedTosData
      }
    end
  end
end
