module Privy
  module Models
    type wallet_export_request_body =
      {
        encryption_type: Privy::Models::hpke_encryption,
        recipient_public_key: String,
        export_seed_phrase: bool
      }

    class WalletExportRequestBody < Privy::Internal::Type::BaseModel
      attr_accessor encryption_type: Privy::Models::hpke_encryption

      attr_accessor recipient_public_key: String

      attr_reader export_seed_phrase: bool?

      def export_seed_phrase=: (bool) -> bool

      def initialize: (
        encryption_type: Privy::Models::hpke_encryption,
        recipient_public_key: String,
        ?export_seed_phrase: bool
      ) -> void

      def to_hash: -> {
        encryption_type: Privy::Models::hpke_encryption,
        recipient_public_key: String,
        export_seed_phrase: bool
      }
    end
  end
end
