module Privy
  module Models
    type wallet_automation_attachment_list_response =
      { data: ::Array[Privy::WalletAutomationAttachmentResponse] }

    class WalletAutomationAttachmentListResponse < Privy::Internal::Type::BaseModel
      attr_accessor data: ::Array[Privy::WalletAutomationAttachmentResponse]

      def initialize: (
        data: ::Array[Privy::WalletAutomationAttachmentResponse]
      ) -> void

      def to_hash: -> {
        data: ::Array[Privy::WalletAutomationAttachmentResponse]
      }
    end
  end
end
