module Privy
  module Models
    type wallet_deposit_account_deposit_completed_webhook_event =
      {
        data: Privy::DepositCompletedData,
        deposit_account_id: String,
        deposit_type: Privy::Models::WalletDepositAccountDepositCompletedWebhookEvent::deposit_type,
        environment: Privy::Models::environment,
        provider: Privy::Models::orchestration_provider,
        provider_deposit_id: String,
        type: Privy::Models::WalletDepositAccountDepositCompletedWebhookEvent::type_,
        wallet_id: String
      }

    class WalletDepositAccountDepositCompletedWebhookEvent < Privy::Internal::Type::BaseModel
      attr_accessor data: Privy::DepositCompletedData

      attr_accessor deposit_account_id: String

      attr_accessor deposit_type: Privy::Models::WalletDepositAccountDepositCompletedWebhookEvent::deposit_type

      attr_accessor environment: Privy::Models::environment

      attr_accessor provider: Privy::Models::orchestration_provider

      attr_accessor provider_deposit_id: String

      attr_accessor type: Privy::Models::WalletDepositAccountDepositCompletedWebhookEvent::type_

      attr_accessor wallet_id: String

      def initialize: (
        data: Privy::DepositCompletedData,
        deposit_account_id: String,
        deposit_type: Privy::Models::WalletDepositAccountDepositCompletedWebhookEvent::deposit_type,
        environment: Privy::Models::environment,
        provider: Privy::Models::orchestration_provider,
        provider_deposit_id: String,
        type: Privy::Models::WalletDepositAccountDepositCompletedWebhookEvent::type_,
        wallet_id: String
      ) -> void

      def to_hash: -> {
        data: Privy::DepositCompletedData,
        deposit_account_id: String,
        deposit_type: Privy::Models::WalletDepositAccountDepositCompletedWebhookEvent::deposit_type,
        environment: Privy::Models::environment,
        provider: Privy::Models::orchestration_provider,
        provider_deposit_id: String,
        type: Privy::Models::WalletDepositAccountDepositCompletedWebhookEvent::type_,
        wallet_id: String
      }

      type deposit_type = :fiat

      module DepositType
        extend Privy::Internal::Type::Enum

        FIAT: :fiat

        def self?.values: -> ::Array[Privy::Models::WalletDepositAccountDepositCompletedWebhookEvent::deposit_type]
      end

      type type_ = :"wallet.deposit_account.deposit_completed"

      module Type
        extend Privy::Internal::Type::Enum

        WALLET_DEPOSIT_ACCOUNT_DEPOSIT_COMPLETED: :"wallet.deposit_account.deposit_completed"

        def self?.values: -> ::Array[Privy::Models::WalletDepositAccountDepositCompletedWebhookEvent::type_]
      end
    end
  end
end
