module Privy
  module Models
    type wallet_action_earn_deposit_succeeded_webhook_payload =
      {
        action_type: Privy::Models::wallet_action_type,
        asset_address: String,
        :caip2 => String,
        completed_at: String,
        created_at: String,
        raw_amount: String,
        share_amount: String,
        status: Privy::Models::WalletActionEarnDepositSucceededWebhookPayload::status,
        steps: ::Array[Privy::Models::wallet_action_step],
        type: Privy::Models::WalletActionEarnDepositSucceededWebhookPayload::type_,
        vault_address: String,
        vault_id: String,
        wallet_action_id: String,
        wallet_id: String,
        amount: String,
        asset: String,
        decimals: Integer
      }

    class WalletActionEarnDepositSucceededWebhookPayload < Privy::Internal::Type::BaseModel
      attr_accessor action_type: Privy::Models::wallet_action_type

      attr_accessor asset_address: String

      attr_accessor caip2: String

      attr_accessor completed_at: String

      attr_accessor created_at: String

      attr_accessor raw_amount: String

      attr_accessor share_amount: String

      attr_accessor status: Privy::Models::WalletActionEarnDepositSucceededWebhookPayload::status

      attr_accessor steps: ::Array[Privy::Models::wallet_action_step]

      attr_accessor type: Privy::Models::WalletActionEarnDepositSucceededWebhookPayload::type_

      attr_accessor vault_address: String

      attr_accessor vault_id: String

      attr_accessor wallet_action_id: String

      attr_accessor wallet_id: String

      attr_reader amount: String?

      def amount=: (String) -> String

      attr_reader asset: String?

      def asset=: (String) -> String

      attr_reader decimals: Integer?

      def decimals=: (Integer) -> Integer

      def initialize: (
        action_type: Privy::Models::wallet_action_type,
        asset_address: String,
        caip2: String,
        completed_at: String,
        created_at: String,
        raw_amount: String,
        share_amount: String,
        status: Privy::Models::WalletActionEarnDepositSucceededWebhookPayload::status,
        steps: ::Array[Privy::Models::wallet_action_step],
        type: Privy::Models::WalletActionEarnDepositSucceededWebhookPayload::type_,
        vault_address: String,
        vault_id: String,
        wallet_action_id: String,
        wallet_id: String,
        ?amount: String,
        ?asset: String,
        ?decimals: Integer
      ) -> void

      def to_hash: -> {
        action_type: Privy::Models::wallet_action_type,
        asset_address: String,
        :caip2 => String,
        completed_at: String,
        created_at: String,
        raw_amount: String,
        share_amount: String,
        status: Privy::Models::WalletActionEarnDepositSucceededWebhookPayload::status,
        steps: ::Array[Privy::Models::wallet_action_step],
        type: Privy::Models::WalletActionEarnDepositSucceededWebhookPayload::type_,
        vault_address: String,
        vault_id: String,
        wallet_action_id: String,
        wallet_id: String,
        amount: String,
        asset: String,
        decimals: Integer
      }

      type status = :succeeded

      module Status
        extend Privy::Internal::Type::Enum

        SUCCEEDED: :succeeded

        def self?.values: -> ::Array[Privy::Models::WalletActionEarnDepositSucceededWebhookPayload::status]
      end

      type type_ = :"wallet_action.earn_deposit.succeeded"

      module Type
        extend Privy::Internal::Type::Enum

        WALLET_ACTION_EARN_DEPOSIT_SUCCEEDED: :"wallet_action.earn_deposit.succeeded"

        def self?.values: -> ::Array[Privy::Models::WalletActionEarnDepositSucceededWebhookPayload::type_]
      end
    end
  end
end
