module Privy
  module Models
    type wallet_export_response_body =
      {
        ciphertext: String,
        encapsulated_key: String,
        encryption_type: Privy::Models::hpke_encryption
      }

    class WalletExportResponseBody < Privy::Internal::Type::BaseModel
      attr_accessor ciphertext: String

      attr_accessor encapsulated_key: String

      attr_accessor encryption_type: Privy::Models::hpke_encryption

      def initialize: (
        ciphertext: String,
        encapsulated_key: String,
        encryption_type: Privy::Models::hpke_encryption
      ) -> void

      def to_hash: -> {
        ciphertext: String,
        encapsulated_key: String,
        encryption_type: Privy::Models::hpke_encryption
      }
    end
  end
end
