module Privy
  module Models
    type wallet_entity = { id: String, type: Privy::Models::wallet_entity_type }

    class WalletEntity < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor type: Privy::Models::wallet_entity_type

      def initialize: (
        id: String,
        type: Privy::Models::wallet_entity_type
      ) -> void

      def to_hash: -> { id: String, type: Privy::Models::wallet_entity_type }
    end
  end
end
