module Privy
  module Models
    type wallet_creation_additional_signer_item =
      { signer_id: String, override_policy_ids: ::Array[String] }

    class WalletCreationAdditionalSignerItem < Privy::Internal::Type::BaseModel
      attr_accessor signer_id: String

      attr_reader override_policy_ids: ::Array[String]?

      def override_policy_ids=: (::Array[String]) -> ::Array[String]

      def initialize: (
        signer_id: String,
        ?override_policy_ids: ::Array[String]
      ) -> void

      def to_hash: -> {
        signer_id: String,
        override_policy_ids: ::Array[String]
      }
    end
  end
end
