module Privy
  module Models
    type wallet_create_params =
      {
        chain_type: Privy::Models::wallet_chain_type,
        additional_signers: Privy::Models::additional_signer_input,
        display_name: String,
        external_id: String,
        owner: Privy::Models::owner_input?,
        owner_id: String?,
        policy_ids: Privy::Models::policy_input,
        privy_idempotency_key: String
      }
      & Privy::Internal::Type::request_parameters

    class WalletCreateParams < Privy::Internal::Type::BaseModel
      extend Privy::Internal::Type::RequestParameters::Converter
      include Privy::Internal::Type::RequestParameters

      attr_accessor chain_type: Privy::Models::wallet_chain_type

      attr_reader additional_signers: Privy::Models::additional_signer_input?

      def additional_signers=: (
        Privy::Models::additional_signer_input
      ) -> Privy::Models::additional_signer_input

      attr_reader display_name: String?

      def display_name=: (String) -> String

      attr_reader external_id: String?

      def external_id=: (String) -> String

      attr_accessor owner: Privy::Models::owner_input?

      attr_accessor owner_id: String?

      attr_reader policy_ids: Privy::Models::policy_input?

      def policy_ids=: (
        Privy::Models::policy_input
      ) -> Privy::Models::policy_input

      attr_reader privy_idempotency_key: String?

      def privy_idempotency_key=: (String) -> String

      def initialize: (
        chain_type: Privy::Models::wallet_chain_type,
        ?additional_signers: Privy::Models::additional_signer_input,
        ?display_name: String,
        ?external_id: String,
        ?owner: Privy::Models::owner_input?,
        ?owner_id: String?,
        ?policy_ids: Privy::Models::policy_input,
        ?privy_idempotency_key: String,
        ?request_options: Privy::request_opts
      ) -> void

      def to_hash: -> {
        chain_type: Privy::Models::wallet_chain_type,
        additional_signers: Privy::Models::additional_signer_input,
        display_name: String,
        external_id: String,
        owner: Privy::Models::owner_input?,
        owner_id: String?,
        policy_ids: Privy::Models::policy_input,
        privy_idempotency_key: String,
        request_options: Privy::RequestOptions
      }
    end
  end
end
