module Privy
  module Models
    type wallet_automation_execution_list_response =
      {
        data: ::Array[Privy::WalletAutomationExecutionResponse],
        next_cursor: String?
      }

    class WalletAutomationExecutionListResponse < Privy::Internal::Type::BaseModel
      attr_accessor data: ::Array[Privy::WalletAutomationExecutionResponse]

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[Privy::WalletAutomationExecutionResponse],
        next_cursor: String?
      ) -> void

      def to_hash: -> {
        data: ::Array[Privy::WalletAutomationExecutionResponse],
        next_cursor: String?
      }
    end
  end
end
