module Privy
  module Models
    type wallet_authenticate_bound_request_body =
      Privy::WalletAuthenticateBoundEncryptedRequestBody
      | Privy::WalletAuthenticateBoundUnencryptedRequestBody

    module WalletAuthenticateBoundRequestBody
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::wallet_authenticate_bound_request_body]
    end
  end
end
