module Privy
  module Models
    type wallet_action_swap_succeeded_webhook_payload =
      {
        action_type: Privy::Models::wallet_action_type,
        :caip2 => String,
        completed_at: String,
        created_at: String,
        input_amount: String?,
        input_token: String,
        output_amount: String?,
        output_token: String,
        status: Privy::Models::WalletActionSwapSucceededWebhookPayload::status,
        steps: ::Array[Privy::Models::wallet_action_step],
        type: Privy::Models::WalletActionSwapSucceededWebhookPayload::type_,
        wallet_action_id: String,
        wallet_id: String
      }

    class WalletActionSwapSucceededWebhookPayload < Privy::Internal::Type::BaseModel
      attr_accessor action_type: Privy::Models::wallet_action_type

      attr_accessor caip2: String

      attr_accessor completed_at: String

      attr_accessor created_at: String

      attr_accessor input_amount: String?

      attr_accessor input_token: String

      attr_accessor output_amount: String?

      attr_accessor output_token: String

      attr_accessor status: Privy::Models::WalletActionSwapSucceededWebhookPayload::status

      attr_accessor steps: ::Array[Privy::Models::wallet_action_step]

      attr_accessor type: Privy::Models::WalletActionSwapSucceededWebhookPayload::type_

      attr_accessor wallet_action_id: String

      attr_accessor wallet_id: String

      def initialize: (
        action_type: Privy::Models::wallet_action_type,
        caip2: String,
        completed_at: String,
        created_at: String,
        input_amount: String?,
        input_token: String,
        output_amount: String?,
        output_token: String,
        status: Privy::Models::WalletActionSwapSucceededWebhookPayload::status,
        steps: ::Array[Privy::Models::wallet_action_step],
        type: Privy::Models::WalletActionSwapSucceededWebhookPayload::type_,
        wallet_action_id: String,
        wallet_id: String
      ) -> void

      def to_hash: -> {
        action_type: Privy::Models::wallet_action_type,
        :caip2 => String,
        completed_at: String,
        created_at: String,
        input_amount: String?,
        input_token: String,
        output_amount: String?,
        output_token: String,
        status: Privy::Models::WalletActionSwapSucceededWebhookPayload::status,
        steps: ::Array[Privy::Models::wallet_action_step],
        type: Privy::Models::WalletActionSwapSucceededWebhookPayload::type_,
        wallet_action_id: String,
        wallet_id: String
      }

      type status = :succeeded

      module Status
        extend Privy::Internal::Type::Enum

        SUCCEEDED: :succeeded

        def self?.values: -> ::Array[Privy::Models::WalletActionSwapSucceededWebhookPayload::status]
      end

      type type_ = :"wallet_action.swap.succeeded"

      module Type
        extend Privy::Internal::Type::Enum

        WALLET_ACTION_SWAP_SUCCEEDED: :"wallet_action.swap.succeeded"

        def self?.values: -> ::Array[Privy::Models::WalletActionSwapSucceededWebhookPayload::type_]
      end
    end
  end
end
