module Privy
  module Models
    type wallet_api_revoke_authorization_key_input = { id: String }

    class WalletAPIRevokeAuthorizationKeyInput < Privy::Internal::Type::BaseModel
      attr_accessor id: String

      def initialize: (id: String) -> void

      def to_hash: -> { id: String }
    end
  end
end
