module Privy
  module Models
    type wallet_action_type =
      :swap | :transfer | :earn_deposit | :earn_withdraw | :earn_incentive_claim

    module WalletActionType
      extend Privy::Internal::Type::Enum

      SWAP: :swap
      TRANSFER: :transfer
      EARN_DEPOSIT: :earn_deposit
      EARN_WITHDRAW: :earn_withdraw
      EARN_INCENTIVE_CLAIM: :earn_incentive_claim

      def self?.values: -> ::Array[Privy::Models::wallet_action_type]
    end
  end
end
