module Privy
  module Models
    type wallet_action_step =
      Privy::EvmTransactionWalletActionStep
      | Privy::EvmUserOperationWalletActionStep
      | Privy::SvmTransactionWalletActionStep
      | Privy::ExternalTransactionWalletActionStep

    module WalletActionStep
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::wallet_action_step]
    end
  end
end
