module Privy
  module Models
    type wallet_authorization_headers =
      {
        privy_app_id: String,
        privy_authorization_signature: String,
        privy_request_expiry: String
      }

    class WalletAuthorizationHeaders < Privy::Internal::Type::BaseModel
      attr_accessor privy_app_id: String

      attr_reader privy_authorization_signature: String?

      def privy_authorization_signature=: (String) -> String

      attr_reader privy_request_expiry: String?

      def privy_request_expiry=: (String) -> String

      def initialize: (
        privy_app_id: String,
        ?privy_authorization_signature: String,
        ?privy_request_expiry: String
      ) -> void

      def to_hash: -> {
        privy_app_id: String,
        privy_authorization_signature: String,
        privy_request_expiry: String
      }
    end
  end
end
