module Privy
  module Models
    type wallet_action_transfer_succeeded_webhook_payload =
      {
        action_type: Privy::Models::wallet_action_type,
        completed_at: String,
        created_at: String,
        destination_address: String,
        source_chain: String,
        status: Privy::Models::WalletActionTransferSucceededWebhookPayload::status,
        steps: ::Array[Privy::Models::wallet_action_step],
        type: Privy::Models::WalletActionTransferSucceededWebhookPayload::type_,
        wallet_action_id: String,
        wallet_id: String,
        source_amount: String,
        source_asset: String,
        source_asset_address: String,
        source_asset_decimals: Integer
      }

    class WalletActionTransferSucceededWebhookPayload < Privy::Internal::Type::BaseModel
      attr_accessor action_type: Privy::Models::wallet_action_type

      attr_accessor completed_at: String

      attr_accessor created_at: String

      attr_accessor destination_address: String

      attr_accessor source_chain: String

      attr_accessor status: Privy::Models::WalletActionTransferSucceededWebhookPayload::status

      attr_accessor steps: ::Array[Privy::Models::wallet_action_step]

      attr_accessor type: Privy::Models::WalletActionTransferSucceededWebhookPayload::type_

      attr_accessor wallet_action_id: String

      attr_accessor wallet_id: String

      attr_reader source_amount: String?

      def source_amount=: (String) -> String

      attr_reader source_asset: String?

      def source_asset=: (String) -> String

      attr_reader source_asset_address: String?

      def source_asset_address=: (String) -> String

      attr_reader source_asset_decimals: Integer?

      def source_asset_decimals=: (Integer) -> Integer

      def initialize: (
        action_type: Privy::Models::wallet_action_type,
        completed_at: String,
        created_at: String,
        destination_address: String,
        source_chain: String,
        status: Privy::Models::WalletActionTransferSucceededWebhookPayload::status,
        steps: ::Array[Privy::Models::wallet_action_step],
        type: Privy::Models::WalletActionTransferSucceededWebhookPayload::type_,
        wallet_action_id: String,
        wallet_id: String,
        ?source_amount: String,
        ?source_asset: String,
        ?source_asset_address: String,
        ?source_asset_decimals: Integer
      ) -> void

      def to_hash: -> {
        action_type: Privy::Models::wallet_action_type,
        completed_at: String,
        created_at: String,
        destination_address: String,
        source_chain: String,
        status: Privy::Models::WalletActionTransferSucceededWebhookPayload::status,
        steps: ::Array[Privy::Models::wallet_action_step],
        type: Privy::Models::WalletActionTransferSucceededWebhookPayload::type_,
        wallet_action_id: String,
        wallet_id: String,
        source_amount: String,
        source_asset: String,
        source_asset_address: String,
        source_asset_decimals: Integer
      }

      type status = :succeeded

      module Status
        extend Privy::Internal::Type::Enum

        SUCCEEDED: :succeeded

        def self?.values: -> ::Array[Privy::Models::WalletActionTransferSucceededWebhookPayload::status]
      end

      type type_ = :"wallet_action.transfer.succeeded"

      module Type
        extend Privy::Internal::Type::Enum

        WALLET_ACTION_TRANSFER_SUCCEEDED: :"wallet_action.transfer.succeeded"

        def self?.values: -> ::Array[Privy::Models::WalletActionTransferSucceededWebhookPayload::type_]
      end
    end
  end
end
