module Privy
  module Models
    type wallet_ethereum_asset =
      :usdc | :"usdc.e" | :eth | :avax | :pol | :usdt | :eurc | :usdb

    module WalletEthereumAsset
      extend Privy::Internal::Type::Enum

      USDC: :usdc
      USDC_E: :"usdc.e"
      ETH: :eth
      AVAX: :avax
      POL: :pol
      USDT: :usdt
      EURC: :eurc
      USDB: :usdb

      def self?.values: -> ::Array[Privy::Models::wallet_ethereum_asset]
    end
  end
end
