module Privy
  module Models
    type wallet_additional_signer_item =
      { signer_id: String, override_policy_ids: Privy::Models::policy_input }

    class WalletAdditionalSignerItem < Privy::Internal::Type::BaseModel
      attr_accessor signer_id: String

      attr_reader override_policy_ids: Privy::Models::policy_input?

      def override_policy_ids=: (
        Privy::Models::policy_input
      ) -> Privy::Models::policy_input

      def initialize: (
        signer_id: String,
        ?override_policy_ids: Privy::Models::policy_input
      ) -> void

      def to_hash: -> {
        signer_id: String,
        override_policy_ids: Privy::Models::policy_input
      }
    end
  end
end
