module Privy
  module Models
    type wallet_archive_params =
      { wallet_id: String } & Privy::Internal::Type::request_parameters

    class WalletArchiveParams < Privy::Internal::Type::BaseModel
      extend Privy::Internal::Type::RequestParameters::Converter
      include Privy::Internal::Type::RequestParameters

      attr_accessor wallet_id: String

      def initialize: (
        wallet_id: String,
        ?request_options: Privy::request_opts
      ) -> void

      def to_hash: -> {
        wallet_id: String,
        request_options: Privy::RequestOptions
      }
    end
  end
end
