module Privy
  module Models
    type wallet_update_request_body =
      {
        additional_signers: Privy::Models::additional_signer_input,
        display_name: String?,
        owner: Privy::Models::owner_input?,
        owner_id: String?,
        policy_ids: ::Array[String]
      }

    class WalletUpdateRequestBody < Privy::Internal::Type::BaseModel
      attr_reader additional_signers: Privy::Models::additional_signer_input?

      def additional_signers=: (
        Privy::Models::additional_signer_input
      ) -> Privy::Models::additional_signer_input

      attr_accessor display_name: String?

      attr_accessor owner: Privy::Models::owner_input?

      attr_accessor owner_id: String?

      attr_reader policy_ids: ::Array[String]?

      def policy_ids=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?additional_signers: Privy::Models::additional_signer_input,
        ?display_name: String?,
        ?owner: Privy::Models::owner_input?,
        ?owner_id: String?,
        ?policy_ids: ::Array[String]
      ) -> void

      def to_hash: -> {
        additional_signers: Privy::Models::additional_signer_input,
        display_name: String?,
        owner: Privy::Models::owner_input?,
        owner_id: String?,
        policy_ids: ::Array[String]
      }
    end
  end
end
