module Privy
  module Models
    type wallet_import_supported_chains =
      :ethereum | :solana | :stellar | :tron | :sui | :aptos | :xrpl

    module WalletImportSupportedChains
      extend Privy::Internal::Type::Enum

      ETHEREUM: :ethereum
      SOLANA: :solana
      STELLAR: :stellar
      TRON: :tron
      SUI: :sui
      APTOS: :aptos
      XRPL: :xrpl

      def self?.values: -> ::Array[Privy::Models::wallet_import_supported_chains]
    end
  end
end
