module Privy
  module Models
    type wallet_authenticate_with_jwt_response =
      Privy::EncryptedWalletAuthenticateResponse
      | Privy::RawWalletAuthenticateResponse

    module WalletAuthenticateWithJwtResponse
      extend Privy::Internal::Type::Union

      def self?.variants: -> ::Array[Privy::Models::wallet_authenticate_with_jwt_response]
    end
  end
end
