module Privy
  module Models
    type wallet_asset_chain_name_input =
      :ethereum
      | :arbitrum
      | :avalanche
      | :base
      | :tempo
      | :linea
      | :optimism
      | :polygon
      | :solana
      | :zksync_era
      | :sepolia
      | :arbitrum_sepolia
      | :avalanche_fuji
      | :base_sepolia
      | :linea_testnet
      | :optimism_sepolia
      | :polygon_amoy
      | :solana_devnet
      | :solana_testnet

    module WalletAssetChainNameInput
      extend Privy::Internal::Type::Enum

      ETHEREUM: :ethereum
      ARBITRUM: :arbitrum
      AVALANCHE: :avalanche
      BASE: :base
      TEMPO: :tempo
      LINEA: :linea
      OPTIMISM: :optimism
      POLYGON: :polygon
      SOLANA: :solana
      ZKSYNC_ERA: :zksync_era
      SEPOLIA: :sepolia
      ARBITRUM_SEPOLIA: :arbitrum_sepolia
      AVALANCHE_FUJI: :avalanche_fuji
      BASE_SEPOLIA: :base_sepolia
      LINEA_TESTNET: :linea_testnet
      OPTIMISM_SEPOLIA: :optimism_sepolia
      POLYGON_AMOY: :polygon_amoy
      SOLANA_DEVNET: :solana_devnet
      SOLANA_TESTNET: :solana_testnet

      def self?.values: -> ::Array[Privy::Models::wallet_asset_chain_name_input]
    end
  end
end
