module Privy
  module Models
    type wallet_automation_update_params =
      { automation_id: String } & Privy::Internal::Type::request_parameters

    class WalletAutomationUpdateParams < Privy::Models::UpdateAutomationRequestBody
      extend Privy::Internal::Type::RequestParameters::Converter
      include Privy::Internal::Type::RequestParameters

      def automation_id: -> String

      def automation_id=: (String _) -> String

      def initialize: (
        automation_id: String,
        ?request_options: Privy::request_opts
      ) -> void

      def to_hash: -> {
        automation_id: String,
        request_options: Privy::RequestOptions
      }
    end
  end
end
