module Privy
  module Models
    type wallet_recovery_setup_webhook_payload =
      {
        method_: Privy::Models::wallet_recovery_setup_method,
        type: Privy::Models::WalletRecoverySetupWebhookPayload::type_,
        user_id: String,
        wallet_address: String,
        wallet_id: String
      }

    class WalletRecoverySetupWebhookPayload < Privy::Internal::Type::BaseModel
      attr_accessor method_: Privy::Models::wallet_recovery_setup_method

      attr_accessor type: Privy::Models::WalletRecoverySetupWebhookPayload::type_

      attr_accessor user_id: String

      attr_accessor wallet_address: String

      attr_accessor wallet_id: String

      def initialize: (
        method_: Privy::Models::wallet_recovery_setup_method,
        type: Privy::Models::WalletRecoverySetupWebhookPayload::type_,
        user_id: String,
        wallet_address: String,
        wallet_id: String
      ) -> void

      def to_hash: -> {
        method_: Privy::Models::wallet_recovery_setup_method,
        type: Privy::Models::WalletRecoverySetupWebhookPayload::type_,
        user_id: String,
        wallet_address: String,
        wallet_id: String
      }

      type type_ = :"wallet.recovery_setup"

      module Type
        extend Privy::Internal::Type::Enum

        WALLET_RECOVERY_SETUP: :"wallet.recovery_setup"

        def self?.values: -> ::Array[Privy::Models::WalletRecoverySetupWebhookPayload::type_]
      end
    end
  end
end
