module Privy
  module Models
    type webhook_unsafe_unwrap_params =
      {  } & Privy::Internal::Type::request_parameters

    class WebhookUnsafeUnwrapParams < Privy::Internal::Type::BaseModel
      extend Privy::Internal::Type::RequestParameters::Converter
      include Privy::Internal::Type::RequestParameters

      def initialize: (?request_options: Privy::request_opts) -> void

      def to_hash: -> { request_options: Privy::RequestOptions }
    end
  end
end
