module Privy
  module Models
    type xrpl_sign_transaction_rpc_response_data =
      {
        encoding: Privy::Models::XrplSignTransactionRpcResponseData::encoding,
        signed_transaction: String,
        txn_signature: String
      }

    class XrplSignTransactionRpcResponseData < Privy::Internal::Type::BaseModel
      attr_accessor encoding: Privy::Models::XrplSignTransactionRpcResponseData::encoding

      attr_accessor signed_transaction: String

      attr_accessor txn_signature: String

      def initialize: (
        encoding: Privy::Models::XrplSignTransactionRpcResponseData::encoding,
        signed_transaction: String,
        txn_signature: String
      ) -> void

      def to_hash: -> {
        encoding: Privy::Models::XrplSignTransactionRpcResponseData::encoding,
        signed_transaction: String,
        txn_signature: String
      }

      type encoding = :hex

      module Encoding
        extend Privy::Internal::Type::Enum

        HEX: :hex

        def self?.values: -> ::Array[Privy::Models::XrplSignTransactionRpcResponseData::encoding]
      end
    end
  end
end
