module Privy
  module Models
    module Users
      type kyc_initiate_tos_params =
        { user_id: String } & Privy::Internal::Type::request_parameters

      class KYCInitiateTosParams < Privy::Models::KyxTosRequestBody
        extend Privy::Internal::Type::RequestParameters::Converter
        include Privy::Internal::Type::RequestParameters

        def user_id: -> String

        def user_id=: (String _) -> String

        def initialize: (
          user_id: String,
          ?request_options: Privy::request_opts
        ) -> void

        def to_hash: -> {
          user_id: String,
          request_options: Privy::RequestOptions
        }
      end
    end
  end
end
