module Privy
  module Resources
    class Wallets
      class Transactions
        def get: (
          String wallet_id,
          chain: Privy::Models::transaction_chain_name_input,
          ?token: Privy::Models::Wallets::TransactionGetParams::token,
          ?asset: Privy::Models::Wallets::TransactionGetParams::asset,
          ?cursor: String,
          ?include_archived: bool,
          ?limit: Float?,
          ?tx_hash: String,
          ?request_options: Privy::request_opts
        ) -> Privy::Models::Wallets::TransactionGetResponse

        def initialize: (client: Privy::Client) -> void
      end
    end
  end
end
