module Privy
  module Models
    module Apps
      type allowlist_delete_params =
        { app_id: String } & Privy::Internal::Type::request_parameters

      class AllowlistDeleteParams < Privy::Internal::Type::BaseModel
        extend Privy::Internal::Type::RequestParameters::Converter
        include Privy::Internal::Type::RequestParameters

        attr_accessor app_id: String

        def initialize: (
          app_id: String,
          ?request_options: Privy::request_opts
        ) -> void

        def to_hash: -> {
          app_id: String,
          request_options: Privy::RequestOptions
        }
      end
    end
  end
end
